Repository knative/docs, pull requests merged in 2018-08, with the labels that each got.

#262 Update Scaling working group Hangout link
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#266 Add PKS to choosing a cluster paragraph
  install/README.md
Labels: approved, lgtm, size/XS

#305 Remove space from command
  serving/outbound-network-access.md
Labels: approved, lgtm, size/XS

#313 Add knative-users as as access option for Team Drive
  community/CONTRIBUTING.md
  community/ROLES.md
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#310 Add instructions for OpenShift
  install/Knative-with-OpenShift.md
  install/README.md
  install/scripts/knative-with-openshift.sh
Labels: approved, lgtm, size/L

#317 Fix broken link
  build/builds.md
Labels: approved, lgtm, size/XS

#314 Remove instructions for checking Prow logs from Google Cloud Console
  community/REVIEWING.md
Labels: approved, lgtm, size/S

#298 Add an elixir language sample using the phoenix framework to the knat…
  serving/samples/helloworld-elixir/.gitignore
  serving/samples/helloworld-elixir/Dockerfile
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-elixir/assets/brunch-config.js
  serving/samples/helloworld-elixir/assets/css/app.css
  serving/samples/helloworld-elixir/assets/css/phoenix.css
  serving/samples/helloworld-elixir/assets/js/app.js
  serving/samples/helloworld-elixir/assets/js/socket.js
  serving/samples/helloworld-elixir/assets/package.json
  serving/samples/helloworld-elixir/assets/static/favicon.ico
  serving/samples/helloworld-elixir/assets/static/images/phoenix.png
  serving/samples/helloworld-elixir/assets/static/robots.txt
  serving/samples/helloworld-elixir/config/config.exs
  serving/samples/helloworld-elixir/config/dev.exs
  serving/samples/helloworld-elixir/config/prod.exs
  serving/samples/helloworld-elixir/config/prod.secret.exs.sample
  serving/samples/helloworld-elixir/config/test.exs
  serving/samples/helloworld-elixir/lib/hello.ex
  serving/samples/helloworld-elixir/lib/hello/application.ex
  serving/samples/helloworld-elixir/lib/hello_web.ex
  serving/samples/helloworld-elixir/lib/hello_web/channels/user_socket.ex
  serving/samples/helloworld-elixir/lib/hello_web/controllers/page_controller.ex
  serving/samples/helloworld-elixir/lib/hello_web/endpoint.ex
  serving/samples/helloworld-elixir/lib/hello_web/gettext.ex
  serving/samples/helloworld-elixir/lib/hello_web/router.ex
  serving/samples/helloworld-elixir/lib/hello_web/templates/layout/app.html.eex
  serving/samples/helloworld-elixir/lib/hello_web/templates/page/index.html.eex
  serving/samples/helloworld-elixir/lib/hello_web/views/error_helpers.ex
  serving/samples/helloworld-elixir/lib/hello_web/views/error_view.ex
  serving/samples/helloworld-elixir/lib/hello_web/views/hello_view.ex
  serving/samples/helloworld-elixir/lib/hello_web/views/layout_view.ex
  serving/samples/helloworld-elixir/lib/hello_web/views/page_view.ex
  serving/samples/helloworld-elixir/mix.exs
  serving/samples/helloworld-elixir/mix.lock
  serving/samples/helloworld-elixir/priv/gettext/en/LC_MESSAGES/errors.po
  serving/samples/helloworld-elixir/priv/gettext/errors.pot
  serving/samples/helloworld-elixir/rel/config.exs
  serving/samples/helloworld-elixir/service.yaml
  serving/samples/helloworld-elixir/test/hello_web/controllers/page_controller_test.exs
  serving/samples/helloworld-elixir/test/hello_web/views/error_view_test.exs
  serving/samples/helloworld-elixir/test/hello_web/views/layout_view_test.exs
  serving/samples/helloworld-elixir/test/hello_web/views/page_view_test.exs
  serving/samples/helloworld-elixir/test/support/channel_case.ex
  serving/samples/helloworld-elixir/test/support/conn_case.ex
  serving/samples/helloworld-elixir/test/test_helper.exs
Labels: approved, lgtm, size/XXL

#322 Split serving into two separate work groups: observability and networking.
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/M

#285 Add glossary.md
  resources.md
Labels: approved, lgtm, size/L

#318 Updates to clarify install instructions
  install/Knative-with-GKE.md
Labels: approved, lgtm, size/M

#320 Updating app deployment guide
  install/getting-started-knative-app.md
Labels: approved, lgtm, size/M

#315 Correct typos in OpenShift instructions
  install/Knative-with-OpenShift.md
Labels: approved, lgtm, size/XS

#301 Making a change to default azure location to reflect the correct Azure
  install/Knative-with-AKS.md
Labels: approved, lgtm, size/XS

#307 Add applying the knative route and config
  serving/samples/thumbnailer-go/README.md
Labels: approved, lgtm, size/XS

#326 Sync install instructions with GKE version
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, size/L

#248 Update Telemetry readmes
  serving/accessing-logs.md
  serving/accessing-metrics.md
  serving/installing-logging-metrics-traces.md
  serving/samples/telemetry-go/README.md
  serving/samples/telemetry-go/sample.yaml
Labels: approved, lgtm, size/L

#327 Update accessing-logs.md
  serving/accessing-logs.md
Labels: approved, lgtm, size/XS

#329 Clarifies working directory to run command
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/XS

#330 Correct name of .yaml file
  serving/samples/thumbnailer-go/README.md
Labels: approved, lgtm, size/XS

#331 Update our docs to document the 0.1.1 release.
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, size/M

#334 Fix a typo in the path so that ko can be used to deploy the sample.
  eventing/samples/k8s-events/function.yaml
Labels: approved, lgtm, size/XS

#336 Update Build WG meeting information
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#316 Add a helloworld sample for haskell
  serving/samples/helloworld-haskell/.gitignore
  serving/samples/helloworld-haskell/Dockerfile
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-haskell/app/Main.hs
  serving/samples/helloworld-haskell/package.yaml
  serving/samples/helloworld-haskell/service.yaml
  serving/samples/helloworld-haskell/stack.yaml
Labels: approved, lgtm, size/L

#325 Doc to introduce how to install ExternalDNS within Knative
  serving/using-external-dns.md
Labels: approved, lgtm, size/L

#347 Update ROLES.md
  community/ROLES.md
Labels: approved, lgtm, size/XS

#346 remove redundant step in source-to-url deployment
  serving/samples/source-to-url-go/README.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#357 Fail fast in update-deps.sh when sourcing library.sh
  hack/update-deps.sh
Labels: approved, lgtm, size/XS

#354 add productivity wg
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#356 Update ExternalDNS setup doc to require Cloud DNS scope when creating a cluster
  serving/using-external-dns.md
Labels: approved, lgtm, size/S

#339 Adding GitHub Sample for move from eventing.
  eventing/samples/github-events/Dockerfile
  eventing/samples/github-events/README.md
  eventing/samples/github-events/auth.yaml
  eventing/samples/github-events/flow.yaml
  eventing/samples/github-events/function.go
  eventing/samples/github-events/function.yaml
  eventing/samples/github-events/githubsecret.yaml
  eventing/samples/github-events/personal_access_token.png
Labels: approved, lgtm, size/L

#363 Run eventing samples from the samples home directory
  eventing/samples/event-flow/README.md
  eventing/samples/github-events/README.md
  eventing/samples/k8s-events/README.md
Labels: approved, lgtm, size/M

#364 Fix link to Error Conditions and Reporting page...
  serving/debugging-application-issues.md
Labels: approved, lgtm, size/XS

#362 Add documentation for build timeout
  build/builds.md
Labels: approved, lgtm, size/S

#360 services.serving.knative.dev -> ksvc, adding check install guide
  eventing/samples/github-events/README.md
  eventing/samples/k8s-events/README.md
  images/knative-version.png
  install/README.md
  install/check-install-version.md
  install/getting-started-knative-app.md
  serving/samples/gitwebhook-go/README.md
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/README.md
  serving/samples/source-to-url-go/README.md
Labels: approved, lgtm, size/L

#366 Fix WG calendar link after original meeting was deleted.
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#367 Really fix URL to the WG meeting
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS
