Repository knative/docs, pull requests merged in 2018-12, with the labels that each got.

#332 Fluentd DaemonSet needs a specific Label on Nodes
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, needs eng input, size/M

#608 Update some docs for installation of knative on GKE
  install/Knative-with-GKE.md
Labels: approved, lgtm, size/M

#617 Fix spelling error
  serving/samples/autoscale-go/README.md
Labels: approved, lgtm, size/XS

#629 move eventing to 0.2.1 release
  eventing/README.md
Labels: approved, lgtm, size/XS

#637 Update kubectl apply URLs to use release artifacts
  eventing/README.md
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-PKS.md
Labels: approved, lgtm, size/M

#638 Format markdown
  eventing/README.md
  install/Knative-with-GKE.md
Labels: approved, lgtm, size/S

#641 Fix my username :)
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#607 Add more content about granting CloudDNS permission to GKE cluster
  serving/using-external-dns-on-gcp.md
  serving/using-external-dns.md
Labels: approved, lgtm, size/XL

#634 samples/autoscale-go: simplify instructions
  serving/samples/autoscale-go/Dockerfile
  serving/samples/autoscale-go/README.md
  serving/samples/autoscale-go/service.yaml
Labels: approved, lgtm, size/M

#640 Add PKS information to configuring outbound access setup
  serving/outbound-network-access.md
Labels: approved, lgtm, size/XS

#631 Fixed the path in example that shows how to copy private key from id_rsa file
  build/auth.md
Labels: approved, lgtm, size/XS

#650 Format markdown
  community/WORKING-GROUPS.md
  serving/outbound-network-access.md
  serving/samples/autoscale-go/README.md
  serving/using-external-dns-on-gcp.md
Labels: approved, lgtm, size/L

#643 Update issue templates
  .github/ISSUE_TEMPLATE/bug-in-existing-docs.md
  .github/ISSUE_TEMPLATE/feature-request----new-or-updated-documentation.md
Labels: approved, lgtm, size/M

#654 Remove repeated words
  eventing/samples/github-source/README.md
  serving/samples/autoscale-go/README.md
Labels: approved, lgtm, size/XS

#648 Update service.yaml in the gitwebhook sample
  serving/samples/gitwebhook-go/service.yaml
Labels: approved, lgtm, size/XS

#658 Format markdown
  serving/samples/autoscale-go/README.md
Labels: approved, lgtm, size/XS

#627 Add Docker for Mac setup instructions.
  install/Knative-with-Docker-for-Mac.md
  install/README.md
Labels: approved, lgtm, size/L

#659 Fix an error in README of serving/sample/telemetry-go
  serving/samples/telemetry-go/README.md
Labels: approved, lgtm, size/XS

#661 Restore code in the helloworld-haskell README
  serving/samples/helloworld-haskell/README.md
Labels: approved, lgtm, size/M

#656 Creating OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#664 Update the link to the Eventing Working Group calendar.
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#666 Add link to source code
  serving/samples/blue-green-deployment.md
Labels: approved, lgtm, size/XS

#665 Use lowercase 'b' for builders
  build/README.md
  build/builder-contract.md
Labels: approved, lgtm, size/S

#669 Format markdown
  build/README.md
  build/builder-contract.md
  serving/samples/blue-green-deployment.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#651 serving/samples: update helloworld-nodejs to nodejs v10
  serving/samples/helloworld-nodejs/Dockerfile
  serving/samples/helloworld-nodejs/package-lock.json
  serving/samples/helloworld-nodejs/package.json
Labels: approved, lgtm, needs eng input, size/L

#671 Updates to OWNERS so Prow will uses ALIASES for autoassignments
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#672 Add refernce to helloworld haskell section
  serving/samples/README.md
Labels: approved, lgtm, size/XS

#674 Update old monitoring namespaces
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/S

#673 Update the GCP PubSub sample
  eventing/samples/gcp-pubsub-source/README.md
  eventing/samples/gcp-pubsub-source/subscriber.yaml
Labels: approved, kind/enhancement, kind/sample, lgtm, size/M

#675 Format markdown
  eventing/samples/gcp-pubsub-source/README.md
  serving/samples/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#676 Update README.md
  build/README.md
Labels: approved, lgtm, size/XS

#678 Adds more info for Docs contributors
  CONTRIBUTING.md
  community/CONTRIBUTING.md
  community/DOCS-CONTRIBUTING.md
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/L

#681 Format markdown
  community/DOCS-CONTRIBUTING.md
  community/WORKING-GROUPS.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#635 Fix knative minikube installation doc
  install/Knative-with-Minikube.md
Labels: approved, lgtm, needs eng input, size/XS

#542 Adv. install topic - pluggable components
  install/Knative-custom-install.md
Labels: approved, kind/new-docs-needed, lgtm, needs eng input, priority/1, size/L

#683 Format markdown
  install/Knative-custom-install.md
Labels: approved, lgtm, size/L

#684 Fixing odd sentence
  install/Knative-custom-install.md
Labels: approved, lgtm, size/XS

#685 Add annotations to autoscale-go sample.
  serving/samples/autoscale-go/README.md
  serving/samples/autoscale-go/service.yaml
Labels: approved, lgtm, size/L
