Repository knative/docs, pull requests merged in 2018-10, with the labels that each got.

#408 Add Documentation working group
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#413 Update autoscale-go serving sample with ContainerConcurrency changes
  serving/samples/autoscale-go/README.md
Labels: approved, lgtm, size/M

#439 Updating Container Engine to new name
  serving/outbound-network-access.md
Labels: approved, lgtm, size/XS

#440 Moving documentation WG to Tuesdays
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#441 Update Observability WG meeting information & fix Slack channel links for all WGs
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#352 Add instruction to use LetsEncrypt through CertManager.
  serving/using-an-ssl-cert.md
  serving/using-cert-manager-on-gcp.md
Labels: approved, lgtm, needs edits, size/L

#442 Revert ksvc changes
  eventing/samples/k8s-events/README.md
  install/getting-started-knative-app.md
  serving/samples/gitwebhook-go/README.md
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/README.md
  serving/samples/source-to-url-go/README.md
Labels: approved, lgtm, size/L

#434 Update knative/test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#419 minor edits to examples
  eventing/samples/k8s-events/README.md
  eventing/samples/k8s-events/function.yaml
Labels: approved, kind/enhancement, lgtm, priority/1, size/XS

#443 Make samples less scary when no env var is provided
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-csharp/Startup.cs
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-go/helloworld.go
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-haskell/app/Main.hs
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-java/src/main/java/com/example/helloworld/HelloworldApplication.java
  serving/samples/helloworld-nodejs/Dockerfile
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-nodejs/app.js
  serving/samples/helloworld-nodejs/package.json
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-php/index.php
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-python/app.py
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-ruby/app.rb
  serving/samples/helloworld-rust/README.md
  serving/samples/helloworld-rust/src/main.rs
Labels: approved, lgtm, size/M

#437 Fix knative-monitoring namespace and accessing-logs URL
  install/Knative-with-OpenShift.md
  install/scripts/knative-with-openshift.sh
  serving/accessing-logs.md
  serving/installing-logging-metrics-traces.md
  serving/samples/telemetry-go/README.md
  serving/setting-up-a-logging-plugin.md
Labels: approved, lgtm, size/M

#432 Close response body in autoscale-go sample test program
  serving/samples/autoscale-go/test/test.go
Labels: approved, kind/sample, lgtm, needs eng input, size/XS

#453 Clojure helloworld serving sample
  serving/samples/README.md
  serving/samples/helloworld-clojure/.gitignore
  serving/samples/helloworld-clojure/Dockerfile
  serving/samples/helloworld-clojure/README.md
  serving/samples/helloworld-clojure/project.clj
  serving/samples/helloworld-clojure/service.yaml
  serving/samples/helloworld-clojure/src/helloworld/core.clj
Labels: approved, lgtm, size/L

#414 Improvements to OpenShift installation
  install/Knative-with-Minishift.md
  install/Knative-with-OpenShift.md
  install/README.md
  install/scripts/istio-openshift-policies.sh
  install/scripts/knative-openshift-policies.sh
  install/scripts/knative-with-openshift.sh
Labels: approved, kind/enhancement, lgtm, priority/2, size/L

#459 Update PKS docs clarifying the need to enable privileged containers
  install/Knative-with-PKS.md
Labels: approved, lgtm, size/S

#465 Make the Clojure greeting unscary.
  serving/samples/helloworld-clojure/README.md
  serving/samples/helloworld-clojure/src/helloworld/core.clj
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/README.md
Labels: approved, lgtm, size/M

#458 serving/helloworld-nodejs: Respect the PORT env var
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-nodejs/app.js
Labels: approved, lgtm, size/S

#460 serving/helloworld-php: Respect the PORT env var
  serving/samples/helloworld-php/Dockerfile
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-php/index.php
Labels: approved, lgtm, size/S

#462 serving/helloworld-csharp: respect the port env var
  serving/samples/helloworld-csharp/Program.cs
  serving/samples/helloworld-csharp/README.md
Labels: approved, lgtm, size/S

#463 serving/helloworld-haskell: respect the port env var
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-haskell/app/Main.hs
Labels: approved, lgtm, size/S

#457 serving/helloworld-go: Respect the PORT env var
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-go/helloworld.go
Labels: approved, lgtm, size/S

#475 Clean up formatting on with-any-k8s steps
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, size/XS

#468 Clojure helloworld serve on $PORT
  serving/samples/helloworld-clojure/README.md
  serving/samples/helloworld-clojure/src/helloworld/core.clj
Labels: approved, lgtm, size/XS

#381 Create Hello World program with Kotlin
  serving/samples/README.md
  serving/samples/helloworld-kotlin/Dockerfile
  serving/samples/helloworld-kotlin/README.md
  serving/samples/helloworld-kotlin/build.gradle
  serving/samples/helloworld-kotlin/service.yaml
  serving/samples/helloworld-kotlin/src/main/kotlin/com/example/hello/Main.kt
Labels: approved, lgtm, needs edits, needs eng input, size/L

#452 Added a serving sample for dart
  serving/samples/helloworld-dart/Dockerfile
  serving/samples/helloworld-dart/README.md
  serving/samples/helloworld-dart/bin/server.dart
  serving/samples/helloworld-dart/pubspec.lock
  serving/samples/helloworld-dart/pubspec.yaml
  serving/samples/helloworld-dart/service.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#477 Fix Dart sample
  serving/samples/helloworld-dart/README.md
  serving/samples/helloworld-dart/service.yaml
Labels: approved, lgtm, size/M

#476 Fix typo
  serving/debugging-application-issues.md
Labels: approved, lgtm, size/XS

#483 README.md: imported and not used: "flag"
  serving/samples/helloworld-go/README.md
Labels: approved, lgtm, size/XS

#486 Reverting the namespace rename knative-monitoring
  install/Knative-with-OpenShift.md
  install/scripts/knative-with-openshift.sh
  serving/accessing-logs.md
  serving/installing-logging-metrics-traces.md
  serving/samples/telemetry-go/README.md
  serving/setting-up-a-logging-plugin.md
Labels: approved, lgtm, size/S

#416 Update references to monitoring namespace (#407)
  eventing/samples/k8s-events/README.md
  install/Knative-with-OpenShift.md
  install/scripts/knative-with-openshift.sh
  serving/debugging-application-issues.md
  serving/samples/autoscale-go/README.md
  serving/samples/telemetry-go/README.md
  serving/samples/telemetry-go/telemetrysample.go
Labels: approved, lgtm, size/S

#435 Update accessing-metrics.md with knative-metrics namespace.
  serving/accessing-metrics.md
Labels: approved, lgtm, size/XS

#490 Remove cmd dir from eventing.
  hack/update-deps.sh
  vendor/github.com/knative/eventing/cmd/controller-manager/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/controller-manager/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/cmd/controller/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/controller/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/cmd/sendevent/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/sendevent/kodata/VENDOR-LICENSE
  vendor/github.com/knative/eventing/cmd/webhook/kodata/LICENSE
  vendor/github.com/knative/eventing/cmd/webhook/kodata/VENDOR-LICENSE
Labels: approved, lgtm, size/S
