Repository knative/docs, pull requests merged in 2018-11, with the labels that each got.

#487 Update docs to refer to Istio 1.0.2
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/M

#491 Update Hello world - Java
  serving/samples/helloworld-java/Dockerfile
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-java/src/main/java/com/example/helloworld/HelloworldApplication.java
  serving/samples/helloworld-ruby/README.md
Labels: approved, lgtm, size/S

#450 docker -> Dockerfile for syntax highlighting
  serving/samples/helloworld-nodejs/README.md
Labels: approved, lgtm, size/XS

#492 Use the ksvc shortname for services
  eventing/samples/k8s-events/README.md
  install/getting-started-knative-app.md
  serving/samples/blue-green-deployment.md
  serving/samples/gitwebhook-go/README.md
  serving/samples/helloworld-clojure/README.md
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-dart/README.md
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-kotlin/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/README.md
  serving/samples/knative-routing-go/README.md
  serving/samples/source-to-url-go/README.md
  serving/setting-up-a-logging-plugin.md
  serving/using-an-ssl-cert.md
  serving/using-cert-manager-on-gcp.md
Labels: approved, lgtm, size/M

#496 Add docs from eventing sources
  eventing/samples/gcp-pubsub-source/README.md
  eventing/samples/gcp-pubsub-source/channel.yaml
  eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
  eventing/samples/gcp-pubsub-source/subscriber.yaml
  eventing/samples/k8s-events/Dockerfile
  eventing/samples/k8s-events/Kibana.png
  eventing/samples/k8s-events/README.md
  eventing/samples/k8s-events/flow.yaml
  eventing/samples/k8s-events/function.go
  eventing/samples/k8s-events/function.yaml
  eventing/samples/k8s-events/serviceaccount.yaml
  eventing/samples/kubernetes-event-source/README.md
  eventing/samples/kubernetes-event-source/channel.yaml
  eventing/samples/kubernetes-event-source/k8s-events.yaml
  eventing/samples/kubernetes-event-source/serviceaccount.yaml
  eventing/samples/kubernetes-event-source/subscription.yaml
Labels: approved, lgtm, size/XL

#509 Remove outdated samples
  eventing/samples/event-flow/README.md
  eventing/samples/event-flow/configuration.yaml
  eventing/samples/event-flow/device/package.json
  eventing/samples/event-flow/device/send-data.js
  eventing/samples/event-flow/eventsource.yaml
  eventing/samples/event-flow/eventtype.yaml
  eventing/samples/event-flow/flow.yaml
  eventing/samples/event-flow/function.go
  eventing/samples/event-flow/route.yaml
  eventing/samples/event-flow/serviceaccount.yaml
  eventing/samples/event-flow/serviceaccountbinding.yaml
  eventing/samples/github-events/Dockerfile
  eventing/samples/github-events/README.md
  eventing/samples/github-events/auth.yaml
  eventing/samples/github-events/flow.yaml
  eventing/samples/github-events/function.go
  eventing/samples/github-events/function.yaml
  eventing/samples/github-events/githubsecret.yaml
  eventing/samples/github-events/personal_access_token.png
Labels: approved, lgtm, size/XXL

#511 Ignore GoLand files.
  .gitignore
Labels: approved, lgtm, size/XS

#528 updating wrong file name
  eventing/samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/XS

#524 Update the serving + build sample to use the new style.
  serving/samples/source-to-url-go/README.md
  serving/samples/source-to-url-go/service.yaml
Labels: approved, lgtm, size/M

#530 Update eventing top-level readme with @sebgoa feedback
  eventing/README.md
  eventing/data-plane.png
Labels: approved, lgtm, size/M

#534 Remove extra.yaml from a link to release-with-gcppubsub.yaml
  eventing/README.md
Labels: approved, lgtm, size/XS

#535 Change install instructions to use v0.2.1 instead of v0.2.0
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/M

#536 Remove redundant (and errorneous) installation of eventing-sources
  eventing/samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/S

#537 Make serving a prerequisite rather than a surprise later on
  eventing/samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/XS

#538 Kubernetes event source sample: get message dumper logs by label selector
  eventing/samples/kubernetes-event-source/README.md
Labels: approved, lgtm, size/XS

#521 Add a GitHubSource sample
  eventing/samples/github-source/README.md
  eventing/samples/github-source/channel.yaml
  eventing/samples/github-source/github-source.yaml
  eventing/samples/github-source/githubsecret.yaml
  eventing/samples/github-source/personal_access_token.png
  eventing/samples/github-source/subscription.yaml
  eventing/samples/github-source/webhook_created.png
Labels: approved, lgtm, size/L

#546 Update calendar information for TOC and Working Groups.
  community/TECH-OVERSIGHT-COMMITTEE.md
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/M

#532 Don't pass -n default to `ko`
  eventing/samples/gcp-pubsub-source/README.md
Labels: approved, lgtm, size/S

#510 Sync README.md and service.yaml
  serving/samples/source-to-url-go/README.md
Labels: approved, lgtm, size/XS

#549 This fixes some field renaming.
  eventing/samples/gcp-pubsub-source/subscriber.yaml
Labels: approved, lgtm, size/XS

#559 Update pubsub sample
  eventing/samples/gcp-pubsub-source/README.md
  eventing/samples/gcp-pubsub-source/channel.yaml
  eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
  eventing/samples/gcp-pubsub-source/subscriber.yaml
Labels: approved, lgtm, size/L

#547 Update owners
  OWNERS
Labels: approved, lgtm, size/XS

#500 serving/samples/helloworld-csharp: simplify and standardize Dockerfile
  serving/samples/helloworld-csharp/Dockerfile
  serving/samples/helloworld-csharp/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#504 serving/samples/helloworld-php: simplify and standardize Dockerfile
  serving/samples/helloworld-php/Dockerfile
  serving/samples/helloworld-php/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/S

#506 serving/samples/helloworld-python: simplify and standardize Dockerfile
  serving/samples/helloworld-python/Dockerfile
  serving/samples/helloworld-python/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#508 serving/samples/helloworld-go: simplify and standardize Dockerfile
  serving/samples/helloworld-go/Dockerfile
  serving/samples/helloworld-go/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#507 serving/samples/helloworld-nodejs: simplify and standardize Dockerfile
  serving/samples/helloworld-nodejs/Dockerfile
  serving/samples/helloworld-nodejs/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, size/M

#561 Fix getting started
  install/getting-started-knative-app.md
Labels: approved, lgtm, size/XS

#499 serving/samples/helloworld-clojure: simplify and standardize Dockerfile
  serving/samples/helloworld-clojure/Dockerfile
  serving/samples/helloworld-clojure/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#560 Events work group -> Eventing
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#545 Require rack 2.0.6
  serving/samples/helloworld-ruby/Gemfile
  serving/samples/helloworld-ruby/Gemfile.lock
Labels: approved, kind/enhancement, kind/sample, lgtm

#454 Update OpenShift instructions to set Istio sidecar injector priviledged to true
  install/Knative-with-OpenShift.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#525 Adding an automated installation of Knative to IKS with a deploy button
  install/Knative-with-IKS.md
Labels: approved, lgtm, size/XS

#449 Adding Reactive java WebApp, with Eclipse Vert.x
  serving/samples/README.md
  serving/samples/helloworld-vertx/Dockerfile
  serving/samples/helloworld-vertx/README.md
  serving/samples/helloworld-vertx/pom.xml
  serving/samples/helloworld-vertx/service.yaml
  serving/samples/helloworld-vertx/src/main/java/com/example/helloworld/HelloWorld.java
Labels: approved, kind/new-docs-needed, kind/sample, lgtm, size/L

#502 serving/samples/helloworld-rust: simplify and standardize Dockerfile
  serving/samples/helloworld-rust/Dockerfile
  serving/samples/helloworld-rust/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/S

#505 serving/samples/helloworld-haskell: simplify and standardize Dockerfile
  serving/samples/helloworld-haskell/Dockerfile
  serving/samples/helloworld-haskell/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#512 serving/samples/helloworld-java: simplify and standardize Dockerfile
  serving/samples/helloworld-java/Dockerfile
  serving/samples/helloworld-java/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#516 serving/samples/helloworld-kotlin: simplify and standardize Dockerfile
  serving/samples/helloworld-kotlin/Dockerfile
  serving/samples/helloworld-kotlin/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/M

#501 serving/samples/helloworld-dart: simplify and standardize Dockerfile
  serving/samples/helloworld-dart/Dockerfile
  serving/samples/helloworld-dart/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/S

#564 Updated k8s doc use latest serving release.
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#576 Add notes for how to debug `curl`.
  install/getting-started-knative-app.md
  serving/samples/helloworld-go/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#574 Correct Namespace in Kabana UI link
  serving/accessing-logs.md
Labels: approved, lgtm, size/XS

#579 [samples/gitwebhook-go] Minor typo fix for gitwebhook-go.
  serving/samples/gitwebhook-go/README.md
Labels: approved, lgtm, size/XS

#563 Discover the K8S version for IKS deployment
  install/Knative-with-IKS.md
Labels: approved, lgtm, size/XS

#583 source-to-url: remove unnecessary yaml indentation
  serving/samples/source-to-url-go/README.md
Labels: approved, lgtm, size/S

#406 Replace Bazel commands with ko
  serving/setting-up-a-logging-plugin.md
Labels: approved, kind/enhancement, lgtm, size/XS

#589 [samples/grpc-ping-go] Minor typo fix for this example.
  serving/samples/grpc-ping-go/README.md
Labels: approved, lgtm, size/S

#598 Update gke-assigning-static-ip-address.md
  serving/gke-assigning-static-ip-address.md
Labels: approved, lgtm, size/XS

#591 Fixed broken link for eventing.
  README.md
Labels: approved, lgtm, size/XS

#590 [samples/knative-routing-go] Updated README for some keywords.
  serving/samples/knative-routing-go/README.md
Labels: approved, lgtm, size/M

#566 update Helloworld-Nodejs Dockerfile
  serving/samples/helloworld-nodejs/service.yaml
Labels: approved, lgtm, size/XS

#523 serving/samples/helloworld-java: update Dockerfile to respect PORT
  serving/samples/helloworld-java/Dockerfile
  serving/samples/helloworld-java/README.md
Labels: approved, kind/enhancement, kind/sample, lgtm, needs eng input, size/XS

#570 Updated helloworld-go by clarifying the `IP_ADDRESS` address.
  serving/samples/helloworld-go/README.md
Labels: approved, lgtm, size/M

#578 [sample/build-private-repo-go] Unify the format for build private repo.
  serving/samples/build-private-repo-go/README.md
Labels: approved, lgtm, size/S

#384 use base64 -w0 instead of some random high number
  build/builds.md
  serving/samples/build-private-repo-go/README.md
  serving/samples/build-private-repo-go/build-bot.yaml
Labels: approved, lgtm, needs eng input, size/S

#572 Use golang:alpine instead of golang for example Dockerfile.
  serving/samples/build-private-repo-go/README.md
Labels: approved, lgtm, size/XS

#582 use public image instead of requiring ko
  eventing/samples/kubernetes-event-source/README.md
  eventing/samples/kubernetes-event-source/subscription.yaml
Labels: approved, lgtm, size/XS

#568 Removed the unnecessary create namespace command under section for setting up GCP pubsub source
  eventing/README.md
Labels: approved, lgtm, size/XS

#596 Updating misspelling of their
  eventing/README.md
Labels: approved, lgtm, size/XS

#605 Fix spelling errors
  serving/samples/grpc-ping-go/grpc-ping.go
Labels: approved, lgtm, size/XS

#609 Remove images deletion step from e2e test / Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/dummy.go
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#451 Node.js serving sample README.md has inconsistent response example
  serving/samples/helloworld-nodejs/README.md
Labels: approved, lgtm, needs eng input, needs-ok-to-test, size/XS

#587 Simplify the Github sample.
  eventing/samples/github-source/README.md
  eventing/samples/github-source/channel.yaml
  eventing/samples/github-source/github-source.yaml
  eventing/samples/github-source/service.yaml
  eventing/samples/github-source/subscription.yaml
Labels: approved, lgtm, size/L

#610 Adding Caroline to the repo owners file
  OWNERS
Labels: approved, lgtm, size/XS
