Repository knative/docs, pull requests merged in 2018-09, with the labels that each got.

#368 fix typos in getting-started-knative-app.md
  install/getting-started-knative-app.md
Labels: approved, lgtm, size/XS

#370 Mention MutatingAdmissionWebhook is required for serving
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#378 README: fix link to "good first issue" label
  README.md
Labels: approved, lgtm, size/XS

#376 Build Templates Missing comma
  build/build-templates.md
Labels: approved, lgtm, size/XS

#274 Fix typos
  build/auth.md
  build/build-templates.md
  build/builds.md
  community/REVIEWING.md
  eventing/README.md
  install/Knative-with-Gardener.md
Labels: approved, lgtm, size/S

#371 Update test-infra dependency
  Gopkg.lock
  hack/update-deps.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, kind/infrastructure, lgtm, needs eng input, size/XS

#373 Remove flag package import
  serving/samples/helloworld-go/helloworld.go
Labels: approved, lgtm, needs eng input, size/XS

#388 fix typo in workingDir field name
  build/build-templates.md
Labels: approved, lgtm, size/XS

#372 Update docs to use kubectl long flags
  build/auth.md
  build/creating-builds.md
  build/installing-build-component.md
  eventing/README.md
  eventing/samples/event-flow/README.md
  eventing/samples/github-events/README.md
  eventing/samples/k8s-events/README.md
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
  install/check-install-version.md
  install/getting-started-knative-app.md
  serving/accessing-metrics.md
  serving/debugging-application-issues.md
  serving/gke-assigning-static-ip-address.md
  serving/installing-logging-metrics-traces.md
  serving/outbound-network-access.md
  serving/samples/autoscale-go/README.md
  serving/samples/blue-green-deployment.md
  serving/samples/build-private-repo-go/README.md
  serving/samples/buildpack-app-dotnet/README.md
  serving/samples/buildpack-function-nodejs/README.md
  serving/samples/gitwebhook-go/README.md
  serving/samples/grpc-ping-go/README.md
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/README.md
  serving/samples/knative-routing-go/README.md
  serving/samples/rest-api-go/README.md
  serving/samples/source-to-url-go/README.md
  serving/samples/telemetry-go/README.md
  serving/samples/thumbnailer-go/README.md
  serving/samples/traffic-splitting/README.md
  serving/setting-up-a-logging-plugin.md
  serving/using-a-custom-domain.md
  serving/using-an-ssl-cert.md
  serving/using-external-dns.md
Labels: approved, lgtm, size/XL

#394 cleanup remaining kubectl shorthand -o flags
  eventing/samples/github-events/README.md
  serving/samples/gitwebhook-go/README.md
  serving/samples/knative-routing-go/README.md
  serving/samples/traffic-splitting/README.md
Labels: approved, lgtm, size/XS

#395 Update README.md
  install/README.md
Labels: approved, lgtm, size/XS

#392 telemetry: document sd/prom manifest locations
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/S

#398 Update build WG calendar link
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#399 Remove &image yaml anchors
  serving/samples/build-private-repo-go/manifest.yaml
  serving/samples/buildpack-app-dotnet/sample.yaml
  serving/samples/buildpack-function-nodejs/sample.yaml
  serving/samples/source-to-url-go/README.md
  serving/samples/source-to-url-go/service.yaml
  serving/samples/thumbnailer-go/sample.yaml
Labels: approved, lgtm, size/S

#396 Fix typo in accessing-metrics command
  serving/accessing-metrics.md
Labels: approved, lgtm, size/XS

#405 Fix directory name
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/XS

#402 Remove incorrect kibana and elasticsearch pods
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/S

#415 Make Python example use the PORT env var instead of 8080
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-python/app.py
Labels: approved, lgtm, size/XS

#420 Update Networking WG calendar.
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#427 update calendar link for productivity wg
  community/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#426 Add note to community/CONTRIBUTING.md about gubernator
  community/CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#429 Change slack link to slack guidelines
  community/README.md
Labels: approved, kind/enhancement, lgtm, size/XS
