Repository knative/docs, pull requests merged in 2019-11, with the labels that each got.

#1953 Links to files in pubsub example
  docs/eventing/samples/gcp-pubsub-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1957 Cherry-picking changes to release 0.10
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/gcp-pubsub-source/event-display.yaml
  docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
  docs/eventing/samples/gcp-pubsub-source/trigger.yaml
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/L

#1959 PubSub source cherry-pick Release 0.10
  docs/eventing/samples/gcp-pubsub-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1963 Fix presubmit-link-check.sh
  test/presubmit-link-check.sh
Labels: approved, cla: yes, lgtm, size/S

#1663 Documentation about tracing for Knative Eventing.
  docs/eventing/accessing-traces.md
  docs/eventing/data/ee46c4c6be1df717b3b82f55b531912f.json
  docs/eventing/images/AnnotatedTrace.png
  docs/eventing/images/RawTrace.png
Labels: approved, cla: yes, kind/eventing, kind/observability, lgtm, size/XL

#1967 fix small typo in sample READMEs
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-java-quarkus/README.md
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-rserver/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-vertx/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/secrets-go/README.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/M

#1971 add external code samples
  docs/samples.md
Labels: approved, cla: yes, lgtm, size/XS

#1961 Add field imagePullSecrets
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, kind/serving, lgtm, size/M

#1877 Renamed autoscaling section, added details for PodAutoscaler custom resource
  docs/README.md
  docs/serving/configuring-autoscaling.md
Labels: approved, cla: yes, kind/serving, lgtm, size/M

#1975 fix broken links (from link checking report tool testing)
  community/samples/README.md
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-rserver/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-vertx/README.md
  docs/README.md
  docs/eventing/event-registry.md
  docs/eventing/getting-started.md
  docs/eventing/samples/README.md
  docs/eventing/samples/_index.md
  docs/eventing/samples/helloworld/README.md
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/kafka/channel/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gloo.md
  docs/install/README.md
  docs/install/installing-istio.md
  docs/serving/cluster-local-route.md
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cla: yes, lgtm, size/L

#1979 Issue 1977
  docs/eventing/README.md
  docs/eventing/samples/parallel/README.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/cron-source.yaml
  docs/eventing/samples/parallel/multiple-branches/parallel.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/cron-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/cron-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/steps.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/cron-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/steps.yaml
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/cron-source.yaml
  docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
  docs/eventing/samples/sequence/sequence-terminal/steps.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/cron-source.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
Labels: approved, cla: yes, lgtm, size/L

#1976 Update camel examples to reflect recent changes
  docs/eventing/samples/apache-camel-source/source_http_poller.yaml
  docs/eventing/samples/apache-camel-source/source_mqtt.yaml
  docs/eventing/samples/apache-camel-source/source_telegram.yaml
  docs/eventing/samples/apache-camel-source/source_timer.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1974 fix broken links (from link checking report tool testing)
  community/samples/README.md
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-rserver/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-vertx/README.md
  docs/README.md
  docs/eventing/event-registry.md
  docs/eventing/getting-started.md
  docs/eventing/samples/README.md
  docs/eventing/samples/_index.md
  docs/eventing/samples/helloworld/README.md
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/kafka/channel/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gloo.md
  docs/install/README.md
  docs/install/installing-istio.md
  docs/serving/cluster-local-route.md
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cla: yes, lgtm, size/L

#1982 Updated docs for reconciler / controllers in autoscaling
  docs/serving/configuring-autoscaling.md
Labels: approved, cla: yes, lgtm, size/XS

#1984 Cleanup Knative install versions page
  docs/install/check-install-version.md
Labels: approved, cla: yes, lgtm, size/L

#1990 Fix spelling errors
  docs/serving/samples/cloudevents/cloudevents-go/cloudevents.go
Labels: approved, cla: yes, lgtm, size/XS

#1988 Add missing _index.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1970 fix links to repos in temp API refdocs files
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XS

#1986 Template for new Docs pages
  contributing/new-page-template.md
Labels: approved, cla: yes, lgtm, size/M

#1992 Remove namespace definition from hello-world service.yaml
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-csharp/service.yaml
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-go/service.yaml
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/service.yaml
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/service.yaml
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/service.yaml
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/service.yaml
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-php/service.yaml
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-python/service.yaml
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-ruby/service.yaml
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-scala/helloworld-scala.yaml
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/hello-world/helloworld-shell/service.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S, triage/needs-eng-input

#1985 Added 'Creating Knative Services' section
  docs/serving/services/creating-services.md
Labels: approved, cla: yes, lgtm, size/M

#1997 [release-0.10] Cherry-pick presubmit link checker tool
  test/presubmit-link-check.sh
Labels: approved, cla: yes, lgtm, size/M

#1996 updates for kafka based on 0.10.x release
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kafka/source/event-source.yaml
Labels: approved, cla: yes, lgtm, size/S

#1998 fix gloo docs for 0.10.0 release
  docs/install/Knative-with-Gloo.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S
