Repository knative/docs, pull requests merged in 2019-04, with the labels that each got.

#1124 build: code block was smooshed
  docs/build/installing-build-component.md
Labels: approved, cherrypick-0.4, cla: yes, lgtm, size/XS

#1123 Format markdown
  contributing/WORKING-GROUPS.md
  docs/build/auth.md
  docs/eventing/README.md
  docs/eventing/samples/cronjob-source/README.md
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/sources/README.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-PKS.md
  docs/serving/samples/README.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/traffic-splitting/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1103 Update the iot-core demo to use Broker rather than Channel
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/iot-core/channel.yaml
  docs/eventing/samples/iot-core/gcp-pubsub-source.yaml
  docs/eventing/samples/iot-core/trigger.yaml
Labels: approved, cla: yes, lgtm, size/L

#1049 Update the GcpPubSubSource example to use Broker, rather than Channel.
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/gcp-pubsub-source/channel.yaml
  docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
  docs/eventing/samples/gcp-pubsub-source/trigger.yaml
Labels: approved, cla: yes, lgtm, size/M

#1091 Update the kubernetes-event-source example to use Broker, rather than Channel.
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/channel.yaml
  docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
  docs/eventing/samples/kubernetes-event-source/serviceaccount.yaml
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
Labels: approved, cla: yes, lgtm, size/M

#1122 Fix 'verion' mispelling in check-install-version
  docs/install/check-install-version.md
Labels: approved, cla: yes, lgtm, size/XS

#1129 Cherry-pick
  docs/build/auth.md
  docs/build/installing-build-component.md
  docs/eventing/README.md
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
  docs/install/Knative-with-GKE.md
  docs/install/getting-started-knative-app.md
  docs/serving/samples/hello-world/helloworld-shell/Dockerfile
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/hello-world/helloworld-shell/_index.md
  docs/serving/samples/hello-world/helloworld-shell/invoke.go
  docs/serving/samples/hello-world/helloworld-shell/script.sh
  docs/serving/samples/hello-world/helloworld-shell/service.yaml
Labels: approved, cla: yes, lgtm, size/L

#1125 Eventing v0.5 updates
  docs/eventing/README.md
  docs/eventing/images/broker-trigger-overview.svg
Labels: approved, cla: yes, kind/eventing, kind/eventing-sources, lgtm, size/M

#1132 Delete old version of site landing page
  _index.html
Labels: approved, cla: yes, lgtm, size/L

#1135 Conflict message removed.
  docs/install/Knative-with-GKE.md
Labels: approved, cla: yes, lgtm, size/XS

#1128 Update PR template with branch info
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#1120 Updated generated documentation for serving
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XL

#1017 Proposal: Update for Knative Governance [WIP]
  contributing/README.md
  contributing/REPOSITORY-GUIDELINES.md
  contributing/SLACK-GUIDELINES.md
  contributing/STEERING-COMMITTEE.md
  contributing/WORKING-GROUP-PROCESSES.md
Labels: approved, cla: yes, do-not-merge/hold, size/L

#1140 Reflect #api channel rename to #serving-api
  contributing/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#1141 Add Ryan Gregg to the Knative Steering Committee page
  contributing/STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#1145 Update dep for test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#1121 Update sample to use the new URL field
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cla: yes, lgtm, size/S

#1149 v0.4 -> v0.5
  docs/build/installing-build-component.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-Minishift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, kind/install, lgtm, size/L

#1126 message_dumper to event_display
  docs/eventing/samples/cronjob-source/README.md
  docs/eventing/samples/cronjob-source/service.yaml
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/gcp-pubsub-source/trigger.yaml
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/github-source/service.yaml
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/iot-core/trigger.yaml
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
Labels: approved, cla: yes, lgtm, size/M

#1147 update cleanup
  docs/eventing/samples/kubernetes-event-source/README.md
Labels: approved, cla: yes, kind/enhancement, kind/eventing, kind/eventing-sources, lgtm, priority/1, size/XS

#1142 API docs for v0.5.0 release
  docs/reference/build.md
  docs/reference/eventing/eventing-sources.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, kind/build, kind/enhancement, kind/eventing, kind/eventing-sources, kind/serving, size/XL

#1094 fix export IP Address step
  docs/serving/samples/autoscale-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1156 Format markdown
  contributing/README.md
  contributing/REPOSITORY-GUIDELINES.md
  contributing/SLACK-GUIDELINES.md
  contributing/STEERING-COMMITTEE.md
  contributing/WORKING-GROUP-PROCESSES.md
  contributing/WORKING-GROUPS.md
  docs/eventing/README.md
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#1056 #fixit remove ref to subscriber
  docs/eventing/samples/gcp-pubsub-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1075 Import previous knative blogs from medium
  blog/articles/Build--deploy--manage-modern-serverless-workloads-using-Knative-on-Kubernetes.html
  blog/articles/build-deploy-manage-modern-serverless-workloads-using-knative-on-kubernetes.html
  blog/articles/images/gopher.png
  blog/articles/images/koservices.png
  blog/articles/images/multipleservices.png
  blog/articles/images/scaffold.png
  blog/articles/images/singleservice.png
  blog/articles/knative-v0-3-autoscaling-a-love-story.html
  blog/articles/ko-fast-kubernetes-microservice-development-in-go.html
  blog/events/Knative-at-KubeCon-Seattle.html
  blog/events/knative-at-kubecon-seattle.html
  blog/images/grpc.png
  blog/images/istio.png
  blog/images/principled-objects.png
  blog/releases/Announcing-Knative-v0-2-Release.html
  blog/releases/Announcing-Knative-v0-3-Release.html
  blog/releases/announcing-knative-v0-2-release.html
  blog/releases/announcing-knative-v0-3-release.html
  blog/releases/announcing-knative-v0-4-release.html
Labels: approved, cla: yes, lgtm, size/XL

#1152 Update .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#1157 Fix bash syntax error
  docs/install/Knative-with-Minishift.md
Labels: approved, cla: yes, lgtm, size/XS

#1153 Bitbucket Event Source
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/M

#982 suggest using knative-operators's installation script in minishift doc
  docs/install/Knative-with-Minishift.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/M

#1058 Update community Dart sample
  community/samples/serving/helloworld-dart/.gitignore
  community/samples/serving/helloworld-dart/bin/server.dart
  community/samples/serving/helloworld-dart/pubspec.lock
  community/samples/serving/helloworld-dart/pubspec.yaml
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/M

#981 link Install to openshift-cloud-functions/knative-operators
  docs/install/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1160 convert all hardcoded blog img links to relative
  blog/articles/Knative v0.3 Autoscaling — A Love Story _ Knative.html
  blog/articles/build-deploy-manage-modern-serverless-workloads-using-knative-on-kubernetes.html
  blog/articles/images/1_BkMXQfMrRERP_n04_C7geQ.png
  blog/articles/images/1_Ec5KvL9ux3AvlMFJ6liiDw.png
  blog/articles/images/1_F-mOzMbo-Yy2XWTSgJkfQA.png
  blog/articles/images/1_O6ZSdCeotT7J4zSbDNIsYw.png
  blog/articles/images/1_OwJCCIaSFFSE1Rv6ZPuTBQ.png
  blog/articles/images/1_fSxikLtB7TNsV-6Y3u5g2w.png
  blog/articles/images/1_znzl9nGKIif51YRwmBw_BA.png
  blog/articles/knative-v0-3-autoscaling-a-love-story.html
  blog/articles/ko-fast-kubernetes-microservice-development-in-go.html
  blog/events/knative-at-kubecon-seattle.html
  blog/releases/announcing-knative-v0-2-release.html
  blog/releases/announcing-knative-v0-3-release.html
  blog/releases/announcing-knative-v0-4-release.html
Labels: approved, cla: yes, lgtm, size/XL

#1161 add 'Documentation' to main menu
  docs/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#1163 Fix broken resource links
  docs/install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, size/S

#1164 Cherry-pick: Fix broken resource links (#1163)
  docs/install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, size/S

#1111 Improve Java Hello World
  docs/serving/samples/hello-world/helloworld-java/.dockerignore
  docs/serving/samples/hello-world/helloworld-java/Dockerfile
  docs/serving/samples/hello-world/helloworld-java/README.md
  docs/serving/samples/hello-world/helloworld-java/pom.xml
  docs/serving/samples/hello-world/helloworld-kotlin/Dockerfile
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
Labels: approved, cla: yes, lgtm, size/M

#1165 Release 0.5
  community/samples/serving/helloworld-dart/.gitignore
  community/samples/serving/helloworld-dart/bin/server.dart
  community/samples/serving/helloworld-dart/pubspec.lock
  community/samples/serving/helloworld-dart/pubspec.yaml
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
  docs/install/Knative-with-Minishift.md
  docs/install/README.md
Labels: approved, cla: yes, lgtm, size/L

#1170 delete localhost file
  blog/articles/Knative v0.3 Autoscaling — A Love Story _ Knative.html
Labels: approved, cla: yes, lgtm, size/XL

#1172 More fixes to blogs
  blog/_index.md
  blog/articles/_index.md
  blog/articles/knative-v0-3-autoscaling-a-love-story.html
  blog/events/_index.md
  blog/releases/_index.md
Labels: approved, cla: yes, lgtm, size/S

#1176 knative.slack.com -> slack.knative.dev
  contributing/WORKING-GROUPS.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/S

#1171 Replace knative-ingressgateway service with istio-ingressgateway service
  docs/serving/samples/knative-routing-go/routing.yaml
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1178 Update Knative-custom-install.md
  docs/install/Knative-custom-install.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1114 Update installation documentation with Minishift
  docs/install/Knative-with-Minishift.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/M

#1180 fix README for community Dart sample
  community/samples/serving/helloworld-dart/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1143 helloworld-go: install CA certs
  community/samples/serving/helloworld-elixir/Dockerfile
  community/samples/serving/helloworld-elixir/README.md
  docs/install/Knative-with-Gloo.md
  docs/serving/samples/hello-world/helloworld-go/Dockerfile
  docs/serving/samples/hello-world/helloworld-go/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1182 update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#1027 Knative with Gardener - Fix Installing Istio Typo
  docs/install/Knative-with-Gardener.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1131 Mention IKS's one-click install process
  docs/install/Knative-with-IKS.md
Labels: approved, cherrypick-0.5, cla: yes, kind/enhancement, lgtm, needs edits, size/M

#1186 Add Paul Morie from Red Hat to the Knative Steering Committee
  contributing/STEERING-COMMITTEE.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1188 Fix some spelling mistakes of docs
  docs/build/auth.md
  docs/eventing/debugging/README.md
  docs/eventing/samples/cronjob-source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1187 Update READMEs to make community samples discoverable.
  community/samples/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1198 cherrypick: community samples discoverable. (#1187)
  community/samples/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1196 Fix typo Knatve -> Knative
  community/samples/serving/helloworld-vertx/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, ok-to-test, size/XS

#1195 Add label install to guides, update Minikube
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-Minishift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/L

#1155 Added Hello World Java using Spark Java Framework
  docs/serving/samples/hello-world/helloworld-java-spark/.gitignore
  docs/serving/samples/hello-world/helloworld-java-spark/.mvn/wrapper/MavenWrapperDownloader.java
  docs/serving/samples/hello-world/helloworld-java-spark/.mvn/wrapper/maven-wrapper.jar
  docs/serving/samples/hello-world/helloworld-java-spark/.mvn/wrapper/maven-wrapper.properties
  docs/serving/samples/hello-world/helloworld-java-spark/Dockerfile
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/helloworld.zip
  docs/serving/samples/hello-world/helloworld-java-spark/main/java/com/example/helloworld/HelloWorldApplication.java
  docs/serving/samples/hello-world/helloworld-java-spark/mvnw
  docs/serving/samples/hello-world/helloworld-java-spark/mvnw.cmd
  docs/serving/samples/hello-world/helloworld-java-spark/pom.xml
  docs/serving/samples/hello-world/helloworld-java-spark/service.yaml
  docs/serving/samples/hello-world/helloworld-java-spark/src/main/java/com/example/helloworld/HelloWorldApplication.java
Labels: approved, cla: yes, lgtm, needs-eng-input, size/XL

#1206 docs: Remove `--save` from `npm install`
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, ok-to-test, size/XS

#1200 Fix some spelling mistakes in docs
  docs/install/Knative-with-Minishift.md
  docs/install/getting-started-knative-app.md
  docs/serving/samples/blue-green-deployment.md
  docs/serving/samples/build-private-repo-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1193 Update docs contributor guidelines
  contributing/DOCS-CONTRIBUTING.md
  doc-releases.md
Labels: approved, cla: yes, lgtm, size/L

#1208 Cherrrypick: fix some spelling mistakes of docs (#1188)
  docs/build/auth.md
  docs/eventing/debugging/README.md
  docs/eventing/samples/cronjob-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1209 Cherrypick: fix some spelling mistakes in docs (#1200)
  docs/install/Knative-with-Minishift.md
  docs/install/getting-started-knative-app.md
  docs/serving/samples/blue-green-deployment.md
  docs/serving/samples/build-private-repo-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1212 add missing mention of cla
  contributing/DOCS-CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/S

#1207 update sample.yaml to fix the build-template name to buildpacks-cnb
  docs/serving/samples/buildpack-app-dotnet/sample.yaml
  docs/serving/samples/buildpack-function-nodejs/sample.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1221 Fix a typo in Eventing doc
  docs/eventing/README.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1218 links and landing pages for all samples
  community/samples/README.md
  community/samples/_index.md
  docs/build/README.md
  docs/build/samples.md
  docs/concepts/_index.md
  docs/eventing/debugging/_index.md
  docs/eventing/samples/_index.md
  docs/samples.md
  docs/serving/samples/README.md
  docs/serving/samples/_index.md
Labels: approved, cla: yes, lgtm, size/L

#1219 add _index.md files for community samples
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-clojure/_index.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-dart/_index.md
  community/samples/serving/helloworld-elixir/README.md
  community/samples/serving/helloworld-elixir/_index.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-haskell/_index.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-rust/_index.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-swift/_index.md
  community/samples/serving/helloworld-vertx/README.md
  community/samples/serving/helloworld-vertx/_index.md
Labels: approved, cla: yes, lgtm, size/M

#1185 rename hellworld-java to helloworld-java-spring
  docs/serving/samples/hello-world/helloworld-java-spring/.dockerignore
  docs/serving/samples/hello-world/helloworld-java-spring/.gitignore
  docs/serving/samples/hello-world/helloworld-java-spring/.mvn/wrapper/maven-wrapper.jar
  docs/serving/samples/hello-world/helloworld-java-spring/.mvn/wrapper/maven-wrapper.properties
  docs/serving/samples/hello-world/helloworld-java-spring/Dockerfile
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/_index.md
  docs/serving/samples/hello-world/helloworld-java-spring/helloworld.zip
  docs/serving/samples/hello-world/helloworld-java-spring/mvnw
  docs/serving/samples/hello-world/helloworld-java-spring/mvnw.cmd
  docs/serving/samples/hello-world/helloworld-java-spring/pom.xml
  docs/serving/samples/hello-world/helloworld-java-spring/service.yaml
  docs/serving/samples/hello-world/helloworld-java-spring/src/main/java/com/example/helloworld/HelloworldApplication.java
  docs/serving/samples/hello-world/helloworld-java-spring/src/main/resources/application.properties
  docs/serving/samples/hello-world/helloworld-java-spring/src/test/java/com/example/helloworld/HelloworldApplicationTests.java
  test/sampleapp/config.yaml
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/S

#1214 README: fix broken links to "help wanted" label
  contributing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1228 cherry-pick #1218 - add samples landing pages
  community/samples/README.md
  community/samples/_index.md
  docs/build/README.md
  docs/build/samples.md
  docs/concepts/_index.md
  docs/eventing/debugging/_index.md
  docs/eventing/samples/_index.md
  docs/samples.md
  docs/serving/samples/README.md
  docs/serving/samples/_index.md
Labels: approved, cla: yes, lgtm, size/L

#1229 fix broken link
  docs/build/samples.md
Labels: approved, cla: yes, lgtm, size/XS

#1225 Fix an error in README.md
  docs/eventing/samples/iot-core/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1181 Take a crack at updates for v1beta1 API shape.
  docs/eventing/samples/cronjob-source/README.md
  docs/eventing/samples/cronjob-source/service.yaml
  docs/eventing/samples/gcp-pubsub-source/trigger.yaml
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/github-source/service.yaml
  docs/eventing/samples/iot-core/trigger.yaml
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-Minishift.md
  docs/install/getting-started-knative-app.md
  docs/serving/samples/README.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/autoscale-go/service.yaml
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/gitwebhook-go/service.yaml
  docs/serving/samples/grpc-ping-go/sample.yaml
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-csharp/service.yaml
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-go/service.yaml
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/service.yaml
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/service.yaml
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/service.yaml
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-php/service.yaml
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-python/service.yaml
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-ruby/service.yaml
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-scala/helloworld-scala.yaml
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/hello-world/helloworld-shell/service.yaml
  docs/serving/samples/hello-world/rest-api-go/sample-template.yaml
  docs/serving/samples/knative-routing-go/sample.yaml
  docs/serving/samples/rest-api-go/sample-template.yaml
  docs/serving/samples/rest-api-go/sample.yaml
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/secrets-go/service.yaml
  docs/serving/samples/source-to-url-go/README.md
  docs/serving/samples/source-to-url-go/_index.md
  docs/serving/samples/source-to-url-go/docker-secret.yaml
  docs/serving/samples/source-to-url-go/service.yaml
  docs/serving/samples/traffic-splitting/README.md
  docs/serving/samples/traffic-splitting/release_sample.yaml
  docs/serving/samples/traffic-splitting/split_sample.yaml
  docs/serving/samples/traffic-splitting/updated_sample.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1231 Cherry-pick: Fix a typo in Eventing doc (#1221)
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1232 Cherry-pick batch
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-elixir/Dockerfile
  community/samples/serving/helloworld-elixir/README.md
  contributing/WORKING-GROUPS.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minishift.md
  docs/serving/samples/hello-world/helloworld-go/Dockerfile
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/knative-routing-go/routing.yaml
Labels: approved, cla: yes, lgtm, size/L

#1233 Add Michael Behrendt from IBM to the Knative Steering Committee
  contributing/STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#1230 Update Build WG calendar link 📆
  contributing/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#1223 Fix some spelling mistakes of doc
  community/samples/serving/helloworld-vertx/README.md
  contributing/DOCS-CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#1238 Fix the link to mbehrendt's profile
  contributing/STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#1224 serving/samples/helloworld-php: render newline
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-php/index.php
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1236 update test-infra: skip e2e tests for non-code changes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#1245 Format markdown
  community/samples/README.md
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-elixir/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-vertx/README.md
  contributing/DOCS-CONTRIBUTING.md
  contributing/STEERING-COMMITTEE.md
  contributing/WORKING-GROUPS.md
  docs/build/README.md
  docs/build/samples.md
  docs/eventing/README.md
  docs/eventing/samples/_index.md
  docs/eventing/samples/cronjob-source/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-Minishift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/getting-started-knative-app.md
  docs/samples.md
  docs/serving/samples/README.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/traffic-splitting/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1243 Remove references to Istio yamls attached to releases.
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-Minishift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/L

#1242 Fix a couple broken links to removed samples.
  docs/README.md
Labels: approved, cherrypick-0.5, cla: yes, lgtm, size/XS

#1154 Update to include support for deploying Jaeger and accessing its UI
  docs/install/Knative-custom-install.md
  docs/serving/accessing-traces.md
  docs/serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, kind/enhancement, kind/observability, lgtm, size/M
