Repository knative/docs, pull requests merged in 2019-08, with the labels that each got.

#1634 Format markdown
  docs/eventing/channels/default-channels.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1636 revert to README.md to prevent index/_index conflict
  community/samples/_index.md
  docs/_index.md
  docs/build/_index.md
  docs/eventing/_index.md
  docs/eventing/samples/writing-a-source/_index.md
  docs/install/_index.md
  docs/serving/_index.md
  docs/serving/samples/_index.md
Labels: approved, cla: yes, lgtm, size/S

#1637 revert to README.md to prevent index/_index conflict
  community/samples/_index.md
  docs/_index.md
  docs/build/_index.md
  docs/eventing/_index.md
  docs/eventing/samples/writing-a-source/_index.md
  docs/install/_index.md
  docs/serving/_index.md
  docs/serving/samples/_index.md
Labels: approved, cla: yes, lgtm, size/S

#1638 Format markdown
  community/samples/_index.md
  docs/eventing/channels/README.md
  docs/eventing/sources/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1628 Correct some error in "knative/docs/docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md"
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1640 feat: Use Node 12 (Latest Node LTS)
  docs/serving/samples/hello-world/helloworld-nodejs/Dockerfile
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1631 choice documentation and samples
  docs/eventing/choice.md
  docs/eventing/samples/choice/README.md
  docs/eventing/samples/choice/_index.md
  docs/eventing/samples/choice/multiple-cases/README.md
  docs/eventing/samples/choice/multiple-cases/_index.md
  docs/eventing/samples/choice/multiple-cases/choice.yaml
  docs/eventing/samples/choice/multiple-cases/cron-source.yaml
  docs/eventing/samples/choice/multiple-cases/event-display.yaml
  docs/eventing/samples/choice/multiple-cases/filters.yaml
  docs/eventing/samples/choice/multiple-cases/transformers.yaml
  docs/eventing/samples/choice/mutual-exclusivity/README.md
  docs/eventing/samples/choice/mutual-exclusivity/_index.md
  docs/eventing/samples/choice/mutual-exclusivity/choice.yaml
  docs/eventing/samples/choice/mutual-exclusivity/cron-source.yaml
  docs/eventing/samples/choice/mutual-exclusivity/event-display.yaml
  docs/eventing/samples/choice/mutual-exclusivity/switcher.yaml
  docs/eventing/samples/choice/mutual-exclusivity/transformers.yaml
Labels: approved, cla: yes, lgtm, size/XL

#1641 Sam fixes some links
  docs/build/samples.md
  docs/install/Knative-custom-install.md
  docs/install/installing-istio.md
  docs/serving/README.md
  docs/serving/debugging-performance-issues.md
  docs/serving/fluentd-requirements.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/using-a-tls-cert.md
Labels: approved, cla: yes, lgtm, size/M

#1642 Add Knative API Specification
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, lgtm, size/XXL

#1647 Format markdown
  docs/eventing/choice.md
  docs/eventing/samples/choice/README.md
  docs/eventing/samples/choice/multiple-cases/README.md
  docs/eventing/samples/choice/mutual-exclusivity/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/serving/fluentd-requirements.md
  docs/serving/spec/knative-api-specification-1.0.md
  docs/serving/using-a-tls-cert.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1652 fix default-channels rendering and prevent nested shortcodes
  docs/eventing/channels/README.md
  docs/eventing/channels/_index.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/channels/generator/ReadmeTemplate.gomd
  docs/eventing/channels/generator/main.go
Labels: approved, cla: yes, lgtm, size/L

#1658 Format markdown
  docs/eventing/channels/README.md
  docs/eventing/channels/channels-crds.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1653 Attributes Filter documentation in Trigger
  docs/eventing/broker-trigger.md
Labels: approved, cla: yes, lgtm, size/M

#1659 Create smoke test pages (for testing site elements)
  docs/smoketest.md
  smoketest.md
Labels: approved, cla: yes, lgtm, size/L

#1660 Fix the order that Knative is installed in.
  docs/install/Knative-with-Ambassador.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#1650 Choice: minor clarification and fix some typos
  docs/eventing/choice.md
  docs/eventing/samples/choice/multiple-cases/README.md
  docs/eventing/samples/choice/mutual-exclusivity/README.md
  docs/eventing/samples/choice/mutual-exclusivity/_index.md
Labels: approved, cla: yes, lgtm, size/S

#1657 Delete knative build in the doc for 0.8 version
  docs/install/Knative-with-ICP.md
Labels: approved, cla: yes, lgtm, size/S

#1670 Format markdown
  docs/eventing/broker-trigger.md
  docs/eventing/choice.md
  docs/install/Knative-with-Ambassador.md
  docs/smoketest.md
  smoketest.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1656 remove knative build from everywhere - v0.8 docs
  community/samples/README.md
  docs/README.md
  docs/build/README.md
  docs/build/_index.md
  docs/build/auth.md
  docs/build/build-templates.md
  docs/build/builder-contract.md
  docs/build/builds.md
  docs/build/creating-builds.md
  docs/build/installing-build-component.md
  docs/build/personas.md
  docs/build/samples.md
  docs/concepts/resources.md
  docs/eventing/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-OpenShift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/README.md
  docs/reference/README.md
  docs/reference/build-api.md
  docs/reference/build.md
  docs/samples.md
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-metrics.md
  docs/serving/accessing-traces.md
  docs/serving/debugging-application-issues.md
  docs/serving/debugging-performance-issues.md
  docs/serving/getting-started-knative-app.md
  docs/serving/gke-assigning-static-ip-address.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/outbound-network-access.md
  docs/serving/setting-up-a-logging-plugin.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-a-tls-cert.md
  hack/gen-api-reference-docs.sh
Labels: approved, cla: yes, lgtm, size/XXL

#1664 Hello World Sample for R
  community/samples/serving/helloworld-r/.dockerignore
  community/samples/serving/helloworld-r/Dockerfile
  community/samples/serving/helloworld-r/HelloWorld.R
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-r/app.py
  community/samples/serving/helloworld-r/service.yaml
Labels: approved, cla: yes, lgtm, size/L

#1666 fix broken links
  docs/eventing/README.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/debugging/README.md
  docs/eventing/event-registry.md
  docs/install/Knative-with-Gardener.md
  docs/install/check-install-version.md
  docs/serving/accessing-metrics.md
  docs/serving/debugging-performance-issues.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/knative-routing-go/README.md
Labels: approved, cla: yes, lgtm, size/M

#1665 v0.8 - Convert all install cmds to dynamically use version (at site build time)
  docs/eventing/debugging/README.md
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/iot-core/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/L

#1673 Fix typo: uou -> you
  docs/serving/samples/knative-routing-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1667 v0.8 - convert git clone cmds to use dynamic variables
  community/samples/serving/helloworld-java-quarkus/README.md
  docs/eventing/samples/container-source/README.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/secrets-go/README.md
Labels: approved, cla: yes, lgtm, size/M

#1662 v0.8 API ref docs and updated build scripts
  docs/reference/eventing/eventing-contrib-resources.md
  docs/reference/eventing/eventing.md
  hack/gen-api-reference-docs.sh
  hack/reference-docs-gen-config.json
Labels: approved, cla: yes, lgtm, size/XXL

#1677 remove mention of Knative Build as an option
  docs/serving/samples/rest-api-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1679 V0.8 Serving API temporary redirect to Knative/Serving repo
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#1680 remove code sample that used deprecated build
  docs/serving/README.md
  docs/serving/deploying-with-private-registry.md
Labels: approved, cla: yes, lgtm, size/L

#1681 fix https://knative.dev/development/eventing/
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1668 Change initail to initial.
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1683 Fix line continuation
  docs/install/Knative-with-GKE.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1692 remove cert-manager from serving install
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/L

#1694 remove broken links (0.8)
  docs/install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, size/S

#1671 Add port number to route example
  docs/serving/samples/knative-routing-go/routing.yaml
Labels: approved, cla: yes, kind/sample, kind/serving, lgtm, ok-to-test, size/XS

#1698 Spelling fix
  docs/serving/knative-kubernetes-services.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1688 Updating samples.md
  docs/build/samples.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1701 Replace eventing.yaml with release.yaml in the install instructions
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/S

#1702 Cherry pick of #1701 into release-0.8
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/S

#1646 Enable SSL in client of grpc-ping-go sample.
  docs/serving/samples/grpc-ping-go/client/client.go
Labels: approved, cla: yes, kind/sample, lgtm, ok-to-test, size/XS, triage/needs-sample-review

#1703 Delete obsolete default channels doc
  docs/eventing/default-channels.md
Labels: approved, cla: yes, lgtm, size/L

#1629 Remove ClusterChannelProvisioner from docs due to deprecation
  docs/eventing/README.md
  docs/eventing/broker-trigger.md
  docs/eventing/channels/README.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/channels/generator/ReadmeTemplate.gomd
  docs/eventing/debugging/README.md
  docs/eventing/debugging/example.yaml
  docs/eventing/samples/apache-camel-source/README.md
  docs/eventing/samples/apache-camel-source/display_resources.yaml
  docs/eventing/samples/apache-camel-source/source_camel_k.yaml
  docs/eventing/samples/apache-camel-source/source_telegram.yaml
  docs/eventing/samples/apache-camel-source/source_timer.yaml
  docs/install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1714 Fix 404 link
  docs/eventing/README.md
Labels: approved, cherrypick-0.8, cla: yes, lgtm, size/XS

#1715 fix redirect and revise hardcoded urls
  docs/README.md
  docs/build/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-OpenShift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/README.md
  docs/install/installing-istio.md
  docs/serving/getting-started-knative-app.md
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cherrypick-0.8, cla: yes, lgtm, size/M

#1717 Fix 404 in v0.8
  docs/README.md
  docs/build/README.md
  docs/eventing/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-OpenShift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/README.md
  docs/install/installing-istio.md
  docs/serving/getting-started-knative-app.md
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cla: yes, lgtm, size/M

#1719 fix broken images and links in blog
  blog/articles/ko-fast-kubernetes-microservice-development-in-go.html
  blog/releases/announcing-knative-v0-5-release.html
Labels: approved, cla: yes, lgtm, size/S

#1704 Update configmap name to config-istio
  docs/serving/setting-up-custom-ingress-gateway.md
Labels: approved, cherrypick-0.7, cla: yes, lgtm, size/XS

#1691 update gloo install guide for knative serving 0.8.0
  docs/install/Knative-with-Gloo.md
  docs/install/README.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L, triage/needs-sample-review

#1718 move observability into separate section
  docs/install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, size/S

#1723 Fix doc formatting
  docs/serving/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1676 [docs] Update R sample to use Go
  community/samples/serving/helloworld-r/.dockerignore
  community/samples/serving/helloworld-r/Dockerfile
  community/samples/serving/helloworld-r/HelloWorld.R
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-r/app.py
  community/samples/serving/helloworld-r/invoke.go
  community/samples/serving/helloworld-r/service.yaml
Labels: approved, cla: yes, kind/sample, lgtm, size/L
