Repository knative/docs, pull requests merged in 2019-07, with the labels that each got.

#1567 Format markdown
  docs/reference/README.md
  docs/serving/knative-kubernetes-services.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1564 Use current Istio version in Minikube install guide
  docs/install/Knative-with-Minikube.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1561 reference: fix api grouping in reference docs
  hack/gen-api-reference-docs.sh
Labels: approved, cla: yes, lgtm, size/XS

#1570 Fixing Broker manual event emit curl example
  docs/eventing/broker-trigger.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/S

#1568 Update logs metrics
  docs/serving/accessing-logs.md
  docs/serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, kind/observability, lgtm, size/L

#1573 Format markdown
  docs/serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1577 Update Knative on OpenShift on Knative.dev (Release 0.7)
  docs/install/Knative-with-OpenShift.md
  docs/install/images/knative_serving_create_new.png
  docs/install/images/knative_serving_installed_operator.png
  docs/install/images/knative_serving_installed_sub.png
  docs/install/images/knative_serving_namespaces_default.png
  docs/install/images/knative_serving_operator_screen.png
  docs/install/images/knative_serving_tile_highlighted.png
  docs/install/images/knative_serving_uninstall_operator.png
  docs/install/images/knative_serving_uninstall_tile.png
Labels: approved, cla: yes, lgtm, size/L

#1582 Removes links to non-existant files. Fixes #1563.
  docs/serving/samples/README.md
Labels: approved, cherrypick-0.7, lgtm, size/XS

#1583 Removes links to non-existant files. Fixes #1563. (#1582)
  docs/serving/samples/README.md
Labels: approved, lgtm, size/XS

#1584 Removes references to a invalid sample file. Fixes #1457.
  docs/build/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1579 Remove Istio requirement for Eventing
  docs/install/README.md
Labels: approved, cherrypick-0.7, cla: yes, lgtm, size/XS

#1571 07 api from new version of script
  docs/reference/build.md
  docs/reference/eventing/eventing-contrib-resources.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#1572 07 api from new version of script
  docs/reference/build.md
  docs/reference/eventing/eventing-contrib-resources.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#1590 Format markdown
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1588 Remove "Documentation" main menu config
  docs/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#1589 Remove all other main menu configuration out of the files
  blog/_index.md
  community/_index.md
  contributing/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#1586 Update Knative on OpenShift with images on Knative.dev
  docs/install/Knative-with-OpenShift.md
Labels: approved, cla: yes, lgtm, size/S

#1587 Updating image path for OpenShift install docs
  docs/install/Knative-with-OpenShift.md
Labels: approved, cla: yes, lgtm, size/S

#1591 Additional space is required in the yaml example
  docs/serving/configuring-the-autoscaler.md
Labels: approved, cherrypick-0.7, cla: yes, lgtm, ok-to-test, size/S

#1598 Format markdown
  docs/install/Knative-with-OpenShift.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1594 Add Documentation for Install Knative with Ambassador
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Minikube.md
  docs/install/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1600 Format markdown
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Minikube.md
  docs/install/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1603 Remove Erik and Nikhil from Productivity Reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1604 Add Documentation for Install Knative with Ambassador (#1594)
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Minikube.md
  docs/install/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1606 sequence with broker works, update docs
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cherrypick-0.7, cla: yes, lgtm, size/M

#1605 fix incorrect link format
  docs/eventing/sequence.md
Labels: approved, cla: yes, lgtm, size/XS

#1607 Update a website in README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
Labels: approved, cherrypick-master, cla: yes, lgtm, needs-ok-to-test, size/XS

#1611 fix paths
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1613 fix typo
  docs/eventing/samples/github-source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1610 Change version for istio and knative serving in docker for mac
  docs/install/Knative-with-Docker-for-Mac.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1609 gRPC Go example fix
  docs/serving/samples/grpc-ping-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1599 line too long
  docs/install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1615 Update Broken Kafka Sample Link
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1569 Document usage of Camel K in sources
  docs/eventing/samples/apache-camel-source/README.md
Labels: approved, cla: yes, kind/eventing, lgtm, size/L

#1580 Correct minor grammatical error
  docs/eventing/samples/apache-camel-source/README.md
Labels: approved, cla: yes, lgtm, size/S

#1585 Some formatting changes to address #1484.
  docs/install/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, size/S

#1608 Create source_camel_k.yaml in samples directory
  docs/eventing/samples/apache-camel-source/source_camel_k.yaml
Labels: approved, cherrypick-0.7, cla: yes, lgtm, size/S

#911 Building and deploying the sample
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1617 Rewrite the cluster-local route topic
  docs/serving/cluster-local-route.md
Labels: approved, cla: yes, lgtm, size/M

#1612 fix broken links.
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cherrypick-0.7, cla: yes, lgtm, ok-to-test, size/M

#1620 removing annotation does not remove broker
  docs/eventing/broker-trigger.md
Labels: approved, cla: yes, lgtm, size/S

#1621 Format markdown
  docs/eventing/broker-trigger.md
  docs/eventing/samples/apache-camel-source/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/sources/README.md
  docs/install/getting-started-knative-app.md
  docs/serving/cluster-local-route.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1625 serving/samples: update helloworld-php to php 7.3
  docs/serving/samples/hello-world/helloworld-php/Dockerfile
  docs/serving/samples/hello-world/helloworld-php/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1619 Default channel for CRDs documentation
  docs/eventing/channels/default-channels.md
Labels: approved, cla: yes, lgtm, size/L
