Repository knative/docs, pull requests merged in 2019-02, with the labels that each got.

#601 Argument must be "--sink" exactly for the sink to be filled in for ContainerSource
  eventing/README.md
Labels: approved, kind/bug, lgtm, needs eng input, size/XS

#851 Channel docs
  eventing/README.md
  eventing/channels/README.md
  eventing/channels/channels.yaml
  eventing/channels/default-channels.md
  eventing/channels/generator/ReadmeTemplate.gomd
  eventing/channels/generator/main.go
Labels: approved, cla: yes, lgtm, size/L

#853 site: add PR#851 - channels
  docs/eventing/channels/README.md
  docs/eventing/channels/_index.md
  docs/eventing/channels/default-channels.md
  docs/eventing/channels/generator/ReadmeTemplate.gomd
  docs/eventing/debugging/_index.md
  docs/eventing/samples/_index.md
Labels: approved, cla: yes, lgtm, size/S

#857 site: fix links in community
  contributing/CODE-OF-CONDUCT.md
  contributing/CONTRIBUTING.md
  contributing/DOCS-CONTRIBUTING.md
  contributing/README.md
  contributing/REVIEWING.md
  contributing/ROLES.md
  contributing/SLACK-GUIDELINES.md
  contributing/STEERING-COMMITTEE.md
  contributing/TECH-OVERSIGHT-COMMITTEE.md
  contributing/VALUES.md
  contributing/WORKING-GROUP-PROCESSES.md
  contributing/WORKING-GROUPS.md
  contributing/_index.md
Labels: approved, cla: yes, lgtm, size/L

#858 site: fix build links
  docs/build/README.md
  docs/build/build-templates.md
  docs/build/builder-contract.md
  docs/build/builds.md
  docs/build/creating-builds.md
  docs/build/installing-build-component.md
Labels: approved, cla: yes, lgtm, size/M

#859 site: fix eventing links
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/writing-a-source/01-bootstrap.md
  docs/eventing/samples/writing-a-source/02-define-source.md
  docs/eventing/samples/writing-a-source/03-reconcile-sources.md
  docs/eventing/samples/writing-a-source/README.md
Labels: approved, cla: yes, lgtm, size/S

#860 site: fix install links
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-OpenShift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/README.md
Labels: approved, cla: yes, lgtm, size/M

#861 site: fix serving links
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-traces.md
  docs/serving/cluster-local-route.md
  docs/serving/debugging-application-issues.md
  docs/serving/debugging-performance-issues.md
  docs/serving/fluentd/README.md
  docs/serving/gke-assigning-static-ip-address.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/samples/README.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/blue-green-deployment.md
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/knative-routing-go/README.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/source-to-url-go/README.md
  docs/serving/samples/telemetry-go/README.md
  docs/serving/setting-up-a-logging-plugin.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-an-ssl-cert.md
  docs/serving/using-cert-manager-on-gcp.md
  docs/serving/using-external-dns-on-gcp.md
Labels: approved, cla: yes, lgtm, size/L

#863 site: remove hardcoded github link
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-shell/README.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-vertx/README.md
  docs/README.md
  docs/build/README.md
  docs/eventing/README.md
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/github-source/README.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
Labels: approved, cla: yes, lgtm, size/M

#864 Update README.md
  docs/README.md
Labels: approved, cla: yes, lgtm, size/S

#865 site: add missing hello-world directory
  docs/serving/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#867 Link fixes for Build
  docs/build/builder-contract.md
  docs/build/builds.md
  docs/build/creating-builds.md
  docs/build/installing-build-component.md
Labels: approved, cla: yes, lgtm, size/M

#868 site: convert to Hugo rel link
  community/samples/README.md
  contributing/CONTRIBUTING.md
  contributing/DOCS-CONTRIBUTING.md
  contributing/README.md
  contributing/SLACK-GUIDELINES.md
  docs/README.md
  docs/build/README.md
  docs/build/builder-contract.md
  docs/build/builds.md
  docs/eventing/README.md
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/github-source/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-Minishift.md
  docs/install/Knative-with-OpenShift.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/README.md
  docs/install/getting-started-knative-app.md
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-metrics.md
  docs/serving/accessing-traces.md
  docs/serving/cluster-local-route.md
  docs/serving/debugging-application-issues.md
  docs/serving/debugging-performance-issues.md
  docs/serving/gke-assigning-static-ip-address.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/samples/README.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/blue-green-deployment.md
  docs/serving/samples/build-private-repo-go/README.md
  docs/serving/samples/buildpack-app-dotnet/README.md
  docs/serving/samples/buildpack-function-nodejs/README.md
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/knative-routing-go/README.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/source-to-url-go/README.md
  docs/serving/samples/telemetry-go/README.md
  docs/serving/samples/thumbnailer-go/README.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-an-ssl-cert.md
Labels: approved, cla: yes, lgtm, size/L

#848 Adding a Serving sample for Scala which uses Akka HTTP
  serving/samples/README.md
  serving/samples/helloworld-scala/.gitignore
  serving/samples/helloworld-scala/README.md
  serving/samples/helloworld-scala/build.sbt
  serving/samples/helloworld-scala/helloworld-scala.yaml
  serving/samples/helloworld-scala/project/build.properties
  serving/samples/helloworld-scala/project/plugins.sbt
  serving/samples/helloworld-scala/src/main/resources/application.conf
  serving/samples/helloworld-scala/src/main/scala/klang/HelloWorldScala.scala
Labels: approved, cla: yes, lgtm, size/L

#870 Addressing a kubectl typo in helloworld-scala README
  serving/samples/helloworld-scala/README.md
Labels: approved, cla: yes, lgtm, size/XS

#869 adding the '.' to the generated doc...
  eventing/channels/README.md
Labels: approved, cla: yes, lgtm, size/XS

#877 Fixed the dead link
  install/Knative-with-Minishift.md
Labels: approved, cla: yes, lgtm, size/XS

#878 removing mention of gitlab source being python
  eventing/samples/writing-a-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#880 Manually run prettier.io
  build/auth.md
  build/build-templates.md
  community/README.md
  community/samples/README.md
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-elixir/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-shell/README.md
  community/samples/serving/helloworld-vertx/README.md
  doc-releases.md
  eventing/README.md
  eventing/channels/README.md
  eventing/debugging/README.md
  eventing/samples/gcp-pubsub-source/README.md
  eventing/samples/writing-a-source/01-bootstrap.md
  eventing/samples/writing-a-source/02-define-source.md
  eventing/samples/writing-a-source/04-publish-to-cluster.md
  eventing/samples/writing-a-source/README.md
  eventing/sources/README.md
  install/Knative-custom-install.md
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-ICP.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-Minishift.md
  install/Knative-with-OpenShift.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
  install/README.md
  serving/cluster-local-route.md
  serving/gke-assigning-static-ip-address.md
  serving/installing-logging-metrics-traces.md
  serving/samples/README.md
  serving/samples/autoscale-go/README.md
  serving/samples/blue-green-deployment.md
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-kotlin/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-scala/README.md
  serving/samples/knative-routing-go/README.md
  serving/samples/telemetry-go/README.md
  serving/samples/traffic-splitting/README.md
Labels: approved, cla: yes, lgtm, size/XXL

#884 Format markdown
  serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#889 Update cluster-local-route.md
  serving/cluster-local-route.md
Labels: approved, cla: yes, lgtm, size/XS

#887 Use kubectl logs instead of kail to verify the message
  eventing/samples/cronjob-source/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#871 sbt 1.2.8
  serving/samples/helloworld-scala/project/build.properties
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#894 Format markdown
  eventing/samples/cronjob-source/README.md
  serving/cluster-local-route.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#893 Correct spelling of privileged
  install/Knative-with-Minishift.md
Labels: approved, cla: yes, lgtm, size/XS

#802 Update metrics and ingress gateway documentation
  serving/accessing-metrics.md
  serving/gke-assigning-static-ip-address.md
  serving/setting-up-custom-ingress-gateway.md
Labels: approved, cla: yes, lgtm, size/L

#896 Clarify the file name that needs to be updated for k8s event source.
  eventing/samples/kubernetes-event-source/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#895 Updated document for gcp pubsub.
  eventing/samples/gcp-pubsub-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#897 Correct the file path of github source.
  eventing/samples/github-source/README.md
Labels: approved, cla: yes, lgtm, size/S

#898 Correct the file path for iot example.
  eventing/samples/iot-core/README.md
Labels: approved, cla: yes, lgtm, size/XS

#901 Address comments from #802
  serving/accessing-metrics.md
  serving/setting-up-custom-ingress-gateway.md
Labels: approved, cla: yes, lgtm, size/XS

#881 Update Serving Rest API example
  serving/samples/rest-api-go/README.md
  serving/samples/rest-api-go/sample.yaml
Labels: approved, cla: yes, lgtm, size/L

#913 Format markdown
  eventing/samples/kubernetes-event-source/README.md
  serving/accessing-metrics.md
  serving/gke-assigning-static-ip-address.md
  serving/samples/rest-api-go/README.md
  serving/setting-up-custom-ingress-gateway.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#903 Fix up the GRPC sample in preparation for 0.4
  serving/samples/grpc-ping-go/Dockerfile
  serving/samples/grpc-ping-go/README.md
  serving/samples/grpc-ping-go/client/client.go
  serving/samples/grpc-ping-go/sample.yaml
Labels: approved, cla: yes, lgtm, size/M

#886 Add gloo to docs
  install/Knative-custom-install.md
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gloo.md
  install/Knative-with-Minikube.md
  install/Knative-with-OpenShift.md
  install/README.md
Labels: approved, cla: yes, lgtm, size/L

#914 Format markdown
  install/Knative-with-Gloo.md
  install/README.md
  serving/samples/grpc-ping-go/README.md
  serving/samples/secrets-go/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#917 Correct Istio install steps for minikube (#882)
  install/Knative-with-Minikube.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#900 Add commands to clean up `knative-ingressgateway` before upgrade from 0.3.x to 0.4
  install/Knative-custom-install.md
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-ICP.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-Minishift.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/M

#847 Deploy using private registry
  serving/README.md
  serving/deploying-with-private-registry.md
Labels: approved, cla: yes, lgtm, size/L

#918 Add knative lambda sources from triggermesh
  eventing/sources/README.md
  eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/L

#915 Updating install docs to v0.4
  install/Knative-custom-install.md
  install/Knative-with-AKS.md
  install/Knative-with-Docker-for-Mac.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-ICP.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-Minishift.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/L

#912 Updated autoscale go README.
  serving/samples/autoscale-go/README.md
Labels: approved, cla: yes, lgtm, size/M

#919 Tweak grammar in Custom Ingress Gateway guide
  serving/setting-up-custom-ingress-gateway.md
Labels: approved, cla: yes, lgtm, size/S

#924 using correct link in openshift install docs
  install/Knative-with-OpenShift.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#928 Update the docker push reference
  serving/samples/grpc-ping-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#910 Fix gcp-pubsub-source README typo
  eventing/samples/gcp-pubsub-source/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#930 Fix invalid manifest URL to insatll build
  build/installing-build-component.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#929 Update eventing install for v0.4.0
  eventing/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#931 knative with gardener: fix markdown syntax
  install/Knative-with-Gardener.md
Labels: approved, cla: yes, lgtm, size/XS

#807 Update Dockerfile to use gunicorn w/ multithread
  serving/samples/helloworld-python/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#663 Switching to rbac v1
  serving/samples/telemetry-go/prometheus-test.yaml
  serving/using-external-dns-on-gcp.md
Labels: approved, cla: yes, lgtm, needs-eng-input, size/S

#939 Adding frontmatter to Gloo guide
  docs/install/Knative-with-Gloo.md
Labels: approved, cla: yes, lgtm, size/XS

#935 Fix docs
  serving/samples/grpc-ping-go/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-kotlin/README.md
Labels: approved, cla: yes, lgtm, size/M

#940 fix the alignment bugs
  serving/samples/source-to-url-go/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#872 sbt-native-packager 1.3.17
  serving/samples/helloworld-scala/project/plugins.sbt
Labels: approved, cla: yes, lgtm, size/XS

#899 Missing NodePort replace to run on localhost
  install/Knative-with-Docker-for-Mac.md
Labels: approved, cla: yes, lgtm, size/XS

#944 Add in-memory-channel to enable eventing release
  install/Knative-with-GKE.md
Labels: approved, cla: yes, lgtm, size/XS

#943 adding frontmatter; cherry-picking commit into 0.3
  docs/serving/README.md
  docs/serving/deploying-with-private-registry.md
Labels: approved, cla: yes, lgtm, size/L

#936 Add Build and Eventing to "How can I help" (#193)
  community/README.md
Labels: approved, cla: yes, lgtm, size/XS

#907 Correct the command for build auth.
  build/auth.md
Labels: approved, cla: yes, lgtm, size/XS

#909 Added sample link for each event sample.
  eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#908 Added debug info for kubernetes deployment.
  eventing/debugging/README.md
Labels: approved, cla: yes, lgtm, size/S
