Repository knative/docs, pull requests merged in 2019-01, with the labels that each got.

#691 Fixed typo
  install/getting-started-knative-app.md
Labels: approved, lgtm, size/XS

#693 Update README.md
  README.md
Labels: approved, lgtm, size/S

#697 Improve Docker for Mac installation guide
  install/Knative-with-Docker-for-Mac.md
Labels: approved, lgtm, size/XS

#699 serving/samples/helloworld-php: use development php.ini
  serving/samples/helloworld-php/Dockerfile
  serving/samples/helloworld-php/README.md
Labels: approved, lgtm, size/S

#701 Event Sources List
  Gopkg.lock
  eventing/sources/README.md
  eventing/sources/generator/ReadmeTemplate.gomd
  eventing/sources/generator/main.go
  eventing/sources/sources.yaml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
Labels: approved, lgtm, size/XXL

#704 fix(README): "repository" -> "registry"
  build/README.md
Labels: approved, lgtm, size/XS

#703 fix(README): tiny cosmetic formatting fix
  build/README.md
Labels: approved, lgtm, size/XS

#711 golang format tools
  eventing/sources/generator/main.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#713 Manually run prettier.io
  README.md
  community/WORKING-GROUPS.md
  eventing/sources/README.md
  serving/samples/autoscale-go/README.md
Labels: approved, lgtm, size/L

#660 Update doc for knative deploy on IBMCloudPrivate
  install/Knative-with-ICP.md
  install/README.md
Labels: approved, kind/new-docs-needed, lgtm, needs edits, size/L

#708 docs: add AWS SQS source to README
  eventing/README.md
Labels: approved, kind/enhancement, lgtm, needs eng input, needs-ok-to-test, size/S

#714 api-reference: Add API reference docs
  hack/gen-api-reference-docs.sh
  hack/reference-docs-gen-config.json
  reference/README.md
  reference/build.md
  reference/eventing/eventing-sources.md
  reference/eventing/eventing.md
  reference/gen-api-reference-docs.sh
  reference/knative-refdocs-gen-config.json
  reference/serving.md
Labels: approved, lgtm, size/XXL

#717 Tweaks docs to create Istio CRDs first
  install/Knative-with-IKS.md
Labels: approved, lgtm, size/XS

#731 Tweaks docs to create Istio CRDs first - part 2
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-Minishift.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, size/M

#720 Add custom install and Knative codelab links
  install/README.md
Labels: approved, lgtm, size/XS

#721 Format markdown
  eventing/README.md
  install/Knative-with-ICP.md
  serving/samples/helloworld-swift/README.md
Labels: approved, lgtm, size/L

#565 Organizing install guides; adding link to Custom Install guide.
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
  install/README.md
Labels: approved, lgtm, size/XL

#736 Fix syntax of Knative install command
  install/Knative-with-GKE.md
Labels: approved, lgtm, size/XS

#741 Update installs to 3.0 releases; fixing error in some install commands
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, size/M

#743 Adding missing scc binding for istio on openshift
  install/Knative-with-OpenShift.md
Labels: approved, lgtm, size/XS

#744 Remove license header for Go sample
  serving/samples/helloworld-go/helloworld.go
Labels: approved, lgtm, size/S

#745 Remove license header for Node.js sample
  serving/samples/helloworld-nodejs/app.js
Labels: approved, lgtm, size/S

#759 use consistent env variables from install section
  serving/outbound-network-access.md
Labels: approved, lgtm, size/S

#764 Note about outbound access
  eventing/README.md
Labels: approved, lgtm, size/XS

#769 Update presubmit tests
  Gopkg.lock
  README.md
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#747 Add link to image in Dockerhub
  serving/samples/helloworld-go/Dockerfile
  serving/samples/helloworld-go/README.md
Labels: approved, lgtm, size/S

#763 Update installation instructions for logs, metrics and traces
  serving/installing-logging-metrics-traces.md
Labels: approved, lgtm, size/L

#770 GCPPubSubSource moved to contrib
  eventing/sources/README.md
  eventing/sources/sources.yaml
Labels: approved, lgtm, size/M

#773 Disable markdown link checks
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#700 Update docs to use correct ingress gateway service.
  install/Knative-with-Minikube.md
  install/Knative-with-Minishift.md
  install/Knative-with-OpenShift.md
  install/getting-started-knative-app.md
  serving/gke-assigning-static-ip-address.md
  serving/samples/autoscale-go/README.md
  serving/samples/blue-green-deployment.md
  serving/samples/build-private-repo-go/README.md
  serving/samples/buildpack-app-dotnet/README.md
  serving/samples/buildpack-function-nodejs/README.md
  serving/samples/grpc-ping-go/README.md
  serving/samples/helloworld-clojure/README.md
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-dart/README.md
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/README.md
  serving/samples/helloworld-vertx/README.md
  serving/samples/knative-routing-go/README.md
  serving/samples/rest-api-go/README.md
  serving/samples/source-to-url-go/README.md
  serving/samples/telemetry-go/README.md
  serving/samples/thumbnailer-go/README.md
  serving/samples/traffic-splitting/README.md
  serving/using-a-custom-domain.md
  serving/using-external-dns-on-gcp.md
Labels: approved, lgtm, size/XL

#767 Bump required kube version to 1.11 to align with v0.3.0 release
  install/Knative-custom-install.md
  install/Knative-with-AKS.md
  install/Knative-with-Docker-for-Mac.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-OpenShift.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
Labels: approved, lgtm, size/M

#715 Add a tutorial for writing an event source
  eventing/README.md
  eventing/samples/writing-a-source/01-bootstrap.md
  eventing/samples/writing-a-source/02-define-source.md
  eventing/samples/writing-a-source/03-reconcile-sources.md
  eventing/samples/writing-a-source/04-publish-to-cluster.md
  eventing/samples/writing-a-source/README.md
  eventing/sources/README.md
  eventing/sources/sources.yaml
Labels: approved, lgtm, size/XL

#771 Update custom install for v.0.3
  install/Knative-custom-install.md
Labels: approved, lgtm, size/L

#694 Instruction to make a Route/KService visible only inside cluster.
  serving/README.md
  serving/cluster-local-route.md
Labels: approved, lgtm, size/S

#774 Adding IBM Cloud Private install to index.
  install/README.md
Labels: approved, lgtm, size/XS

#776 Update SSL and IP address docs to work with istio-ingressgateway.
  serving/gke-assigning-static-ip-address.md
  serving/samples/knative-routing-go/README.md
  serving/samples/knative-routing-go/routing.yaml
  serving/using-an-ssl-cert.md
  serving/using-cert-manager-on-gcp.md
Labels: approved, lgtm, size/M

#470 Fixes #385
  build/auth.md
Labels: approved, kind/enhancement, lgtm, size/S

#397 Update kube-version to 1.10.7
  install/Knative-with-IKS.md
Labels: approved, kind/enhancement, lgtm, needs eng input, size/XS

#777 update version to v0.3.0
  eventing/README.md
Labels: approved, lgtm, size/S

#784 Improvements to spacing and install wording
  install/README.md
Labels: approved, lgtm, size/S

#782 Update builder-contract.md
  build/builder-contract.md
Labels: approved, lgtm, size/XS

#778 Update subscriber.yaml from gcp-pubsub sample to v0.3
  eventing/samples/gcp-pubsub-source/subscriber.yaml
Labels: approved, lgtm, size/XS

#723 Document default channels for users and operators
  eventing/README.md
  eventing/default-channels.md
Labels: approved, cla: yes, lgtm, size/L

#787 Typo fix
  install/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, size/XS

#749 Refactor Node.js sample to use arrow functions
  serving/samples/helloworld-nodejs/app.js
Labels: approved, lgtm, size/XS

#786 Updates monitoring in installs; rewrite of ICP install
  install/Knative-with-AKS.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-ICP.md
  install/Knative-with-IKS.md
  install/Knative-with-PKS.md
  serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, lgtm, size/L

#785 Debugging tutorial for Knative Eventing
  eventing/debugging/ExampleModel.png
  eventing/debugging/README.md
  eventing/debugging/example.yaml
Labels: approved, lgtm, size/XL

#779 Tweaks to custom install for v0.3
  install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, size/M

#753 Shell Hello World
  serving/samples/helloworld-shell/Dockerfile
  serving/samples/helloworld-shell/README.md
  serving/samples/helloworld-shell/invoke.go
  serving/samples/helloworld-shell/script.sh
  serving/samples/helloworld-shell/service.yaml
Labels: approved, cla: yes, lgtm, size/L

#790 Add missing image tag for v0.3
  eventing/samples/gcp-pubsub-source/subscriber.yaml
Labels: approved, cla: yes, lgtm, size/XS

#792 add default port for dart app
  serving/samples/helloworld-dart/bin/server.dart
Labels: approved, cla: yes, lgtm, size/XS

#688 Update instructions for setting up a logging plugin
  serving/setting-up-a-logging-plugin.md
Labels: approved, lgtm, size/S

#801 Use template literals in node sample
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-nodejs/app.js
Labels: approved, cla: yes, lgtm, size/XS

#775 v0.3 updates for Gardener, ICP, Minikube, Minishift installs
  install/Knative-with-Gardener.md
  install/Knative-with-ICP.md
  install/Knative-with-Minikube.md
  install/Knative-with-Minishift.md
Labels: approved, cla: yes, lgtm, size/M

#644 serving/samples: remove EXPOSE directive from helloworld
  serving/samples/helloworld-clojure/Dockerfile
  serving/samples/helloworld-clojure/README.md
  serving/samples/helloworld-csharp/Dockerfile
  serving/samples/helloworld-csharp/README.md
  serving/samples/helloworld-dart/Dockerfile
  serving/samples/helloworld-dart/README.md
  serving/samples/helloworld-elixir/Dockerfile
  serving/samples/helloworld-elixir/README.md
  serving/samples/helloworld-go/Dockerfile
  serving/samples/helloworld-go/README.md
  serving/samples/helloworld-haskell/Dockerfile
  serving/samples/helloworld-haskell/README.md
  serving/samples/helloworld-java/Dockerfile
  serving/samples/helloworld-java/README.md
  serving/samples/helloworld-kotlin/Dockerfile
  serving/samples/helloworld-kotlin/README.md
  serving/samples/helloworld-nodejs/Dockerfile
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-php/Dockerfile
  serving/samples/helloworld-php/README.md
  serving/samples/helloworld-python/Dockerfile
  serving/samples/helloworld-python/README.md
  serving/samples/helloworld-ruby/Dockerfile
  serving/samples/helloworld-ruby/README.md
  serving/samples/helloworld-rust/Dockerfile
  serving/samples/helloworld-rust/README.md
  serving/samples/helloworld-vertx/Dockerfile
  serving/samples/helloworld-vertx/README.md
Labels: approved, cla: yes, kind/enhancement, lgtm, needs eng input, size/XL

#647 Added cronjob sample
  eventing/README.md
  eventing/samples/cronjob-source/README.md
  eventing/samples/cronjob-source/cronjob-source.yaml
  eventing/samples/cronjob-source/service.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, needs eng input, size/L

#815 Fix cronjob sample bug
  eventing/samples/cronjob-source/README.md
  eventing/samples/cronjob-source/service.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#811 Correct spec documentation for GitHubSource
  eventing/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#820 Cut v0.2 branch + add v0.2.x tag
  doc-releases.md
Labels: approved, cla: yes, lgtm, size/S

#821 add v0.1 release branch
  doc-releases.md
Labels: approved, cla: yes, lgtm, size/S

#823 eventing/samples/cronjob-source: fix broken cmd
  eventing/samples/cronjob-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#824 eventing/samples/gcp-pubsub-source: fix filename
  eventing/samples/gcp-pubsub-source/README.md
  eventing/samples/gcp-pubsub-source/knative-source.json
Labels: approved, cla: yes, lgtm, size/S

#826 samples/gcp-pubsub: remove checked in secret
  eventing/samples/gcp-pubsub-source/knative-source.json
Labels: approved, cla: yes, lgtm, size/S

#833 Add front matter to Build files
  build/auth.md
  build/build-templates.md
  build/builder-contract.md
  build/builds.md
  build/creating-builds.md
  build/installing-build-component.md
  build/personas.md
  eventing/debugging/README.md
Labels: approved, cla: yes, lgtm, size/M

#834 Adding frontmatter to /install/
  install/Knative-custom-install.md
  install/Knative-with-AKS.md
  install/Knative-with-Docker-for-Mac.md
  install/Knative-with-GKE.md
  install/Knative-with-Gardener.md
  install/Knative-with-ICP.md
  install/Knative-with-IKS.md
  install/Knative-with-Minikube.md
  install/Knative-with-Minishift.md
  install/Knative-with-OpenShift.md
  install/Knative-with-PKS.md
  install/Knative-with-any-k8s.md
  install/check-install-version.md
  install/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, size/M

#838 Adds front matter to Serving
  serving/accessing-logs.md
  serving/accessing-metrics.md
  serving/accessing-traces.md
  serving/cluster-local-route.md
  serving/debugging-application-issues.md
  serving/debugging-performance-issues.md
  serving/gke-assigning-static-ip-address.md
  serving/installing-logging-metrics-traces.md
  serving/outbound-network-access.md
  serving/setting-up-a-logging-plugin.md
  serving/using-a-custom-domain.md
  serving/using-an-ssl-cert.md
  serving/using-cert-manager-on-gcp.md
  serving/using-external-dns-on-gcp.md
Labels: approved, cla: yes, lgtm, size/M

#839 site: Hugo files for Fluentd folder
  serving/fluentd/README.md
  serving/fluentd/_index.md
Labels: approved, cla: yes, lgtm, size/S

#840 site: add _index.md build files and front matter
  eventing/README.md
  eventing/_index.md
  eventing/debugging/README.md
  eventing/debugging/_index.md
  eventing/samples/_index.md
  eventing/samples/cronjob-source/README.md
  eventing/samples/cronjob-source/_index.md
  eventing/samples/gcp-pubsub-source/README.md
  eventing/samples/gcp-pubsub-source/_index.md
  eventing/samples/github-source/README.md
  eventing/samples/github-source/_index.md
  eventing/samples/iot-core/README.md
  eventing/samples/iot-core/_index.md
  eventing/samples/kubernetes-event-source/README.md
  eventing/samples/kubernetes-event-source/_index.md
  eventing/samples/writing-a-source/01-bootstrap.md
  eventing/samples/writing-a-source/02-define-source.md
  eventing/samples/writing-a-source/03-reconcile-sources.md
  eventing/samples/writing-a-source/04-publish-to-cluster.md
  eventing/samples/writing-a-source/README.md
  eventing/samples/writing-a-source/_index.md
  eventing/sources/README.md
  eventing/sources/_index.md
  eventing/sources/generator/ReadmeTemplate.gomd
Labels: approved, cla: yes, lgtm, size/L

#841 site: hugo build files for autogen refdocs
  reference/_index.md
  reference/build-api.md
  reference/eventing/_index.md
  reference/eventing/eventing-sources-api.md
  reference/serving-api.md
Labels: approved, cla: yes, lgtm, size/M

#843 site: add and move around overview and resources
  README.md
  _index.html
  background.png
  docs/README.md
  docs/_index.md
  docs/concepts/_index.md
  docs/concepts/resources.md
  search.md
Labels: approved, cla: yes, lgtm, size/L

#837 site: add blog
  blog/_index.md
  blog/articles/Build--deploy--manage-modern-serverless-workloads-using-Knative-on-Kubernetes.html
  blog/articles/_index.md
  blog/events/Knative-at-KubeCon-Seattle.html
  blog/events/_index.md
  blog/releases/Announcing-Knative-v0-2-Release.html
  blog/releases/Announcing-Knative-v0-3-Release.html
  blog/releases/_index.md
  community/_index.md
Labels: approved, cla: yes, lgtm, size/L

#825 Simplify Node.js package.json
  serving/samples/helloworld-nodejs/README.md
  serving/samples/helloworld-nodejs/package.json
Labels: approved, cla: yes, lgtm, size/S

#828 eventing/samples/pubsub: fix copy paste issue
  eventing/samples/gcp-pubsub-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#732 Add additional image repositories for ICP install
  install/Knative-with-ICP.md
Labels: approved, cla: yes, lgtm, size/S
