Repository knative/docs, pull requests merged in 2019-10, with the labels that each got.

#1847 Fix a minor typo
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-vertx/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1841 Document xip.io with Istio.
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/M

#1848 Drop the vestigial knative.dev/type annotations
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cla: yes, lgtm, size/XS

#1849 Fixed minor typos.
  docs/serving/installing-logging-metrics-traces.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1840 Document xip.io with Gloo.
  docs/install/Knative-with-Gloo.md
Labels: approved, cla: yes, kind/serving, lgtm, size/M

#1839 Document xip.io with ambassador.
  docs/install/Knative-with-Ambassador.md
Labels: approved, cla: yes, kind/serving, lgtm, size/M

#1846 Drop the manual gateway resolution from samples.
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-elixir/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-java-quarkus/README.md
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-rserver/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-vertx/README.md
  docs/eventing/samples/container-source/README.md
  docs/serving/getting-started-knative-app.md
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/blue-green-deployment.md
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/telemetry-go/README.md
Labels: approved, cla: yes, kind/sample, kind/serving, lgtm, size/XL

#1712 Apache kafka
  docs/eventing/samples/kafka/README.md
  docs/eventing/samples/kafka/_index.md
  docs/eventing/samples/kafka/channel/000-ksvc.yaml
  docs/eventing/samples/kafka/channel/010-serviceaccount.yaml
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kafka/channel/030-trigger.yaml
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kafka/source/event-display.yaml
  docs/eventing/samples/kafka/source/event-source.yaml
  docs/eventing/samples/kafka/source/kafka-topic.yaml
Labels: approved, cla: yes, kind/eventing, lgtm, size/XL

#1868 Fix KafkaSource URL
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1870 Cherry-picked kafka docs to 0.9
  docs/eventing/samples/kafka/README.md
  docs/eventing/samples/kafka/_index.md
  docs/eventing/samples/kafka/channel/000-ksvc.yaml
  docs/eventing/samples/kafka/channel/010-serviceaccount.yaml
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kafka/channel/030-trigger.yaml
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kafka/source/event-display.yaml
  docs/eventing/samples/kafka/source/event-source.yaml
  docs/eventing/samples/kafka/source/kafka-topic.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1869 Correct indent formatting and use demo correct strimzi topic to send …
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1871 Remove comment about limitation that doesn't exist anymore
  docs/install/installing-istio.md
Labels: approved, cherrypick-0.9, cla: yes, lgtm, size/S

#1863 Fix format
  docs/serving/samples/knative-routing-go/README.md
Labels: approved, cla: yes, lgtm, size/S

#1860 Use istio-ingressgateway in docs
  docs/install/Knative-with-Gardener.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1873 Update a few invalid links and a couple tips for prerequisite
  docs/eventing/getting-started.md
  docs/eventing/sources/README.md
Labels: approved, cla: yes, lgtm, size/M

#1878 Add docs title for Kafka subsections
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cla: yes, lgtm, size/S

#1879 Capitalize Channel for consistency
  docs/eventing/samples/kafka/channel/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1864 Correct eventing getting started to look for imc-controller (not old name)
  docs/eventing/getting-started.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1889 fix incorrect link in-memory-channel-crd.yaml => in-memory-channel.yaml
  docs/install/Knative-custom-install.md
Labels: approved, cla: yes, lgtm, size/XS

#1890 Fixing specversions, using url
  docs/eventing/README.md
  docs/eventing/getting-started.md
  docs/eventing/parallel.md
  docs/eventing/sequence.md
Labels: approved, cla: yes, lgtm, size/M

#1836 fix typo (offical -> official)
  docs/serving/samples/hello-world/helloworld-go/Dockerfile
  docs/serving/samples/hello-world/helloworld-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1888 remove references to in-memory-channel-*
  docs/eventing/getting-started.md
Labels: approved, cherrypick-0.9, cla: yes, lgtm, size/XS

#1816 Changed C# sample to use .NET Core 3.0 and more lean and secure alpine as base image
  docs/serving/samples/hello-world/helloworld-csharp/Dockerfile
  docs/serving/samples/hello-world/helloworld-csharp/Program.cs
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-csharp/Startup.cs
  docs/serving/samples/hello-world/helloworld-csharp/helloworld-csharp.csproj
Labels: approved, cla: yes, kind/sample, kind/serving, lgtm, ok-to-test, size/M, triage/needs-eng-input, triage/needs-sample-review

#1899 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1894 Add a step to install cluster local gateway when setting up cluster
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/M

#1909 Eallred google patch 1
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#1907 Update Knative-with-GKE.md
  docs/install/Knative-with-GKE.md
Labels: approved, cherrypick-master, cla: yes, lgtm, needs-ok-to-test, size/XS

#1915 Version updates and CE update
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/container-source/heartbeats-source.yaml
  docs/eventing/samples/cronjob-source/README.md
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kafka/source/event-source.yaml
  docs/eventing/samples/kafka/source/kafka-topic.yaml
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
Labels: approved, cla: yes, lgtm, size/L

#1912 Fix typo in microk8s doc
  docs/install/Knative-with-MicroK8s.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1901 Add annotatios in autoscale example
  docs/serving/configuring-the-autoscaler.md
Labels: approved, cherrypick-0.9, cla: yes, kind/serving, lgtm, ok-to-test, size/XS

#1908 helloworld: go clarity tweaks and go modules for shell
  docs/serving/samples/hello-world/helloworld-go/Dockerfile
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-go/helloworld.go
  docs/serving/samples/hello-world/helloworld-shell/Dockerfile
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/hello-world/helloworld-shell/go.mod
  docs/serving/samples/hello-world/helloworld-shell/invoke.go
  test/sampleapp/config.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1914 Fix the Subscription's apiVersion in debugging.
  docs/eventing/debugging/example.yaml
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1918 Use cpu metric for CPU-based autoscaling sample
  docs/serving/configuring-the-autoscaler.md
Labels: approved, cla: yes, lgtm, size/XS

#1936 Fixing links
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1932 minor typo fix
  docs/serving/knative-kubernetes-services.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1935 Add CouchDB event source
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/M

#1941 update eventing-contrib api for v0.10
  docs/reference/eventing/eventing-contrib.md
Labels: approved, cla: yes, lgtm, size/XL

#1944 point to the correct release
  docs/eventing/README.md
  docs/eventing/broker-trigger.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/debugging/README.md
  docs/eventing/event-registry.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/writing-a-source/03-reconcile-sources.md
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/M

#1945 dynamically populate the correct repo branch
  docs/eventing/README.md
  docs/eventing/broker-trigger.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/debugging/README.md
  docs/eventing/event-registry.md
  docs/eventing/getting-started.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/writing-a-source/03-reconcile-sources.md
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
  docs/serving/fluentd-requirements.md
Labels: approved, cla: yes, lgtm, size/M

#1942 remove build folder for good
  docs/build/README.md
  docs/build/_index.md
Labels: approved, cla: yes, lgtm, size/S

#1947 invalid since v0.8.1
  docs/eventing/README.md
  docs/install/README.md
  docs/serving/README.md
  docs/serving/outbound-network-access.md
  docs/serving/samples/rest-api-go/README.md
Labels: approved, cla: yes, lgtm, size/L

#1948 remove outdated content
  docs/eventing/README.md
  docs/install/README.md
  docs/serving/README.md
  docs/serving/outbound-network-access.md
  docs/serving/samples/rest-api-go/README.md
Labels: approved, cla: yes, lgtm, size/L

#1943 Add vaikas to OWNERS via new account
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1950 Fixing PubSub source example
  docs/eventing/samples/gcp-pubsub-source/README.md
  docs/eventing/samples/gcp-pubsub-source/event-display.yaml
  docs/eventing/samples/gcp-pubsub-source/gcp-pubsub-source.yaml
  docs/eventing/samples/gcp-pubsub-source/trigger.yaml
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/L
