Repository knative/docs, pull requests merged in 2019-09, with the labels that each got.

#1749 Use smaller images (Node.js, Python, Ruby)
  docs/serving/samples/hello-world/helloworld-nodejs/Dockerfile
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-python/Dockerfile
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/Dockerfile
  docs/serving/samples/hello-world/helloworld-ruby/README.md
Labels: approved, cla: yes, kind/sample, kind/serving, lgtm, ok-to-test, size/M

#1742 Add/fix some documentation for the autoscaler configuration.
  docs/serving/configuring-the-autoscaler.md
Labels: approved, cla: yes, lgtm, size/S

#1753 samples/grpc-ping-go: align with knative sample and README practices
  docs/serving/samples/grpc-ping-go/Dockerfile
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/grpc-ping-go/grpc-ping.go
  docs/serving/samples/grpc-ping-go/service.yaml
Labels: approved, cla: yes, kind/sample, lgtm, size/L

#1726 [container source] Fix the docs to point to correct 'ko publish' command
  docs/eventing/samples/container-source/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1733 directory confusion missing readinessProbe config
  docs/serving/knative-kubernetes-services.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/rest-api-go/sample-template.yaml
Labels: approved, cla: yes, lgtm, size/M

#1769 Secrets use GOOGLE_APPLICATION_CREDENTIALS as key
  docs/serving/samples/secrets-go/README.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1735 Update getting-started-knative-app.md
  docs/serving/getting-started-knative-app.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1773 Add dgerd to eng-approvers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1758 Adding Image processing sample to the list of external sample code
  docs/samples.md
Labels: approved, cla: yes, lgtm, size/XS

#1783 release-0.8 cherrypick: update gloo install guide for knative serving 0.8.0 (#1691)
  docs/install/Knative-with-Gloo.md
  docs/install/README.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/L

#1777 [samples] R sample with R server
  community/samples/README.md
  community/samples/serving/helloworld-rserver/Dockerfile
  community/samples/serving/helloworld-rserver/HelloWorld.R
  community/samples/serving/helloworld-rserver/README.md
  community/samples/serving/helloworld-rserver/server.R
  community/samples/serving/helloworld-rserver/service.yaml
Labels: approved, cla: yes, lgtm, size/L

#1732 [Sample] Update C# hello world serving sample according to Microsoft docs, to multistep build
  docs/serving/samples/hello-world/helloworld-csharp/.dockerignore
  docs/serving/samples/hello-world/helloworld-csharp/Dockerfile
  docs/serving/samples/hello-world/helloworld-csharp/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1710 Blue-green deployment update for 0.8
  docs/serving/samples/blue-green-deployment.md
Labels: approved, cherrypick-master, cla: yes, kind/enhancement, kind/sample, kind/serving, lgtm, ok-to-test, size/L, triage/needs-sample-review

#1786 Rename Choice to Parallel and cases to branches
  .gitignore
  docs/eventing/choice.md
  docs/eventing/parallel.md
  docs/eventing/samples/parallel/README.md
  docs/eventing/samples/parallel/_index.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/_index.md
  docs/eventing/samples/parallel/multiple-branches/cron-source.yaml
  docs/eventing/samples/parallel/multiple-branches/event-display.yaml
  docs/eventing/samples/parallel/multiple-branches/filters.yaml
  docs/eventing/samples/parallel/multiple-branches/parallel.yaml
  docs/eventing/samples/parallel/multiple-branches/transformers.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/_index.md
  docs/eventing/samples/parallel/mutual-exclusivity/cron-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/event-display.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/switcher.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/transformers.yaml
Labels: approved, cla: yes, lgtm, size/L

#1795 update note on eventing dependency
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1778 Remove extra spaces to correct format
  docs/serving/knative-kubernetes-services.md
Labels: approved, cla: yes, lgtm, size/M

#1779 Fix broken kafka source link
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1776 fix event sources broken links because of migration
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/M

#1727 [DOC] Add alternative shell command to delete knative service
  docs/serving/getting-started-knative-app.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1566 Added new section for custom-metrics API details
  docs/serving/custom-metrics-API.md
Labels: approved, cla: yes, kind/observability, lgtm, size/S

#1768 update with config instructions
  docs/serving/accessing-traces.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1790 Use the term source.
  docs/install/Knative-custom-install.md
  docs/reference/eventing/eventing.md
Labels: approved, cla: yes, lgtm, size/XS

#1774 serving/samples: update helloworld-go to go:1.13 and go modules
  docs/serving/samples/hello-world/helloworld-go/Dockerfile
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-go/go.mod
  test/sampleapp/config.yaml
Labels: approved, cla: yes, lgtm, size/M

#1798 update note on eventing dependency (0.8.0 release)
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1747 Create Knative-with-MicroK8s.md
  docs/install/Knative-with-MicroK8s.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1801 Use the new Serving API shape in eventing samples
  docs/eventing/broker-trigger.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
Labels: approved, cla: yes, lgtm, size/S

#1805 0.9 API docs (eventing-contrib only)
  docs/reference/README.md
  docs/reference/eventing/eventing-contrib-api.md
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
  hack/gen-api-reference-docs.sh
Labels: approved, cla: yes, lgtm, size/XXL

#1800 Fix broken links in API Spec
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, lgtm, size/XS

#1807 no markdown in the HTML
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XS

#1811 Make updating custom-domain configmap clearer
  docs/serving/using-a-custom-domain.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1818 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1808 cherry-pick #1807
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XS

#1815 Removed outdated OpenShift installation docs, new link added for up to date install guide
  docs/install/Knative-with-OpenShift.md
  docs/install/README.md
Labels: approved, cla: yes, lgtm, size/L

#1821 Improve gke static ip assign doc
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-elixir/README.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-java-quarkus/README.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-vertx/README.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-OpenShift.md
  docs/serving/getting-started-knative-app.md
  docs/serving/gke-assigning-static-ip-address.md
  docs/serving/gke-assigning-static-ip-address.png
  docs/serving/samples/autoscale-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/knative-routing-go/README.md
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/telemetry-go/README.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-external-dns-on-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1812 Update Helloworld unit test error message to make it actionable
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-python/Dockerfile
  test/sampleapp/config.go
  test/sampleapp/config.yaml
  test/sampleconsistency/sampleconsistency_test.go
Labels: approved, cla: yes, lgtm, size/M

#1820 fix a wrong indentation at knative routing go sample docs
  docs/serving/samples/knative-routing-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1825 Update install link
  docs/serving/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, size/XS

#1819 Correct path and attributes
  docs/serving/samples/traffic-splitting/README.md
Labels: approved, cherrypick-0.9, cla: yes, lgtm, needs-ok-to-test, size/S

#1831 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1813 Move scale bounds settings to annotation field
  docs/serving/configuring-the-autoscaler.md
Labels: approved, cla: yes, lgtm, size/XS, triage/needs-eng-input

#1835 remove erroneous extra backtick
  docs/serving/getting-started-knative-app.md
Labels: approved, cherrypick-master, cla: yes, lgtm, ok-to-test, size/XS

#1832 Update the Kubernetes version requirements.
  docs/eventing/getting-started.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/M

#1837 Fix invalid format in Getting Started with App Deployment
  docs/serving/getting-started-knative-app.md
Labels: approved, cherrypick-0.9, cla: yes, lgtm, size/XS
