Repository knative/docs, pull requests merged in 2020-04, with the labels that each got.

#2361 Deprecate the observability plugin
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2365 replace go with PHP in PHP sample
  docs/serving/samples/hello-world/helloworld-php/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2366 Fix typo secert => secret
  docs/serving/samples/gitwebhook-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2364 Updated upgrade links to v0.13.0
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2351 helloworld-python: Prevent "[CRITICAL] WORKER TIMEOUT" error log
  docs/serving/samples/hello-world/helloworld-python/Dockerfile
  docs/serving/samples/hello-world/helloworld-python/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2329 Update installing-istio.md
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2378 Update deps for https://github.com/knative/docs/pull/2377
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2369 Upgrade documentation includes notes about storage version migration
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/S

#2238 update cert manager version for using on gcp
  docs/serving/using-cert-manager-on-gcp.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2379 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2239 cert manager installation steps changes
  docs/serving/installing-cert-manager.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2334 Updated link to autoscale default
  docs/serving/samples/autoscale-go/README.md
Labels: approved, cla: yes, needs-ok-to-test, size/XS

#2381 Bump supported cert-manager version to 0.12
  docs/serving/installing-cert-manager.md
Labels: approved, cla: yes, lgtm, size/XS

#2376 Add machine learning serving example using python
  community/samples/README.md
  community/samples/serving/machinelearning-python-bentoml/README.md
  community/samples/serving/machinelearning-python-bentoml/iris_classifier.py
  community/samples/serving/machinelearning-python-bentoml/main.py
  community/samples/serving/machinelearning-python-bentoml/service.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2384 Update Istio version to 1.4.6
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#2355 Added clone of docs to steps and updated paths
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2236 Switch support status for triggermesh external sources
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/S

#2383 This documents the VMware sources for Knative.
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#2385 Switch net-kourier to use the artifact shortcode.
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2273 Add the instructions on how to configure the operator CRs
  docs/install/knative-with-operators.md
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, size/XL

#2390 Update references to event-display image
  docs/eventing/getting-started.md
  docs/eventing/samples/helloworld/helloworld-go/README.md
Labels: approved, cla: yes, lgtm, size/S

#2388 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/docs/LICENSE
  vendor/github.com/knative/docs/docs/serving/samples/grpc-ping-go/proto/ping.pb.go
  vendor/github.com/knative/docs/test/flag.go
  vendor/github.com/knative/docs/test/sampleapp/config.go
Labels: approved, cla: yes, lgtm, size/XXL

#2391 Updated APIs for v0.14.0 release
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#2406 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2407 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2410 Update KafkaSource example with updated bootstrapServer, Topics format
  docs/eventing/samples/kafka/source/event-source.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2413 Remove obsolete source sample
  docs/eventing/README.md
  docs/eventing/samples/writing-a-source/01-bootstrap.md
  docs/eventing/samples/writing-a-source/02-define-source.md
  docs/eventing/samples/writing-a-source/03-reconcile-sources.md
  docs/eventing/samples/writing-a-source/04-publish-to-cluster.md
  docs/eventing/samples/writing-a-source/README.md
  docs/eventing/samples/writing-a-source/_index.md
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2398 Add Meetup page
  community/meetup/README.md
  community/meetup/_index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2418 typo in 'serverless'
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2353 Gitlabsource documentation
  docs/eventing/README.md
  docs/eventing/samples/gitlab-source/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/L

#2416 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2409 Adding myself to reviewers to start reviewing
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2420 Subscriber image should not be in a sub array.
  docs/eventing/broker-trigger.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2392 Update istio version for install istio-knative-extras.yaml
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2395 Adding Knative Eventing Example
  docs/samples.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2405 Update Docs to include new field ContainerStatus to the revision status
  docs/reference/serving.md
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, lgtm, size/L

#2408 Document alternative process to setup a custom hostname for a Service
  docs/serving/using-a-custom-domain-per-service.md
Labels: approved, cla: yes, lgtm, size/M

#2423 Update triggermesh docs links after repo move
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/S

#2422 Redo the autoscaling configuration documentation.
  docs/serving/configuring-autoscaling.md
Labels: approved, cla: yes, lgtm, size/XL

#2421 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2424 Add jonatasbaldin in docs-reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS
