Repository knative/docs, pull requests merged in 2020-01, with the labels that each got.

#2080 Remove outdated TODOs
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2082 Update and simplify a few install docs
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/M

#2049 Update "Check ClusterIngress/Istio routing" in debugging-application-…
  docs/serving/debugging-application-issues.md
  docs/serving/samples/knative-routing-go/README.md
Labels: approved, cla: yes, kind/networking, kind/serving, lgtm, ok-to-test, size/M, triage/needs-eng-input

#1893 Fix Ambassador install instructions to avoid panic
  docs/install/Knative-with-Ambassador.md
Labels: approved, cla: yes, kind/networking, kind/serving, lgtm, ok-to-test, size/M, triage/needs-eng-input

#2079 call version with using '--'
  docs/install/Knative-with-Gloo.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2076 Add instruction on how to use local docker registry
  docs/serving/getting-started-knative-app.md
Labels: approved, cla: yes, kind/serving, lgtm, needs-ok-to-test, size/S

#1916 correct the README.md of docs/serving/samples/telemetry-go
  docs/serving/samples/telemetry-go/README.md
Labels: approved, cla: yes, kind/observability, lgtm, ok-to-test, size/S, triage/needs-eng-input

#2093 Add a step for installing github source
  docs/eventing/samples/github-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2091 Bump the min k8s version to 1.15
  docs/eventing/getting-started.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Ambassador.md
  docs/install/Knative-with-Docker-for-Mac.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-Gloo.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
  hack/reference-docs-gen-config.json
Labels: approved, cla: yes, lgtm, size/L

#2058 Writing sources the hard way
  docs/eventing/README.md
  docs/eventing/samples/writing-a-source/README.md
  docs/eventing/samples/writing-receive-adapter-source/01-theory.md
  docs/eventing/samples/writing-receive-adapter-source/02-lifecycle-and-types.md
  docs/eventing/samples/writing-receive-adapter-source/03-controller.md
  docs/eventing/samples/writing-receive-adapter-source/04-reconciler.md
  docs/eventing/samples/writing-receive-adapter-source/05-receive-adapter.md
  docs/eventing/samples/writing-receive-adapter-source/06-yaml.md
  docs/eventing/samples/writing-receive-adapter-source/README.md
  docs/eventing/samples/writing-receive-adapter-source/_index.md
  docs/eventing/samples/writing-receive-adapter-source/simplified-controller.png
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, kind/eventing, kind/eventing-contrib, kind/new-docs-needed, lgtm, size/XL, triage/needs-eng-input

#2100 update minor api updates for github source.
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/github-source/github-source.yaml
  docs/eventing/samples/github-source/service.yaml
Labels: approved, cla: yes, lgtm, size/S

#2094 Use the new api group for ApiServerSource.
  docs/eventing/debugging/example.yaml
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
Labels: approved, cla: yes, lgtm, size/S

#2097 Document the Contour integration with Knative.
  docs/eventing/README.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-Contour.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Minikube.md
  docs/install/README.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/L

#2022 Update C# sample to .Net Core 3.1
  docs/serving/samples/hello-world/helloworld-csharp/Dockerfile
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-csharp/helloworld-csharp.csproj
Labels: approved, cla: yes, kind/sample, lgtm, ok-to-test, size/S, triage/needs-sample-review

#2102 Fix link to yaml file in MQTT CamelSource sample
  docs/eventing/samples/apache-camel-source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2103 Rename eventing release artifacts release.yaml => eventing.yaml
  docs/eventing/getting-started.md
  docs/install/Knative-custom-install.md
  docs/install/Knative-with-AKS.md
  docs/install/Knative-with-GKE.md
  docs/install/Knative-with-Gardener.md
  docs/install/Knative-with-ICP.md
  docs/install/Knative-with-IKS.md
  docs/install/Knative-with-Minikube.md
  docs/install/Knative-with-PKS.md
  docs/install/Knative-with-any-k8s.md
Labels: approved, cla: yes, lgtm, size/M

#1887 Correct image path in sample of "kubernetes-event-source"
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
Labels: approved, cla: yes, kind/eventing-contrib, lgtm, ok-to-test, size/XS

#2106 Remove template -- moved to Community repo
  contributing/new-page-template.md
Labels: approved, cla: yes, lgtm, size/M

#2095 Use the new api group for SinkBinding.
  docs/eventing/samples/sinkbinding/README.md
  docs/eventing/samples/sinkbinding/sinkbinding.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2110 Update check version cmd
  docs/install/check-install-version.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2089 Update configuring-autoscaling.md
  docs/serving/configuring-autoscaling.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2098 Update knative install using Gloo
  docs/install/Knative-with-Gloo.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2045 Added instructions for installing kn
  docs/install/install-kn.md
  docs/reference/client/README.md
  docs/reference/client/_index.md
Labels: approved, cla: yes, kind/cli, kind/install, lgtm, size/S

#2115 Removing directory temporarily
  docs/reference/client/README.md
  docs/reference/client/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#2117 Reference docs 0.12
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#2121 Updating to LATEST for Kafka Channel/Source
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cherrypick-0.12, cla: yes, lgtm, size/S

#2083 Update the Auto TLS instruction
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/L

#2006 Kourier Installation guide for Knative Serving
  docs/install/README.md
  docs/install/knative-with-kourier.md
Labels: approved, cherrypick-0.12, cla: yes, kind/install, kind/networking, lgtm, ok-to-test, size/L

#2128 Release 0.12
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/source/README.md
  docs/install/README.md
  docs/install/knative-with-kourier.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/XL

#2135 fix default template so it works, use event display that works
  docs/eventing/samples/kafka/channel/000-ksvc.yaml
  docs/eventing/samples/kafka/channel/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2132 added github.com/maximilien/knfun as a Knative client demo sample
  community/samples/README.md
Labels: approved, cla: yes, lgtm, size/S

#2130 Remove superfluous conjunction
  docs/install/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2146 Fix missing type in edit command
  docs/install/Knative-with-Contour.md
Labels: approved, cla: yes, lgtm, size/XS

#2148 fix the service yaml, update image
  docs/eventing/samples/kafka/source/event-display.yaml
Labels: approved, cherrypick-0.12, cla: yes, lgtm, size/S

#2142 Adding new reviewers
  OWNERS_ALIASES
  docs/eventing/OWNERS
  docs/install/OWNERS
  docs/serving/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#2086 Move Contributing to sub-dir of knative.dev/community
  .github/pull-request-template.md
  README.md
  community/_index.md
  community/contributing/_index.md
  community/samples/README.md
  docs/README.md
  docs/eventing/README.md
  docs/reference/README.md
Labels: approved, cla: yes, lgtm, size/M

#2157 fix english
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2143 Update OWNERS_ALIASES for Productivity WG
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2159 Cherry-pick batch on 1/31 into release-0.12
  community/samples/README.md
  docs/eventing/samples/kafka/source/event-display.yaml
Labels: approved, cla: yes, lgtm, size/S

#2160 Create overview.md
  docs/concepts/overview.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
