Repository knative/docs, pull requests merged in 2020-10, with the labels that each got.

#2834 hello-world java spark using kn and tabs
  docs/serving/samples/hello-world/helloworld-java-spark/Dockerfile
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/index.md
  docs/serving/samples/hello-world/helloworld-java-spark/main/java/com/example/helloworld/HelloWorldApplication.java
  docs/serving/samples/hello-world/helloworld-java-spark/src/main/java/com/example/helloworld/HelloWorldApplication.java
Labels: approved, cla: yes, lgtm, size/L

#2876 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2875 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#2878 Make feature flag doc less misleading
  docs/serving/feature-flags.md
Labels: approved, cla: yes, lgtm, size/XS

#2863 Updated landing page
  community/contributing/_index.md
  community/contributing/images/knative-audience.png
  community/contributing/images/knative-audience.svg
  community/contributing/images/knative-version.png
  community/contributing/images/logo/cmyk/knative-logo-cmyk.ai
  community/contributing/images/logo/cmyk/knative-logo-cmyk.eps
  community/contributing/images/logo/cmyk/knative-logo-cmyk.jpg
  community/contributing/images/logo/cmyk/knative-logo-cmyk.pdf
  community/contributing/images/logo/cmyk/knative-logo-cmyk.png
  community/contributing/images/logo/rgb/knative-logo-rgb.ai
  community/contributing/images/logo/rgb/knative-logo-rgb.eps
  community/contributing/images/logo/rgb/knative-logo-rgb.jpg
  community/contributing/images/logo/rgb/knative-logo-rgb.pdf
  community/contributing/images/logo/rgb/knative-logo-rgb.png
  community/contributing/images/logo/style-guide.pdf
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XXL

#2880 updating ApiServerSource example to use v1
  docs/eventing/debugging/README.md
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
  docs/eventing/sources/apiserversource.md
Labels: approved, cla: yes, lgtm, size/S

#2903 apiserversource is now v1
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#2900 [release-0.17] Remove Eventing Migration
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/L

#2899 [release-0.18] Remove Eventing Migration
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/L

#2901 [release-0.16] Remove Eventing Migration
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/L

#2902 [release-0.15] Remove Eventing Migration
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/L

#2898 Remove Eventing Migration
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, hacktoberfest-accepted, lgtm, size/L

#2897 Change event type in Sequence with Broker example
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cherrypick-0.16, cherrypick-0.17, cherrypick-0.18, cla: yes, hacktoberfest-accepted, lgtm, size/XS

#2915 [release-0.17] Change event type in Sequence with Broker example (#2897)
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2914 [release-0.16] Change event type in Sequence with Broker example (#2897)
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2811 Fix the broken links for serving and eventing configuration by configmap
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, size/XS

#2893 do not lint .ai files.
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2896 Fix autoscale-go sample's yaml file path
  docs/serving/autoscaling/autoscale-go/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2873 Add blog post on project governance changes
  blog/steering/governance-changes.md
Labels: approved, cla: yes, lgtm, size/M

#2860 Add documentation for max-scale-limit
  docs/serving/autoscaling/scale-bounds.md
Labels: approved, cla: yes, lgtm, size/XS

#2919 fix typo in blog post frontmatter
  blog/steering/governance-changes.md
Labels: approved, cla: yes, lgtm, size/XS

#2913 Switch the base JRE to one that supports multiple architectures.
  docs/serving/samples/hello-world/helloworld-java-spring/Dockerfile
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/Dockerfile
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
Labels: approved, cla: yes, lgtm, size/S

#2877 Release notes for Knative 0.18
  blog/releases/announcing-knative-v0-17-release.md
  blog/releases/announcing-knative-v0-18-release.md
Labels: approved, cla: yes, lgtm, size/L

#2925 Our docs represent how we write code
  docs/serving/autoscaling/autoscale-go/test/test.go
Labels: approved, cla: yes, lgtm, size/M

#2926 Bump to Istio 1.7.1 for tested version
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#2886 [master] Fix default installation without sidecar injection (#2775)
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#2890 Explicitly point out not installing ns-cert component for http01 challenge
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, hacktoberfest-accepted, lgtm, size/XS

#2929 Add ZenDesk and Slack to the list of sources
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#2912 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#2918 Update SinkBinding docs to use v1
  docs/eventing/samples/sinkbinding/README.md
  docs/eventing/samples/sinkbinding/sinkbinding.yaml
  docs/eventing/samples/writing-event-source-easy-way/README.md
  docs/eventing/sources/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/S

#2921 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2887 drop serving v1beta1 and v1alpha1 APIs
  docs/reference/api/serving.md
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, lgtm, size/XXL

#2732 [multi-container]Add samples for multi container support
  docs/serving/samples/README.md
  docs/serving/samples/multi-container/README.md
  docs/serving/samples/multi-container/_index.md
  docs/serving/samples/multi-container/service.yaml
  docs/serving/samples/multi-container/servingcontainer/Dockerfile
  docs/serving/samples/multi-container/servingcontainer/go.mod
  docs/serving/samples/multi-container/servingcontainer/servingcontainer.go
  docs/serving/samples/multi-container/sidecarcontainer/Dockerfile
  docs/serving/samples/multi-container/sidecarcontainer/go.mod
  docs/serving/samples/multi-container/sidecarcontainer/sidecarcontainer.go
Labels: approved, cla: yes, lgtm, size/L

#2906 Do not add visibility label to Route
  docs/serving/cluster-local-route.md
Labels: approved, cla: yes, lgtm, size/XS

#2882 Orchestrating Cloud Events Meetup Blog Post
  blog/articles/orchestrating-cloud-events-with.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2933 fix yaml error
  blog/articles/orchestrating-cloud-events-with.md
Labels: approved, cla: yes, lgtm, size/XS

#2935 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2840 Wrong sample link is wrong
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2928 Update scale-to-zero.md
  docs/serving/autoscaling/scale-to-zero.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2940 Remove security vulnerabilities from the iot-core sample
  docs/eventing/samples/iot-core/generator/main.go
  go.mod
  go.sum
  vendor/github.com/form3tech-oss/jwt-go/.gitignore
  vendor/github.com/form3tech-oss/jwt-go/.travis.yml
  vendor/github.com/form3tech-oss/jwt-go/LICENSE
  vendor/github.com/form3tech-oss/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/form3tech-oss/jwt-go/README.md
  vendor/github.com/form3tech-oss/jwt-go/VERSION_HISTORY.md
  vendor/github.com/form3tech-oss/jwt-go/claims.go
  vendor/github.com/form3tech-oss/jwt-go/doc.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/errors.go
  vendor/github.com/form3tech-oss/jwt-go/hmac.go
  vendor/github.com/form3tech-oss/jwt-go/map_claims.go
  vendor/github.com/form3tech-oss/jwt-go/none.go
  vendor/github.com/form3tech-oss/jwt-go/parser.go
  vendor/github.com/form3tech-oss/jwt-go/rsa.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_pss.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/signing_method.go
  vendor/github.com/form3tech-oss/jwt-go/token.go
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/codec.go
  vendor/github.com/satori/go.uuid/generator.go
  vendor/github.com/satori/go.uuid/sql.go
  vendor/github.com/satori/go.uuid/uuid.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#2945 Bump golang versions to align all samples
  docs/serving/samples/hello-world/helloworld-go/go.mod
  docs/serving/samples/hello-world/helloworld-shell/go.mod
Labels: approved, cla: yes, lgtm, size/XS

#2908 Removed deprecated observability plugin
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, kind/cleanup, kind/observability, lgtm, size/M

#2907 Removed deprecated observability plugin
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, kind/cleanup, kind/observability, lgtm, size/M

#2904 Removed deprecated observability plugin
  docs/install/any-kubernetes-cluster.md
Labels: approved, cherrypick-0.15, cherrypick-0.16, cherrypick-0.17, cherrypick-0.18, cla: yes, hacktoberfest-accepted, kind/cleanup, kind/observability, lgtm, size/M

#2905 Removed deprecated observability plugin
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, kind/cleanup, kind/observability, lgtm, size/M

#2938 Document Broker Delivery Options
  docs/eventing/broker/README.md
  docs/eventing/event-delivery.md
Labels: approved, cla: yes, lgtm, size/M

#2932 Update ContainerSource docs and examples to use v1
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/container-source/heartbeats-source.yaml
  docs/eventing/samples/writing-event-source-easy-way/README.md
  docs/eventing/sources/_index.md
  docs/eventing/sources/apiserversource.md
  docs/eventing/sources/containersource.md
  docs/eventing/sources/pingsource.md
  docs/eventing/sources/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/S

#2870 Fix liks on CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2946 Removing references to old monitoring stack
  docs/README.md
  docs/eventing/accessing-traces.md
  docs/install/upgrade-installation.md
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-metrics.md
  docs/serving/accessing-traces.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/debugging-application-issues.md
  docs/serving/debugging-performance-issues.md
  docs/serving/fluentd-requirements.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/samples/telemetry-go/Dockerfile
  docs/serving/samples/telemetry-go/OWNERS
  docs/serving/samples/telemetry-go/README.md
  docs/serving/samples/telemetry-go/index.md
  docs/serving/samples/telemetry-go/prometheus-test.yaml
  docs/serving/samples/telemetry-go/route.yaml
  docs/serving/samples/telemetry-go/sample.yaml
  docs/serving/samples/telemetry-go/telemetrysample.go
  docs/serving/setting-up-a-logging-plugin.md
Labels: approved, cherrypick-0.15, cherrypick-0.16, cherrypick-0.17, cherrypick-0.18, cla: yes, kind/cleanup, kind/observability, lgtm, priority/0, size/XXL

#2948 Add annotation "autoscaling.knative.dev/metric: rps" when configuragi…
  docs/serving/autoscaling/rps-target.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2955 [release-0.18] fix integration tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2956 [release-0.17] fix integration
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2952 Cherry-pick monitoring changes to 0.18
  docs/README.md
  docs/eventing/accessing-traces.md
  docs/install/upgrade-installation.md
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-metrics.md
  docs/serving/accessing-traces.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/debugging-application-issues.md
  docs/serving/debugging-performance-issues.md
  docs/serving/fluentd-requirements.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/samples/telemetry-go/Dockerfile
  docs/serving/samples/telemetry-go/OWNERS
  docs/serving/samples/telemetry-go/README.md
  docs/serving/samples/telemetry-go/index.md
  docs/serving/samples/telemetry-go/prometheus-test.yaml
  docs/serving/samples/telemetry-go/route.yaml
  docs/serving/samples/telemetry-go/sample.yaml
  docs/serving/samples/telemetry-go/telemetrysample.go
  docs/serving/setting-up-a-logging-plugin.md
Labels: approved, cla: yes, lgtm, size/XXL

#2953 Cherry-pick monitoring changes to 0.17
  docs/README.md
  docs/eventing/accessing-traces.md
  docs/install/upgrade-installation.md
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-metrics.md
  docs/serving/accessing-traces.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/debugging-application-issues.md
  docs/serving/fluentd-requirements.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/samples/telemetry-go/Dockerfile
  docs/serving/samples/telemetry-go/OWNERS
  docs/serving/samples/telemetry-go/README.md
  docs/serving/samples/telemetry-go/index.md
  docs/serving/samples/telemetry-go/prometheus-test.yaml
  docs/serving/samples/telemetry-go/route.yaml
  docs/serving/samples/telemetry-go/sample.yaml
  docs/serving/samples/telemetry-go/telemetrysample.go
  docs/serving/setting-up-a-logging-plugin.md
Labels: approved, cla: yes, lgtm, size/XXL

#2954 CP: Removing references to old monitoring stack 0.16
  docs/README.md
  docs/eventing/accessing-traces.md
  docs/install/upgrade-installation.md
  docs/serving/README.md
  docs/serving/accessing-logs.md
  docs/serving/accessing-metrics.md
  docs/serving/accessing-traces.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/debugging-application-issues.md
  docs/serving/fluentd-requirements.md
  docs/serving/installing-logging-metrics-traces.md
  docs/serving/samples/telemetry-go/Dockerfile
  docs/serving/samples/telemetry-go/OWNERS
  docs/serving/samples/telemetry-go/README.md
  docs/serving/samples/telemetry-go/index.md
  docs/serving/samples/telemetry-go/prometheus-test.yaml
  docs/serving/samples/telemetry-go/route.yaml
  docs/serving/samples/telemetry-go/sample.yaml
  docs/serving/samples/telemetry-go/telemetrysample.go
  docs/serving/setting-up-a-logging-plugin.md
Labels: approved, cla: yes, lgtm, size/XXL

#2961 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2964 delete useless placeholder for ping-source page
  docs/eventing/samples/ping-source/README.md
  docs/eventing/samples/ping-source/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2968 Issue 2966
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2971 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2974 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2975 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2978 drop dead links
  docs/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2979 [release-0.18] drop dead links
  docs/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2980 [release-0.17] drop dead links
  docs/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2981 [release-0.16 ]drop dead links
  docs/README.md
  docs/serving/samples/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2982 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2983 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/sys/LICENSE
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2972 Remove reference to eventing-contrib
  docs/eventing/samples/writing-event-source/07-eventing-contrib.md
  docs/eventing/samples/writing-event-source/07-knative-sandbox.md
  docs/eventing/samples/writing-event-source/README.md
Labels: approved, cla: yes, lgtm, size/M
