Repository knative/docs, pull requests merged in 2020-12, with the labels that each got.

#3071 Fix a rendering glitch that hides eventing.
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3058 Small typo in docs/eventing/getting-started.md
  docs/eventing/getting-started.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2920 Sink binding docs overhaul
  docs/eventing/README.md
  docs/eventing/samples/sinkbinding/README.md
  docs/eventing/samples/sinkbinding/heartbeats-source.yaml
  docs/eventing/samples/sinkbinding/index.md
  docs/eventing/samples/sinkbinding/service.yaml
  docs/eventing/samples/sinkbinding/sinkbinding.yaml
  docs/eventing/sources/_index.md
  docs/eventing/sources/sinkbinding.md
Labels: Toggle me for site "Branch Deploy" build, approved, cla: yes, lgtm, size/XL

#2939 fix: add a reference to eventing sources page instead of having a list
  docs/eventing/samples/writing-event-source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3065 Update Eventing Readme
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3064 Update Eventing README
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3069 Fix Kafka Binding example
  docs/eventing/samples/kafka/binding/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3070 Fix scala sample of serving
  docs/serving/samples/hello-world/helloworld-scala/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3075 Fix typo
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3086 Update .../sequence-termina/README.md
  docs/eventing/samples/sequence/sequence-terminal/README.md
Labels: approved, cla: yes, lgtm, size/S

#3090 Update install-kn.md
  docs/install/install-kn.md
Labels: approved, cla: yes, lgtm, size/XS

#3089 Update 01-theory.md: nit
  docs/eventing/samples/writing-event-source/01-theory.md
Labels: approved, cla: yes, lgtm, size/XS

#3093 Update writing-event-source/07-knative-sandbox.md weight
  docs/eventing/samples/writing-event-source/07-knative-sandbox.md
Labels: approved, cla: yes, lgtm, size/XS

#3074 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/install-istio.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3080 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3097 IBM Cloud Code Engine offers Knative
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3067 Adding configuration description for TLS/SASL for the KafkaChannel
  docs/eventing/samples/kafka/channel/README.md
Labels: approved, cla: yes, lgtm, size/M

#3091 Update writing-event-source/01-theory.md
  docs/eventing/samples/writing-event-source/01-theory.md
Labels: approved, cla: yes, lgtm, size/XS

#3096 Remove prometheus addon from Istio installation instructions
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/S

#3087 Update ..sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cla: yes, lgtm, size/M

#3098 add docs for hostAliases feature gate
  docs/serving/feature-flags.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3052 Update installing-istio.md
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3083 [New Blog Post] Orchestrating Events with Knative and Kogito
  blog/articles/event-drive-app-knative-eventing-kogito.md
  blog/articles/images/kogito/example-patientonboarding.png
  blog/articles/images/kogito/knative-eventing-kogito-operator.png
  blog/articles/images/kogito/kogito-knative-impl-producing-event.png
  blog/articles/images/kogito/kogito-process-workflow-file.png
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3051 fix broken url in docs
  docs/install/operator/configuring-eventing-cr.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3099 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3106 fix broken url in docs
  docs/install/operator/configuring-eventing-cr.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3108 Fixing images and reviewers header on Kogito Blog
  blog/articles/event-drive-app-knative-eventing-kogito.md
  blog/articles/images/kogito-example-patientonboarding.png
  blog/articles/images/kogito-knative-eventing-kogito-operator.png
  blog/articles/images/kogito-knative-impl-producing-event.png
  blog/articles/images/kogito-process-workflow-file.png
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3109 Adding absolute path for Kogito article images
  blog/articles/event-drive-app-knative-eventing-kogito.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3101 Add documentation to sinkbinding modes
  docs/eventing/sources/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/XS

#3114 Add the description on how to to append customized the manifests
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/M

#3118 Add docs on mTLS and Istio authorization policy
  docs/serving/images/architecture.png
  docs/serving/istio-authorization.md
Labels: approved, cla: yes, lgtm, size/M

#3120 Fix typo in istio authorization docs
  docs/serving/istio-authorization.md
Labels: approved, cla: yes, lgtm, size/XS
