Repository knative/docs, pull requests merged in 2020-11, with the labels that each got.

#2985 Change tag header based routing config to config-features
  docs/serving/samples/tag-header-based-routing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2988 fix dead link in config-trace
  docs/serving/accessing-traces.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2888 Update the links for operator docs
  docs/install/knative-with-operators.md
  docs/install/operator/configuring-serving-cr.md
  docs/serving/feature-flags.md
Labels: approved, cla: yes, lgtm, size/S

#2991 CloudEvents Rust example: update to sdk 0.3
  docs/serving/samples/cloudevents/cloudevents-rust/Cargo.lock
  docs/serving/samples/cloudevents/cloudevents-rust/Cargo.toml
  docs/serving/samples/cloudevents/cloudevents-rust/src/main.rs
Labels: approved, cla: yes, lgtm, size/L

#2962 Updated links for broker and trigger. Broke up the single link into two.
  docs/eventing/event-registry.md
Labels: approved, cherrypick-0.16, cherrypick-0.17, cherrypick-0.18, cherrypick-master, cla: yes, lgtm, needs-cherry-pick, size/XS

#2973 Fixed broken links in any-kubernetes-cluster related to eventing
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS, triage/needs-eng-input

#2744 Documenting how to configure system resources for eventing
  docs/install/operator/configuring-eventing-cr.md
Labels: approved, cla: yes, lgtm, size/M

#2965 Fix broken links from sandbox moved files
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#2827 docs(cloudevents): try cloudevents-nodejs with kn
  docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
Labels: approved, cla: yes, lgtm, size/M

#2993 RE #2965: Updated links for 0.18
  docs/eventing/channels/channels-crds.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#2833 hello world java with tabs
  docs/serving/samples/hello-world/helloworld-java-spring/index.md
Labels: approved, cla: yes, lgtm, size/L

#2969 Updated trigger link in eventing docs
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3001 Make newlines consistent across samples
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/src/main/kotlin/com/example/hello/Main.kt
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/index.js
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-php/index.php
Labels: approved, cla: yes, lgtm, size/S

#3003 add missing secret command for contour tls setup
  docs/serving/using-a-tls-cert.md
Labels: approved, cla: yes, lgtm, size/XS

#3004 Fix website build
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2996 RE #2988 And RE #2948
  docs/serving/accessing-traces.md
  docs/serving/autoscaling/rps-target.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2832 Reworked shell hello world example
  docs/serving/samples/hello-world/helloworld-shell/Dockerfile
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/hello-world/helloworld-shell/go.mod
  docs/serving/samples/hello-world/helloworld-shell/index.md
  docs/serving/samples/hello-world/helloworld-shell/invoke.go
  docs/serving/samples/hello-world/helloworld-shell/script.sh
  test/sampleapp/config.yaml
  test/sampleconsistency/sampleconsistency_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2992 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#2994 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#2807 Switch helloworld-go with kn
  docs/serving/samples/hello-world/helloworld-go/Dockerfile
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-go/index.md
  docs/serving/samples/hello-world/helloworld-shell/index.md
Labels: approved, cla: yes, lgtm, size/L

#3010 Drop the `-alpine` for dotnet, it isn't multi-arch.
  docs/serving/samples/hello-world/helloworld-csharp/Dockerfile
  docs/serving/samples/hello-world/helloworld-csharp/README.md
Labels: approved, cla: yes, lgtm, size/S

#2999 RE #2948 Add annotation "autoscaling.knative.dev/metric: rps"
  docs/serving/autoscaling/rps-target.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3014 Add csantanapr as eng approver
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2769 examples(nodejs): bump to the latest 3.x version of cloudevents SDK
  docs/serving/samples/cloudevents/cloudevents-nodejs/index.js
  docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json
  docs/serving/samples/cloudevents/cloudevents-nodejs/package.json
Labels: approved, cla: yes, lgtm, size/M, triage/needs-eng-input

#2998 RE #2948 Add annotation "autoscaling.knative.dev/metric: rps"
  docs/serving/autoscaling/rps-target.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3015 ignore some java related files
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#3013 Blog ksc nominations
  blog/steering/2020-11-ksc-elections.md
Labels: approved, cla: yes, lgtm, size/M

#3019 fix yaml
  blog/steering/2020-11-ksc-elections.md
Labels: approved, cla: yes, lgtm, size/XS

#2885 [release-0.18] Fix default installation without sidecar injection (#2775)
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#3016 Transform Scala example to use a Dockerfile
  docs/serving/samples/hello-world/helloworld-scala/Dockerfile
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-scala/build.sbt
  docs/serving/samples/hello-world/helloworld-scala/helloworld-scala.yaml
  docs/serving/samples/hello-world/helloworld-scala/project/build.properties
  docs/serving/samples/hello-world/helloworld-scala/project/plugins.sbt
Labels: approved, cla: yes, lgtm, size/L

#3007 Cherry-Pick 0.18 - Updated links for broker and trigger. Broke up the single link into t…
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, size/XS

#3008 Cherry-Pick 0.17 - Updated links for broker and trigger. Broke up the single link into t…
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, size/XS

#2989 Add sample logging configuration using fluentbit as collector and forwarder
  docs/install/collecting-logs/README.md
  docs/install/collecting-logs/_index.md
  docs/install/collecting-logs/fluent-bit-collector.yaml
  docs/install/collecting-logs/fluent-bit-configmap.yaml
  docs/install/collecting-logs/system.svg
Labels: approved, cla: yes, lgtm, size/L

#3020 Align Scala sample with the rest of our samples
  docs/serving/samples/hello-world/helloworld-scala/Dockerfile
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-scala/build.sbt
  docs/serving/samples/hello-world/helloworld-scala/service.yaml
  docs/serving/samples/hello-world/helloworld-scala/src/main/resources/application.conf
  docs/serving/samples/hello-world/helloworld-scala/src/main/scala/example/HelloWorldScala.scala
Labels: approved, cla: yes, lgtm, size/M

#2990 Better doc for channel config via operator
  docs/install/operator/configuring-eventing-cr.md
Labels: approved, cla: yes, lgtm, size/M

#3033 Ignore false-positive divisive language flagging
  .wokeignore
Labels: approved, cla: yes, lgtm, size/XS

#3029 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3025 Add description on how to configure each ingress for knative serving
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#3037 [feat] Add community calendar
  community/calendar/_index.md
Labels: approved, cla: yes, lgtm, size/S

#3043 Update API build and generate 0.19 API docs
  docs/reference/api/README.md
  docs/reference/api/eventing/eventing-contrib-api.md
  docs/reference/api/eventing/eventing-contrib.md
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
  hack/gen-api-reference-docs.sh
Labels: approved, cla: yes, kind/api, kind/api-change, lgtm, size/XXL

#3050 Simplify Kotlin example and bump versions to be more recent
  docs/serving/samples/hello-world/helloworld-kotlin/Dockerfile
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/build.gradle
Labels: approved, cla: yes, lgtm, size/M

#3039 Adding docs for the sugar controller
  docs/eventing/sugar/README.md
  docs/eventing/sugar/_index.md
Labels: approved, cla: yes, lgtm, size/L

#3027 Release notes 0.19
  blog/releases/announcing-knative-v0-19-release.md
Labels: approved, cla: yes, lgtm, size/L

#3035 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/install-istio.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-ci-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-ci-no-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-kind-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-kind-no-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-minimal.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/placeholder.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3031 Document Apache Kafka Sink
  docs/eventing/sink/OWNERS
  docs/eventing/sink/_index.md
  docs/eventing/sink/kafka-sink.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cherrypick-0.18, cla: yes, lgtm, size/L

#3030 Add install instructions for DomainMapping CRD
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#3053 helloworld shell sample: Switch to use CGI bin for the output
  docs/serving/samples/hello-world/helloworld-shell/Dockerfile
  docs/serving/samples/hello-world/helloworld-shell/index.md
  docs/serving/samples/hello-world/helloworld-shell/script.sh
Labels: approved, cla: yes, lgtm, size/M

#3060 [0.19] Document Apache Kafka Sink (#3031)
  docs/eventing/sink/OWNERS
  docs/eventing/sink/_index.md
  docs/eventing/sink/kafka-sink.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/L

#3023 Polish the auto TLS related docs
  docs/serving/installing-cert-manager.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/M

#3055 Update docs/serving/samples/helloworld index
  docs/serving/samples/hello-world/helloworld-go/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3054 Update getting-started-knative-app.md
  docs/serving/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2771 doc: fix path to autoscale-go sample
  docs/serving/autoscaling/autoscale-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3062 [Release-0.19] Add install instructions for DomainMapping CRD
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#3045 Add cloudevents-spring sample
  docs/serving/samples/cloudevents/cloudevents-spring/.gitignore
  docs/serving/samples/cloudevents/cloudevents-spring/.mvn/wrapper/MavenWrapperDownloader.java
  docs/serving/samples/cloudevents/cloudevents-spring/.mvn/wrapper/maven-wrapper.jar
  docs/serving/samples/cloudevents/cloudevents-spring/.mvn/wrapper/maven-wrapper.properties
  docs/serving/samples/cloudevents/cloudevents-spring/README.md
  docs/serving/samples/cloudevents/cloudevents-spring/index.md
  docs/serving/samples/cloudevents/cloudevents-spring/mvnw
  docs/serving/samples/cloudevents/cloudevents-spring/mvnw.cmd
  docs/serving/samples/cloudevents/cloudevents-spring/pom.xml
  docs/serving/samples/cloudevents/cloudevents-spring/service.yaml
  docs/serving/samples/cloudevents/cloudevents-spring/src/main/java/org/knative/examples/cloudevents/spring/CloudEventSampleApplication.java
  docs/serving/samples/cloudevents/cloudevents-spring/src/test/java/org/knative/examples/cloudevents/spring/CloudEventSampleApplicationFunctionTests.java
  docs/serving/samples/cloudevents/cloudevents-spring/src/test/java/org/knative/examples/cloudevents/spring/CloudEventSampleApplicationIntegrationTests.java
  docs/serving/samples/cloudevents/cloudevents-spring/src/test/java/org/knative/examples/cloudevents/spring/KSinkCloudEventSampleApplicationIntegrationTests.java
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#3063 fix bad image link in gke-assigning-static-ip-address
  docs/serving/gke-assigning-static-ip-address.md
  docs/serving/images/gke-assigning-static-ip-address.png
Labels: approved, cla: yes, lgtm, size/XS

#3066 Fix typo
  docs/serving/feature-flags.md
  docs/serving/samples/rest-api-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
