Repository knative/docs, pull requests merged in 2020-09, with the labels that each got.

#2784 fix the min k8s version
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2791 Document the feature/extension flags.
  docs/serving/feature-flags.md
Labels: approved, cla: yes, do-not-merge/hold, lgtm, size/L

#2767 Add the instruction on how to use spec.version and spec.manifests
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#2793 [release-0.17] Add the instruction on how to use spec.version and spec.manifests
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#2780 Add release notes for knative 0.17
  blog/releases/announcing-knative-v0-17-release.md
Labels: approved, cla: yes, lgtm, size/L

#2789 operator install prereq kubernetes 1.16 minimum version
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/XS

#2788 Updated cloudevents-vertx sample to latest sdk-java 2.0.0-milestone2
  docs/serving/samples/cloudevents/cloudevents-vertx/pom.xml
  docs/serving/samples/cloudevents/cloudevents-vertx/src/main/java/org/knative/examples/cloudevents/vertx/CloudEventSampleVerticle.java
Labels: approved, cla: yes, lgtm, size/M

#2794 add DockerHubSource to the list of sources
  docs/eventing/sources/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2799 Remove unnecessary occurrences of whitelist and master.
  docs/install/operator/configuring-serving-cr.md
  docs/serving/debugging-performance-issues.md
  test/e2e/sampleapp_test.go
  test/flag.go
  test/sampleconsistency/sampleconsistency_test.go
Labels: approved, cla: yes, lgtm, size/S

#2742 Updates a broken docker link to docker.io
  docs/serving/deploying/private-registry.md
Labels: approved, cla: yes, lgtm, size/XS

#2761 Remove deprecated and have only the fqn for injection
  docs/eventing/samples/helloworld/helloworld-python/README.md
  docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2786 fixing typo
  docs/serving/getting-started-knative-app.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2664 Fix the mismatch process for creating ksvc based on hello-go
  docs/serving/services/creating-services.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2730 Updated cloudevents-rust sample to sdk-rust 0.2
  docs/serving/samples/cloudevents/cloudevents-rust/Cargo.lock
  docs/serving/samples/cloudevents/cloudevents-rust/Cargo.toml
  docs/serving/samples/cloudevents/cloudevents-rust/src/main.rs
Labels: approved, cla: yes, lgtm, size/M

#2631 Updating references to the real REPO url
  docs/eventing/samples/writing-event-source/01-theory.md
  docs/eventing/samples/writing-event-source/04-reconciler.md
  docs/eventing/samples/writing-event-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2800 Move Kubernetes to 1.16+ (v0.15)
  docs/eventing/samples/writing-receive-adapter-source/06-yaml.md
  docs/install/any-kubernetes-cluster.md
  docs/install/knative-with-operators.md
Labels: approved, cherrypick-0.15, cla: yes, lgtm, needs-ok-to-test, ok-to-test, size/XS

#2802 Move Kubernetes to 1.16+ (v0.17)
  docs/eventing/samples/writing-event-source/06-yaml.md
  docs/install/any-kubernetes-cluster.md
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2801 Move Kubernetes to 1.16+ (v0.16)
  docs/eventing/getting-started.md
  docs/eventing/samples/writing-event-source/06-yaml.md
  docs/install/knative-with-operators.md
Labels: approved, cherrypick-0.16, cla: yes, lgtm, needs-ok-to-test, size/XS

#2808 Promote net-contour to stable.
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2815 [Kafka Broker] Change installation steps and artifact names
  docs/eventing/broker/kafka-broker.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/M

#2818 v1alpha1 -> v1 for Trigger
  docs/eventing/samples/helloworld/helloworld-python/README.md
  docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2745 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#2819 fix the link to camel
  docs/eventing/sources/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2805 Try cloudevents-go with kn
  docs/serving/samples/cloudevents/cloudevents-go/README.md
  docs/serving/samples/cloudevents/cloudevents-go/index.md
  docs/serving/samples/cloudevents/cloudevents-go/service.yaml
Labels: approved, cla: yes, lgtm, size/L

#2826 fix istio install
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2825 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2828 Fix the doc layout so it actually renders the whole file
  docs/serving/autoscaling/concurrency.md
Labels: approved, cla: yes, lgtm, size/XS

#2830 Fix broken hash link in documentation
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2831 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2775 Fix default installation without sidecar injection
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2836 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#2822 CloudEvents Rust tabbed doc with kn
  docs/serving/samples/cloudevents/cloudevents-rust/README.md
  docs/serving/samples/cloudevents/cloudevents-rust/index.md
Labels: approved, cla: yes, lgtm, size/L

#2823 CloudEvents Vert.x tabbed doc with kn
  docs/serving/samples/cloudevents/cloudevents-vertx/index.md
Labels: approved, cla: yes, lgtm, size/L

#2847 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2806 Update reference section as per #1883
  docs/reference/_index.md
  docs/reference/api/README.md
  docs/reference/api/_index.md
  docs/reference/api/eventing/_index.md
  docs/reference/api/eventing/eventing-contrib-api.md
  docs/reference/api/eventing/eventing-contrib.md
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving-api.md
  docs/reference/api/serving.md
  docs/reference/client/README.md
  docs/reference/client/_index.md
  docs/reference/relnotes/_index.md
  docs/reference/resources.md
Labels: approved, cherrypick-0.14, cherrypick-0.15, cherrypick-0.16, cherrypick-0.17, cla: yes, kind/cleanup, kind/enhancement, lgtm, size/M

#2841 Add initial docs for config-deployment CM
  docs/serving/services/deployment.md
Labels: approved, cla: yes, lgtm, size/M

#2848 fix links to knative sandbox sources and inline source README
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/samples/writing-event-source/07-eventing-contrib.md
  docs/eventing/sources/README.md
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/L

#2850 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#2853 Updated link for RH OCP offering
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#2849 Add Redis Source
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#2846 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2856 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2859 [Automated] Fix misspellings
  docs/eventing/flows/sequence.md
  docs/eventing/samples/apache-camel-source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2861 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2862 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2795 Adding a section about new releases blog
  blog/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2838 Add documentation for disabling AutoTLS per service/route via annotation
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/S

#2835 Fix alignment in example output
  docs/eventing/broker/kafka-broker.md
Labels: approved, cla: yes, lgtm, size/XS

#2864 Update accessing-traces.md
  docs/serving/accessing-traces.md
Labels: approved, cla: yes, lgtm, size/XS

#2837 Added note about the configmap not being complete
  docs/serving/tag-resolution.md
Labels: approved, cla: yes, lgtm, size/XS

#2871 Add global configuration for target-burst-capacity and some corrections
  docs/serving/autoscaling/target-burst-capacity.md
Labels: approved, cla: yes, lgtm, size/M

#2857 Document Scale Down Delay
  docs/serving/autoscaling/scale-bounds.md
Labels: approved, cla: yes, lgtm, size/M

#2865 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#2869 remove Sams permissions
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2872 Add tested Istio version for clarity
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#2874 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2867 API docs for 0.18 docs release
  docs/reference/api/README.md
  docs/reference/api/_index.md
  docs/reference/api/eventing/eventing-contrib.md
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
  docs/reference/relnotes/_index.md
Labels: approved, cla: yes, lgtm, size/XXL
