Repository knative/docs, pull requests merged in 2020-03, with the labels that each got.

#2263 Add `--upgrade` to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/S

#2259 Update docs to v1beta1 + add more details about channel based broker
  docs/eventing/broker-trigger.md
  docs/eventing/channel-based-broker.md
  docs/eventing/channels/default-channels.md
Labels: approved, cla: yes, lgtm, size/L

#2256 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2264 Flow v1beta1
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/event-display.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence-reply-to-event-display.png
  docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/steps.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/event-display.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence-reply-to-sequence.png
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml
  docs/eventing/samples/sequence/sequence-terminal/sequence-terminal.png
  docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/cron-source.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/ping-source.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence-with-broker-trigger.png
  docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
Labels: approved, cla: yes, lgtm, size/L

#2268 Eventing API docs for v0.13.0
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
Labels: approved, cla: yes, lgtm, size/XXL

#2270 Rename knative-with-any-k8s for better SEO
  docs/install/README.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2269 Rename Monitoring bundle to Observability plugin.
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#2280 Adopt the builds from knative.dev/net-istio
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2278 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#2126 Make documentation for PingSource.
  docs/eventing/samples/ping-source/README.md
  docs/eventing/samples/ping-source/ping-source.yaml
  docs/eventing/samples/ping-source/service.yaml
Labels: approved, cla: yes, lgtm, size/L

#2286 Add a minishift redirect
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2287 [RELEASE 0.13] Add a minishift redirect
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2250 use lowercase title to be consistent with the rest of the doc
  docs/eventing/accessing-traces.md
  docs/eventing/event-delivery.md
  docs/eventing/event-registry.md
  docs/eventing/getting-started.md
Labels: approved, cla: yes, lgtm, size/XS

#2285 Documenting the Trigger annotation case for the Broker creation
  docs/eventing/channel-based-broker.md
Labels: approved, cla: yes, lgtm, size/M

#2275 Source migrations
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/L

#2274 Updates on the PingSource
  docs/eventing/broker-trigger.md
  docs/eventing/samples/ping-source/README.md
  docs/eventing/samples/ping-source/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/ping-source.yaml
Labels: approved, cla: yes, lgtm, size/M

#2225 CloudEvent version 1.0 and latest log details
  docs/eventing/samples/sinkbinding/README.md
Labels: approved, cla: yes, lgtm, size/S

#2297 :lipstick: adding the SinkBinding bits to the index file as well...
  docs/eventing/migration/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2292 Updated secret creation for private registries
  docs/serving/deploying/private-registry.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2261 Add instruction in how to install Knative with Knative operators
  docs/install/README.md
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#2304 Add instruction in how to install Knative with Knative operators (#2261)
  docs/install/README.md
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#2303 Removing pipe from KafkaChannel spec
  docs/eventing/channel-based-broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2302 Remove the additional title for install knative using operators
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/XS

#2306 Cherry-pick 0.13 migration docs to 0.13 release branch
  docs/eventing/migration/README.md
  docs/eventing/migration/_index.md
  docs/eventing/migration/ping.md
  docs/eventing/migration/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/L

#2310 [RELEASE 0.13] Cherrypick 2126
  docs/eventing/samples/ping-source/README.md
  docs/eventing/samples/ping-source/ping-source.yaml
  docs/eventing/samples/ping-source/service.yaml
Labels: approved, cherrypick-0.13, cla: yes, lgtm, size/L

#2311 Removing pipe from KafkaChannel spec
  docs/eventing/channel-based-broker.md
Labels: approved, cherrypick-0.13, cla: yes, lgtm, needs-ok-to-test, size/XS

#2296 Update Source docs to make the migration from CronJobSource to PingSource more clear.
  docs/eventing/migration/ping.md
  docs/eventing/sources/README.md
  docs/eventing/sources/generator/main.go
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/M

#2307 Redirect cronjob-source to ping-source
  docs/eventing/samples/cronjob-source/README.md
  docs/eventing/samples/cronjob-source/cronjob-source.yaml
  docs/eventing/samples/cronjob-source/service.yaml
  docs/eventing/samples/ping-source/README.md
Labels: approved, cla: yes, lgtm, size/L

#2300 Added go mod init so that docker can build
  docs/serving/samples/cloudevents/cloudevents-go/Dockerfile
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2298 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#2317 Update broker installation doc to include ConfigMapPropagation.
  docs/eventing/channel-based-broker.md
Labels: approved, cla: yes, lgtm, size/M

#2316 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2318 Reorder eventing sections
  docs/eventing/accessing-traces.md
  docs/eventing/broker-trigger.md
  docs/eventing/channel-based-broker.md
  docs/eventing/channels/_index.md
  docs/eventing/debugging/README.md
  docs/eventing/event-delivery.md
  docs/eventing/event-registry.md
  docs/eventing/samples/_index.md
  docs/eventing/sources/README.md
Labels: approved, cla: yes, lgtm, size/S

#2266 update parallel doc to v1beta1
  docs/eventing/samples/parallel/README.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/cron-source.yaml
  docs/eventing/samples/parallel/multiple-branches/event-display.yaml
  docs/eventing/samples/parallel/multiple-branches/parallel.yaml
  docs/eventing/samples/parallel/multiple-branches/ping-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/cron-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/event-display.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml
Labels: approved, cla: yes, lgtm, size/L

#2315 fix the broker configmap example
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/M

#2249 link to each channel documentation instead of the code
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
Labels: approved, cla: yes, lgtm, size/S

#2251 add couchdb source as optional install
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#2284 Remove DNS pain point for new users
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#2291 Fixed indentation of Service YAML in Documentation
  docs/eventing/broker-trigger.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2321 Mt broker
  docs/eventing/mt-channel-based-broker.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/L

#2313 Updated secret sample path
  docs/serving/samples/secrets-go/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2324 Removed broken link in autoscale go sample
  docs/serving/samples/autoscale-go/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2244 Fix doc error about eventing requiring Istio
  docs/install/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2312 Cherry-pick #2296
  docs/eventing/migration/ping.md
  docs/eventing/sources/README.md
  docs/eventing/sources/generator/main.go
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/M

#2322 Updated link to contributor doc because broken
  docs/reference/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2333 Remote references to obsolete knative-ingressgateway.
  docs/serving/debugging-application-issues.md
  docs/serving/samples/knative-routing-go/routing.yaml
  docs/serving/using-external-dns-on-gcp.md
Labels: approved, cla: yes, lgtm, size/S

#2243 Markdown link in using-auto-tls.md is outdated
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2335 Updated image location for container-source
  docs/eventing/samples/container-source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2336 Fix third function image definition
  docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2327 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#2326 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2338 Fixed links for Sequence and Parallel flows pages.
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2231 Add more explicit instruction block about enabling tracing
  docs/serving/accessing-traces.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2331 Document how to install net-http01
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/M

#2342 Updating ContainerSource, Sources list, and migration example
  docs/eventing/README.md
  docs/eventing/migration/README.md
  docs/eventing/migration/sinkbinding.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/container-source/heartbeats-source.yaml
  docs/eventing/samples/sinkbinding/README.md
  docs/eventing/sources/README.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/L

#2356 edit -> patch
  docs/serving/deploying/private-registry.md
Labels: approved, cla: yes, lgtm, size/M
