Repository knative/docs, pull requests merged in 2020-08, with the labels that each got.

#2714 Cleaning up event source docs
  docs/README.md
  docs/eventing/README.md
  docs/eventing/sources/README.md
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, kind/enhancement, kind/eventing, lgtm, lifecycle/active, priority/2, size/L, status/in-progress, triage/needs-eng-input

#2726 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/M

#2697 Add the section to describe the field spec.version
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, size/M

#2729 [release-0.16] Add the section to describe the field spec.version (#2697)
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, size/M

#2720 Add docs for initial scale
  docs/serving/autoscaling/scale-bounds.md
Labels: approved, cla: yes, lgtm, size/M

#2737 Move net-contour to beta
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2736 Add documentation for max-scale global setting
  docs/serving/autoscaling/scale-bounds.md
Labels: approved, cla: yes, lgtm, size/S

#2612 Update installing-istio.md
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, ok-to-test, priority/0, size/XS

#2738 Move net-kourier to beta
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2674 Adding RabbitMQ to Event Source list and change Apache CouchDB link
  docs/eventing/samples/writing-event-source/01-theory.md
  docs/eventing/sources/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS, status/blocked

#2725 Nits in cloudevents samples
  docs/serving/samples/README.md
  docs/serving/samples/cloudevents/cloudevents-rust/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2722 Added Docs related to excluding namespaces from the Knative Webhook
  docs/serving/webhook-customizations.md
Labels: approved, cla: yes, lgtm, size/S

#2626 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/gorilla/context/context.go
  vendor/github.com/gorilla/context/doc.go
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/context_gorilla.go
  vendor/github.com/gorilla/mux/context_native.go
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/docker/cli/cli/config/NOTICE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/go-logr/logr/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/gogo/protobuf/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/google/gofuzz/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/googleapis/gnostic/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/imdario/mergo/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/json-iterator/go/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/modern-go/concurrent/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/modern-go/reflect2/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/github.com/openzipkin/zipkin-go/model/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/go.uber.org/atomic/LICENSE.txt
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/go.uber.org/multierr/LICENSE.txt
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE.txt
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/golang.org/x/sys/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/golang.org/x/time/rate/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/google.golang.org/protobuf/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/gopkg.in/inf.v0/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/k8s.io/apimachinery/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/k8s.io/apimachinery/pkg/util/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/k8s.io/client-go/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/k8s.io/utils/LICENSE
  vendor/knative.dev/test-infra/third_party/VENDOR-LICENSE/knative.dev/pkg/LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#2723 Changed filename from serving.yaml to serving-core.yaml in upgrade docs
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/XS

#2739 Fix rendering issue in helloworld-go eventing
  docs/eventing/samples/helloworld/helloworld-go/README.md
Labels: approved, cla: yes, lgtm, size/L

#2707 Updating Broker docs
  docs/eventing/broker/README.md
  docs/eventing/broker/_index.md
  docs/eventing/broker/config-br-defaults.md
  docs/eventing/broker/kafka-configmap.md
  docs/eventing/broker/mt-channel-based-broker.md
  docs/eventing/samples/helloworld/helloworld-python/README.md
Labels: approved, cla: yes, kind/broker, lgtm, size/L

#2748 Fix URL to net-istio for istio manifest
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2741 update pingsource doc to use v1beta1 API
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/ping-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml
  docs/eventing/samples/ping-source/README.md
  docs/eventing/samples/ping-source/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/ping-source.yaml
  docs/eventing/sources/pingsource.md
Labels: approved, cla: yes, lgtm, size/M

#2735 include doc on how to bring your own certificate with net-contour
  docs/serving/using-a-tls-cert.md
Labels: approved, cla: yes, lgtm, size/M

#2743 Fix rendering issue in helloworld-go eventing for 0.16 branch
  docs/eventing/samples/helloworld/helloworld-go/README.md
Labels: approved, cla: yes, lgtm, size/L

#2572 fix get vsvc in debug app issues
  docs/serving/debugging-application-issues.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2740 Add Apache Kafka Broker
  docs/eventing/broker/alternate/README.md
  docs/eventing/broker/kafka-broker.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/L

#2752 Document all event delivery parameters
  docs/eventing/event-delivery.md
Labels: approved, cla: yes, lgtm, size/XS

#2754 remove spec / annotations so broker uses defaults
  docs/eventing/broker/README.md
Labels: approved, cla: yes, lgtm, size/S

#2756 add an explicit Broker creation not relying on defaults
  docs/eventing/broker/README.md
Labels: approved, cla: yes, lgtm, size/M

#2758 fix broker url in eventing getting-started.md
  docs/eventing/getting-started.md
Labels: approved, cla: yes, lgtm, size/S

#2760 Deliver events to a particular path of a Trigger subscriber
  docs/eventing/triggers/README.md
Labels: approved, cla: yes, lgtm, size/S

#2650 Add multi-tenant GitHub source installation doc
  docs/eventing/samples/github-source/README.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/M

#2763 build API docs for 0.17
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, kind/api, kind/eventing, kind/eventing-contrib, kind/serving, lgtm, size/XXL

#2783 Remove redundant paragraph in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2778 Update the stale content of configuring TLS of Istio Gateway
  docs/serving/using-a-tls-cert.md
Labels: approved, cla: yes, lgtm, size/S
