Repository knative/docs, pull requests merged in 2020-07, with the labels that each got.

#2621 Update the HA component list.
  docs/serving/config-ha.md
Labels: approved, cla: yes, lgtm, size/S

#2630 messaging v1beta1->v1
  docs/eventing/README.md
  docs/eventing/broker/mt-channel-based-broker.md
  docs/eventing/channels/default-channels.md
  docs/eventing/debugging/README.md
  docs/eventing/debugging/example.yaml
  docs/eventing/event-delivery.md
  docs/eventing/event-registry.md
  docs/eventing/flows/sequence.md
  docs/eventing/samples/apache-camel-source/display_resources.yaml
  docs/eventing/samples/apache-camel-source/source_http_poller.yaml
  docs/eventing/samples/apache-camel-source/source_mqtt.yaml
  docs/eventing/samples/apache-camel-source/source_telegram.yaml
  docs/eventing/samples/apache-camel-source/source_timer.yaml
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/parallel.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/parallel.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
  docs/eventing/samples/sinkbinding/README.md
Labels: approved, cla: yes, lgtm, size/M

#2634 add a blurp about install vs. upgrade
  docs/install/README.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2635 update install instructions remove channel based broker
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/M

#2629 Quote the author so it parses correctly.
  blog/articles/get-started-knative-eventing.md
Labels: approved, cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#2625 Updates to reflect the v1beta shape of the KafkaSource
  docs/eventing/event-registry.md
  docs/eventing/samples/kafka/binding/README.md
  docs/eventing/samples/kafka/binding/event-binding.yaml
  docs/eventing/samples/kafka/binding/event-source.yaml
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kafka/source/event-source.yaml
Labels: approved, cla: yes, lgtm, size/S

#2638 serving->eventing
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2639 make sure all triggers have spec.broker
  docs/eventing/broker/README.md
  docs/eventing/getting-started.md
  docs/eventing/samples/iot-core/trigger.yaml
  docs/eventing/samples/kafka/channel/030-trigger.yaml
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cla: yes, lgtm, size/S

#2627 Removed outdated sample
  docs/serving/samples/rest-api-go/stock.go
Labels: approved, cla: yes, lgtm, size/M

#2637 Correct the format for yaml rendering
  docs/serving/using-a-tls-cert.md
Labels: approved, cla: yes, lgtm, size/XS

#2640 update upgrade instructions for pre/post install.
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/M

#2642 clean up the broker docs, separate broker defaults
  docs/eventing/broker/README.md
  docs/eventing/broker/defaults-br-config.md
  docs/eventing/broker/mt-channel-based-broker.md
Labels: approved, cla: yes, lgtm, size/L

#2647 Document installing Eventing Sugar Controller
  docs/eventing/getting-started.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XXL

#2649 remove parallel installation instructions
  docs/eventing/getting-started.md
Labels: approved, cla: yes, lgtm, size/M

#2614 [release-0.15] Add the missing section of "Installing Istio without sidecar injection"
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#2651 update few usages of v1alpha1/v1beta1 to v1
  docs/eventing/getting-started.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2230 Improve "Installing the Knative CLI"
  docs/install/install-kn.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2566 Add 2020-05-14 – Knative Community Meetup #2
  community/meetup/README.md
Labels: approved, cla: yes, lgtm, size/M

#2546 [BLOG] Set up a local Knative environment up in no time flat
  blog/articles/set-up-a-local-knative-environment-with-kind.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2656 updated api docs for v0.16.0
  docs/reference/eventing/eventing-contrib.md
  docs/reference/eventing/eventing.md
  docs/reference/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#2645 Update KafkaChannel examples to use v1beta1
  docs/eventing/broker/mt-channel-based-broker.md
  docs/eventing/channels/default-channels.md
  docs/eventing/samples/kafka/channel/README.md
  docs/install/operator/configuring-eventing-cr.md
Labels: approved, cla: yes, lgtm, size/S

#2652 Removing sugar annotation from samples.
  docs/eventing/samples/helloworld/helloworld-go/README.md
  docs/eventing/samples/helloworld/helloworld-go/sample-app.yaml
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
Labels: approved, cla: yes, lgtm, size/L

#2633 update flows samples to use v1 API
  docs/eventing/README.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/parallel.yaml
  docs/eventing/samples/parallel/multiple-branches/ping-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/sequence.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/ping-source.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence1.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/sequence2.yaml
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/ping-source.yaml
  docs/eventing/samples/sequence/sequence-terminal/sequence.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/sequence.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/trigger.yaml
Labels: approved, cla: yes, lgtm, size/L

#2666 Remove Eventing requires Serving
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2667 Remove Eventing requires Serving
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2598 Create event-driven-image-bigquery-processing-pipelines.md
  blog/articles/event-driven-image-bigquery-processing-pipelines.md
Labels: approved, cla: yes, kind/broker, kind/eventing, kind/new-docs-needed, kind/sample, lgtm, ok-to-test, priority/1, size/L

#2653 Fix the doc for eventing as yaml files are renamed
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/XS

#2617 Sample for tag header based routing
  docs/serving/samples/tag-header-based-routing/README.md
  docs/serving/samples/tag-header-based-routing/index.md
  docs/serving/samples/tag-header-based-routing/sample.yaml
Labels: approved, cherrypick-0.16, cla: yes, lgtm, size/L

#2662 Clean up eventing docs
  docs/eventing/getting-started.md
Labels: approved, cla: yes, lgtm, size/XL

#2672 [release-0.16] update doc to reflect migration job changes
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/XS

#2671 update doc to reflect migration job changes
  docs/install/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/XS

#2613 Add the missing section of "Installing Istio without sidecar injection"
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/XS

#2679 Update last of knative/net-* references to use knative-sandbox
  blog/articles/set-up-a-local-knative-environment-with-kind.md
  docs/install/any-kubernetes-cluster.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/XS

#2673 Update SinkBinding example to v1beta1
  docs/eventing/samples/sinkbinding/README.md
  docs/eventing/samples/sinkbinding/sinkbinding.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2683 Remove warning about activator load balancing behaviour
  docs/serving/autoscaling/concurrency.md
Labels: approved, cla: yes, lgtm, size/XS

#2685 Fix dry-run flag name
  docs/serving/feature-flags.md
Labels: approved, cla: yes, lgtm, size/XS

#2686 Cherrypick dryrun docs change
  docs/serving/feature-flags.md
Labels: approved, cla: yes, lgtm, size/XS

#2670 Rename Broker defaults-br-config and clarify Broker defaulting
  docs/eventing/broker/README.md
  docs/eventing/broker/config-br-defaults.md
Labels: approved, cla: yes, lgtm, size/M

#2688 updating ApiServerSource example to use v1beta1
  docs/eventing/debugging/README.md
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2615 Update the local cluster gateway link
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, size/XS

#2691 Simplify the HA documentation.
  docs/serving/config-ha.md
Labels: approved, cla: yes, lgtm, size/M

#2693 fix cm name + talk about using different channel
  docs/eventing/broker/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2690 Update ContainerSource example to use v1beta1
  docs/eventing/migration/sinkbinding.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/container-source/heartbeats-source.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2694 Use github actions/stale for managing stale issues/PRs
  .github/workflows/stale.yaml
Labels: approved, cla: yes, lgtm, size/M

#2695 typos in kafka source
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2696 Update docs to fix broken link
  docs/serving/knative-kubernetes-services.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2676 Fixes #2675 The channel-broker.yaml doesn't exist anymore but it stil…
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2698 Update the cm name, ChannelBasedBroker -> MTChannelBasedBroker
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2701 Fix K_CE_OVERRIDES env var format
  docs/eventing/samples/sinkbinding/README.md
Labels: approved, cherrypick-0.16, cla: yes, lgtm, size/XS

#2700 Update Ambassador install instructions
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2682 Document how to set default for containerConcurrency
  docs/serving/autoscaling/concurrency.md
Labels: approved, cla: yes, lgtm, size/M

#2090 Update the instruction on how to use cluster local gateway
  docs/install/installing-istio.md
  docs/serving/setting-up-custom-ingress-gateway.md
Labels: approved, cla: yes, lgtm, size/M

#2680 revamp eventing sources page
  docs/eventing/sources/README.md
  docs/eventing/sources/_index.md
  docs/eventing/sources/generator/ReadmeTemplate.gomd
  docs/eventing/sources/generator/main.go
  docs/eventing/sources/pingsource.md
  docs/eventing/sources/sources.yaml
Labels: approved, cla: yes, lgtm, size/XL

#2703 fix link to ref doc
  docs/eventing/sources/pingsource.md
Labels: approved, cla: yes, lgtm, size/XS

#2299 Added Python Example for Knative Eventing
  docs/eventing/samples/helloworld/helloworld-python/Dockerfile
  docs/eventing/samples/helloworld/helloworld-python/README.md
  docs/eventing/samples/helloworld/helloworld-python/_index.md
  docs/eventing/samples/helloworld/helloworld-python/helloworld.py
  docs/eventing/samples/helloworld/helloworld-python/requirements.txt
  docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2711 move to k8s v1.16
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#2708 Update APIServerSource docs to include the new attributes in CloudEvents
  docs/eventing/samples/helloworld/helloworld-python/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
Labels: approved, cla: yes, lgtm, size/S

#2710 Label to k8s service instead of route
  docs/serving/cluster-local-route.md
Labels: approved, cla: yes, lgtm, size/XS

#2713 Add source docs for ContainerSource, APIServerSource and SinkBinding
  docs/eventing/sources/README.md
  docs/eventing/sources/apiserversource.md
  docs/eventing/sources/containersource.md
  docs/eventing/sources/pingsource.md
  docs/eventing/sources/sinkbinding.md
Labels: approved, cla: yes, lgtm, size/XL

#2716 Fix the broken E2E tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2644 Enable grpc server reflection for grpc-ping example
  docs/serving/samples/grpc-ping-go/grpc-ping.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/serverreflection.go
Labels: approved, cla: yes, lgtm, size/XXL

#2719 Fix missing hyphen in eventing getting started guide
  docs/eventing/getting-started.md
Labels: approved, cla: yes, kind/bug, lgtm, size/XS
