Repository knative/docs, pull requests merged in 2021-01, with the labels that each got.

#3119 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3110 Fixed a typo.
  docs/eventing/samples/container-source/README.md
  docs/eventing/sources/containersource.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3126 Update any-kubernetes-cluster.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3084 Update eventing/samples/writing-event-source-easy..README.md
  docs/eventing/samples/writing-event-source-easy-way/README.md
Labels: approved, cherrypick-0.19, cla: yes, lgtm, size/XS

#3128 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3136 update package, fix issue 3135
  docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
  docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json
  docs/serving/samples/cloudevents/cloudevents-nodejs/package.json
  docs/serving/samples/cloudevents/cloudevents-nodejs/service.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#3137 Fixing yaml format
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, size/XS

#3125 Update README.md
  docs/eventing/samples/kafka/binding/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3127 Update calendar and drive links
  CONTRIBUTING.md
  community/calendar/_index.md
  community/meetup/README.md
  docs/eventing/samples/writing-event-source/01-theory.md
  docs/reference/api/serving.md
  docs/serving/tag-resolution.md
Labels: approved, cla: yes, lgtm, size/S

#3132 Update README.md
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3139 Adding updates to the Event registry doc
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, size/XS

#3141 Knative API docs for v0.20.0
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
  hack/gen-api-reference-docs.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#3094 Update 06-yaml.md
  docs/eventing/samples/writing-event-source/06-yaml.md
Labels: approved, cla: yes, lgtm, size/XS

#2559 Add load balancing docs
  docs/serving/autoscaling/target-burst-capacity.md
  docs/serving/load-balancing/_index.md
  docs/serving/load-balancing/target-burst-capacity.md
Labels: approved, cla: yes, lgtm, size/L

#3148 Use the new constant in the docs
  docs/serving/cluster-local-route.md
  docs/serving/using-subroutes.md
Labels: approved, cla: yes, lgtm, size/S

#3153 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3149 Add vagababov to eng-approvers and sort and trim people not longer in Knative project
  OWNERS_ALIASES
  docs/serving/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#3160 fix apache kafka broken link #3159
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3146 add kafka installation
  docs/eventing/broker/kafka-broker.md
Labels: approved, cla: yes, lgtm, size/XS

#3167 Promote net-kourier to stable
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3151 Use inline Istio installation.
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3171 Fix the cluster-local docs to be consistent
  docs/serving/cluster-local-route.md
Labels: approved, cla: yes, lgtm, size/S

#3173 update gen-api-reference-docs script
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
  hack/gen-api-reference-docs.sh
Labels: approved, cla: yes, lgtm, size/XXL

#3157 Release blog post for Knative v0.20
  blog/releases/announcing-knative-v0-20-release.md
Labels: approved, cla: yes, lgtm, size/L

#3017 Add DomainMapping docs
  docs/serving/creating-domain-mappings.md
Labels: approved, cherrypick-0.19, cla: yes, kind/serving, lgtm, size/M

#3176 Cherry pick mTLS docs from 0.19 onto 0.20
  docs/serving/images/architecture.png
  docs/serving/istio-authorization.md
Labels: approved, cla: yes, lgtm, size/M

#3170 Update k8s minimum version in (docs/install/any-kubernetes-cluster.md)
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3185 Clarify how to cherry-pick the PR
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#3131 Update knative-kubernetes-services.md
  docs/serving/knative-kubernetes-services.md
Labels: approved, cla: yes, lgtm, size/XS

#3188 Rebase of 3147
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
  hack/gen-api-reference-docs.sh
  hack/patches/serving.patch
Labels: approved, cla: yes, lgtm, size/XL

#3189 Autoscaler can be scaled too now. Add correct docs for activator
  docs/serving/config-ha.md
Labels: approved, cla: yes, lgtm, size/M

#3187 Using proper VERSION var for istio example
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/XS

#3181 Describe new ce-knativedispatcherr cloudevent extension attribute
  docs/eventing/channels/channels-crds.md
  docs/eventing/event-delivery.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#3193 Update README.md
  docs/eventing/samples/kafka/binding/README.md
Labels: approved, cla: yes, lgtm, size/XS

#3158 remove prometheus component
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#3192 HA is enabled for Autoscaler too
  docs/serving/config-ha.md
Labels: approved, cla: yes, lgtm, size/XS

#3152 Cherry pick a few commits that were erroneously made directly into release-0.19
  docs/install/installing-istio.md
  docs/serving/images/architecture.png
  docs/serving/istio-authorization.md
Labels: approved, cla: yes, lgtm, size/M

#2854 Issue 2755 - Troubleshooting PRs
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#3138 Add .gitattributes for docs
  .gitattributes
Labels: approved, cla: yes, lgtm, size/S

#3197 [#3196] cleaning up introduction docs
  docs/README.md
  docs/_index.md
  docs/concepts/_index.md
  docs/concepts/overview.md
Labels: approved, cla: yes, lgtm, size/L

#3198 Add readfile to Knative multi-container samples
  docs/serving/samples/multi-container/index.md
Labels: approved, cla: yes, lgtm, size/XS

#3191 [#3085] Enhance PingSource example with kn
  docs/eventing/samples/ping-source/index.md
Labels: approved, cla: yes, lgtm, size/M

#3130 fix broken link
  docs/eventing/sink/README.md
  docs/eventing/sink/_index.md
Labels: approved, cla: yes, lgtm, size/M

#3155 fix: change PingSource api version badge to v1beta2
  docs/eventing/sources/pingsource.md
Labels: approved, cla: yes, lgtm, size/XS
