Repository knative/docs, pull requests merged in 2021-11, with the labels that each got.

#4409 Make blog distinct again
  blog/config/nav.yml
  config/nav.yml
  docs/stylesheets/extra.css
Labels: lgtm, size/S, cla: yes, approved

#4407 sc 2021 blogpost
  blog/docs/articles/steering-elections-2021.md
Labels: size/M, lgtm, cla: yes, approved

#4412 Removing duplicate blog tab
  config/nav.yml
Labels: size/XS, lgtm, cla: yes, approved

#4406 Case studies
  blog/config/nav.yml
  config/nav.yml
  docs/about/case-studies/deepc.md
  docs/about/case-studies/outfit7.md
  docs/about/case-studies/puppet.md
  docs/images/case-studies/deepc.png
  docs/images/case-studies/outfit7.png
  docs/images/case-studies/puppet.png
  docs/stylesheets/extra.css
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: size/L, lgtm, cla: yes, approved

#4411 Updating website tabs in 0.26 release
  config/nav.yml
  docs/stylesheets/extra.css
Labels: size/XS, lgtm, cla: yes, approved

#4414 Fix rendering glitch
  docs/about/case-studies/deepc.md
  docs/about/case-studies/outfit7.md
  docs/about/case-studies/puppet.md
Labels: size/XS, lgtm, cla: yes, approved

#4413 Updates blog tabs to match redesign
  blog/config/nav.yml
  blog/docs/steering/steering-elections-2021.md
  config/nav.yml
Labels: lgtm, size/S, cla: yes, approved

#4415 fix small typo in case studies
  docs/about/case-studies/outfit7.md
Labels: size/XS, lgtm, cla: yes, approved

#4402 1.0 BlogPost
  blog/config/nav.yml
  blog/docs/articles/knative-1.0.md
  blog/docs/images/1.0Banner.jpg
  blog/docs/index.md
  docs/stylesheets/extra.css
  overrides/main.html
Labels: size/M, lgtm, cla: yes, approved

#4410 Update docs for serving/pull/12174
  docs/install/serving/install-serving-with-yaml.md
  docs/install/serving/serving-installation-files.md
  docs/install/uninstall.md
  docs/serving/using-auto-tls.md
Labels: size/M, lgtm, cla: yes, approved

#4418 cut docs for Knative 1.0 GA
  hack/build.sh
Labels: lgtm, size/S, cla: yes, approved

#4431 removes redundant redirects
  config/redirects.yml
Labels: size/XS, lgtm, cla: yes, approved

#4401 Document contentMode for KafkaSink
  docs/eventing/sinks/kafka-sink.md
Labels: size/M, lgtm, cla: yes, approved

#4405 Added SNMP and Direktiv source
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4421 Update puppet.md - fix wording
  docs/about/case-studies/puppet.md
Labels: size/XS, lgtm, cla: yes, approved

#4422 Update puppet.md - fix grammar
  docs/about/case-studies/puppet.md
Labels: size/XS, lgtm, cla: yes, approved

#4425 Update mkdocs-contributor-guide.md
  docs/help/contributor/mkdocs-contributor-guide.md
Labels: size/XS, lgtm, cla: yes, approved

#4432 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, cla: yes, approved

#4403 Add entry for flag documentation
  docs/help/contributor/style-guide/documenting-code.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4426 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size/XS, lgtm, cla: yes, approved

#4428 update mkdocs.yml in blog
  blog/mkdocs.yml
Labels: size/XS, lgtm, cla: yes, approved

#4434 fix redirect loop
  config/redirects.yml
Labels: size/XS, lgtm, cla: yes, approved, needs-cherry-pick

#4391 Adding command-line instructions for using cloudevents player
  docs/getting-started/first-source.md
Labels: lgtm, size/S, cla: yes, approved

#4336 Edit event registry docs
  config/nav.yml
  docs/eventing/event-registry.md
Labels: size/L, lgtm, cla: yes, approved

#4442 Adding c-suite blog post
  blog/config/nav.yml
  blog/docs/articles/highlighting-value-knative-c-suite.md
  blog/docs/index.md
Labels: size/L, lgtm, cla: yes, approved

#4443 Remove oudated overview page
  docs/eventing/README.md
  docs/eventing/broker.svg
  docs/eventing/channel.svg
  docs/eventing/developer-overview.md
Labels: size/L, lgtm, cla: yes, kind/eventing, kind/cleanup, approved

#4448 Update administrator button on homepage
  overrides/home.html
Labels: size/XS, lgtm, cla: yes, approved

#4454 Change the format of the section of installing eventing sources
  docs/install/operator/knative-with-operators.md
Labels: size/L, lgtm, cla: yes, approved

#4452 add release notes for v1.0
  blog/config/nav.yml
  blog/docs/releases/announcing-knative-v1-0-release.md
Labels: size/L, lgtm, cla: yes, approved

#4455 Grammar fix
  hack/docker/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4457 Remove outdated RESTful example page
  config/nav.yml
  docs/serving/samples/README.md
  docs/serving/samples/rest-api-go/Dockerfile
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/rest-api-go/sample-template.yaml
  docs/serving/samples/rest-api-go/sample.yaml
Labels: size/L, lgtm, cla: yes, approved

#4463 update outfit7 as requested by them via email
  docs/images/case-studies/outfit7.png
Labels: size/XS, lgtm, cla: yes, approved

#4465 Blog: fix code-samples nav link
  blog/config/nav.yml
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4461 Renaming "Overview" pages to be more specific
  config/nav.yml
  mkdocs.yml
Labels: size/M, lgtm, cla: yes, approved

#4466 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/M, lgtm, cla: yes, approved

#4458 Add Activator capacity to navigation
  config/nav.yml
Labels: size/XS, lgtm, cla: yes, approved

#4467 Fix sample output
  docs/install/operator/knative-with-operators.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4445 Fixed few broken cloudevents links in the documentation
  archived/v0.23-docs/eventing/broker/index.xml
  archived/v0.23-docs/eventing/broker/kafka-broker/index.html
  archived/v0.23-docs/eventing/event-registry/index.html
  archived/v0.23-docs/eventing/index.html
  archived/v0.23-docs/eventing/index.xml
  archived/v0.23-docs/eventing/samples/container-source/index.html
  archived/v0.23-docs/eventing/samples/index.xml
  archived/v0.23-docs/eventing/samples/writing-event-source/index.xml
  archived/v0.23-docs/eventing/sources/creating-event-sources/writing-event-source/01-theory/index.html
  archived/v0.23-docs/eventing/sources/creating-event-sources/writing-event-source/index.xml
  docs/eventing/broker/kafka-broker/README.md
  docs/eventing/event-registry.md
  docs/eventing/sinks/kafka-sink.md
  docs/getting-started/first-broker.md
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
Labels: size/M, lgtm, cla: yes, ok-to-test, approved

#4474 Fix link to collector.yaml
  docs/snippets/collecting-metrics.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4408 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, lgtm, cla: yes, approved

#4472 Update Knative Sources README.md
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4483 Fix Kafka Channel yaml
  docs/eventing/samples/kafka/channel/README.md
Labels: kind/bug, size/XS, lgtm, cla: yes, ok-to-test, approved

#4481 Switch to snake-casing for config map properties
  docs/install/serving/install-serving-with-yaml.md
  docs/serving/configuration/deployment.md
  docs/serving/configuration/rolling-out-latest-revision-configmap.md
  docs/serving/samples/knative-routing-go/README.md
  docs/serving/samples/kong-routing-go/README.md
  docs/serving/services/certificate-class.md
  docs/serving/services/custom-domains.md
  docs/serving/services/http-option.md
  docs/serving/services/ingress-class.md
  docs/serving/using-a-tls-cert.md
  docs/serving/using-auto-tls.md
Labels: size/L, lgtm, cla: yes, approved

#4492 Update links to docs of TriggerMesh sources
  docs/eventing/sources/README.md
Labels: size/M, lgtm, cla: yes, approved

#4494 [release-1.0] Update links to docs of TriggerMesh sources
  docs/eventing/sources/README.md
Labels: size/M, lgtm, cla: yes, ok-to-test, approved

#4493 Fix capitalization of TriggerMesh in blog post
  blog/docs/articles/highlighting-value-knative-c-suite.md
Labels: size/XS, lgtm, cla: yes, approved

#4499 Adding a note on messaging ordering for Kafkas
  docs/eventing/channels/channel-types-defaults.md
  docs/eventing/sources/kafka-source/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4497 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/S, cla: yes, approved

#4500 Correct the link of fluent-bit-collector.yaml
  docs/snippets/collecting-logs.md
Labels: size/XS, lgtm, cla: yes, approved

#4503 Remove navigation.indexes
  mkdocs.yml
Labels: size/XS, lgtm, cla: yes, approved

#4464 Github Action to build docker image of knative mkdocs
  .github/workflows/knative-mkdocs-dockerimage.yaml
Labels: size/M, lgtm, cla: yes, approved

#4495 Add documentation about minikube quickstart
  docs/getting-started/README.md
  docs/snippets/quickstart-install.md
Labels: size/M, lgtm, cla: yes, ok-to-test, approved

#4510 Use `redirected` instead of `enabled` in the HTTPS redirection example
  docs/serving/services/http-option.md
Labels: size/XS, lgtm, cla: yes, approved

#4509 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, cla: yes, approved

#4508 Update ContainerSource README.md
  docs/eventing/custom-event-source/containersource/README.md
Labels: lgtm, size/S, cla: yes, approved

#4512 Update notes formatting
  docs/eventing/broker/create-mtbroker.md
  docs/eventing/broker/kafka-broker/README.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/configuration/channel-configuration.md
  docs/eventing/flows/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/sources/apache-camel-source/README.md
  docs/eventing/sugar/README.md
  docs/install/client/README.md
  docs/install/operator/configuring-eventing-cr.md
  docs/install/serving/installing-istio.md
  docs/serving/autoscaling/scale-bounds.md
  docs/serving/configuration/config-defaults.md
  docs/serving/load-balancing/README.md
  docs/serving/troubleshooting/debugging-application-issues.md
  docs/serving/using-auto-tls.md
  docs/snippets/install-kn.md
Labels: size/L, lgtm, cla: yes, approved

#4486 Move and cleanup autoscaling docs
  config/nav.yml
  docs/serving/autoscaling/README.md
Labels: size/M, lgtm, cla: yes, approved

#4513 Fix istio installation doc
  docs/install/serving/installing-istio.md
Labels: size/M, lgtm, cla: yes, approved

#4519 Fix all links to nightly releases
  hack/macros.py
Labels: size/XS, lgtm, cla: yes, approved

#4517 update examples to use kebab case
  config/nav.yml
  config/redirects.yml
  docs/getting-started/first-source.md
  docs/install/operator/knative-with-operators.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/autoscaling/concurrency.md
  docs/serving/autoscaling/kpa-specific.md
  docs/serving/autoscaling/scale-bounds.md
  docs/serving/autoscaling/scale-to-zero.md
  docs/serving/configuration/rolling-out-latest-revision-configmap.md
  docs/serving/load-balancing/README.md
  docs/serving/load-balancing/activator-capacity.md
  docs/serving/load-balancing/target-burst-capacity.md
  docs/serving/rolling-out-latest-revision.md
  docs/serving/services/certificate-class.md
  docs/serving/services/http-protocol.md
  docs/serving/services/ingress-class.md
  docs/serving/using-auto-tls.md
Labels: size/L, lgtm, cla: yes, approved

#4527 create knative-cncf-donation.md
  blog/docs/steering/knative-cncf-donation.md
Labels: size/M, lgtm, cla: yes, approved

#4528 Update nav.yml
  blog/config/nav.yml
Labels: size/XS, lgtm, cla: yes, approved

#4489 Reorganise docs contributor guide
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  config/redirects.yml
  contribute-to-docs/README.md
  contribute-to-docs/getting-started/README.md
  contribute-to-docs/getting-started/becoming-a-contributor.md
  contribute-to-docs/getting-started/branches-and-cherrypicking.md
  contribute-to-docs/getting-started/formatting.md
  contribute-to-docs/getting-started/github-workflow.md
  contribute-to-docs/getting-started/navigation-and-redirects.md
  contribute-to-docs/getting-started/previewing-docs-locally.md
  contribute-to-docs/images/annotated-procedure-topic.png
  contribute-to-docs/images/nav-backend.png
  contribute-to-docs/images/nav-frontend.png
  contribute-to-docs/style-guide/README.md
  contribute-to-docs/style-guide/content-reuse.md
  contribute-to-docs/style-guide/documenting-code.md
  contribute-to-docs/style-guide/style-and-formatting.md
  contribute-to-docs/style-guide/voice-and-language.md
  contribute-to-docs/style-guide/word-and-phrase-list.md
  contribute-to-docs/templates/README.md
  contribute-to-docs/templates/template-blog-entry.md
  contribute-to-docs/templates/template-concept.md
  contribute-to-docs/templates/template-procedure.md
  contribute-to-docs/templates/template-troubleshooting.md
  contribute-to-docs/what-to-contribute/README.md
  contribute-to-docs/what-to-contribute/creating-blog-posts.md
  contribute-to-docs/what-to-contribute/creating-code-samples.md
  contribute-to-docs/what-to-contribute/creating-new-docs.md
  docs/help/contributor/README.md
  docs/help/contributor/mkdocs-contributor-guide.md
  docs/help/contributor/structure.md
  overrides/home.html
Labels: lgtm, size/XXL, cla: yes, approved

#4529 updates for cncf blog
  blog/docs/images/knative-cncf.png
  blog/docs/steering/knative-cncf-donation.md
  blog/docs/steering/steering-elections-2021.md
Labels: size/M, lgtm, cla: yes, approved
