Repository knative/docs, pull requests merged in 2021-03, with the labels that each got.

#3290 Minor update to OpenShift docs link
  docs/knative-offerings.md
Labels: approved, cherrypick-0.18, cherrypick-0.19, cherrypick-0.20, cherrypick-0.21, cla: yes, lgtm, size/XS

#3292 Minor update to OpenShift docs link
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#3295 New contrib
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#3272 Add new operator config spec.deployments to override configuration of system deployment
  docs/install/operator/configuring-serving-cr.md
Labels: approved, cla: yes, lgtm, size/S

#3297 Cleanup install docs
  docs/install/README.md
  docs/install/_index.md
  docs/install/any-kubernetes-cluster.md
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#3305 Follow up install doc improvements
  docs/install/_index.md
  docs/install/any-kubernetes-cluster.md
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/L

#3289 Remove note about cluster-local-gateway and istio-knative-extras.yaml
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3301 Modify the instructions of the ingress configuration
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/S

#3307 Fix link and minor improvements to doc
  docs/eventing/event-registry.md
Labels: approved, cla: yes, kind/cleanup, kind/eventing, lgtm, size/M

#3296 Add description table for install files for Knative Serving
  docs/install/assets/serving.md
Labels: approved, cla: yes, lgtm, size/S

#3302 Clean up and add to CLI docs
  docs/client/_index.md
  docs/client/connecting-kn-to-your-cluster.md
  docs/client/install-kn.md
  docs/install/install-kn.md
  docs/reference/resources.md
Labels: approved, cla: yes, lgtm, size/L

#3304 Add table for eventing assets (#1896)
  docs/install/assets/eventing.md
Labels: approved, cla: yes, lgtm, size/S

#3317 Put command under steps
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/S

#2884 Added examples for kn usage for the Ruby sample app
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-ruby/index.md
Labels: approved, cla: yes, lgtm, size/L

#3293 Minor update to OpenShift docs link
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#3294 Minor update to OpenShift docs link
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#3308 [release-0.21] Modify the instructions of the ingress configuration
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/S

#3059 [0.18] Document Apache Kafka Sink (#3031)
  docs/eventing/sink/OWNERS
  docs/eventing/sink/_index.md
  docs/eventing/sink/kafka-sink.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/L

#2911 Added examples of kn usage for the PHP sample app
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-php/index.md
  docs/serving/samples/hello-world/helloworld-php/index.php
Labels: approved, cla: yes, lgtm, size/L, status/blocked

#3327 fix kafka sample, the yaml should indent spaces in TLS KafkaSource sa…
  docs/eventing/samples/kafka/source/README.md
Labels: approved, cla: yes, lgtm, size/S

#3306 Add Subscription docs with kn commands
  docs/eventing/_index.md
  docs/eventing/channels/_index.md
  docs/eventing/channels/subscriptions.md
  docs/eventing/triggers/README.md
  docs/eventing/triggers/_index.md
Labels: approved, cla: yes, kind/cli, kind/eventing, lgtm, size/L, triage/needs-eng-input

#3333 Drop unnecessary occurrences of master
  .github/pull-request-template.md
  CONTRIBUTING.md
  README.md
  blog/README.md
  blog/releases/announcing-knative-v0-17-release.md
  blog/releases/announcing-knative-v0-18-release.md
  blog/releases/announcing-knative-v0-19-release.md
  blog/releases/announcing-knative-v0-21-release.md
  blog/steering/2020-01-annual-report-2019.md
  blog/steering/2020-11-ksc-elections.md
  blog/steering/governance-changes.md
  community/annual_reports/README.md
  community/meetup/README.md
  community/samples/README.md
  community/samples/serving/helloworld-java-quarkus/README.md
  doc-releases.md
  docs/eventing/README.md
  docs/eventing/accessing-traces.md
  docs/eventing/broker/README.md
  docs/eventing/broker/alternate/README.md
  docs/eventing/debugging/README.md
  docs/eventing/event-registry.md
  docs/eventing/getting-started.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/helloworld/helloworld-go/README.md
  docs/eventing/samples/kafka/binding/README.md
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/writing-event-source-easy-way/README.md
  docs/eventing/samples/writing-event-source/01-theory.md
  docs/eventing/samples/writing-event-source/04-reconciler.md
  docs/eventing/sink/README.md
  docs/eventing/sources/_index.md
  docs/eventing/sources/sinkbinding.md
  docs/install/any-kubernetes-cluster.md
  docs/install/collecting-logs/README.md
  docs/reference/api/README.md
  docs/reference/api/serving.md
  docs/serving/README.md
  docs/serving/accessing-traces.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/debugging-application-issues.md
  docs/serving/getting-started-knative-app.md
  docs/serving/knative-kubernetes-services.md
  docs/serving/services/creating-services.md
  docs/serving/spec/knative-api-specification-1.0.md
  docs/serving/using-a-custom-domain-per-service.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-auto-tls.md
  docs/smoketest.md
  hack/patches/serving.patch
  smoketest.md
Labels: approved, cla: yes, lgtm, size/L

#3341 New blog template and update doc template
  .github/pull-request-template.md
  README.md
  new-page-template.md
  template-blog-entry.md
  template-docs-page.md
Labels: approved, cla: yes, lgtm, size/XL

#3343 Fix obsolete links in debugging guide
  docs/serving/debugging-application-issues.md
Labels: approved, cla: yes, lgtm, size/XS

#3347 Fixed comments and moved verification step
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/M

#3314 Update Rust version and installation commands
  community/samples/serving/helloworld-rust/Dockerfile
Labels: approved, cla: yes, kind/serving, lgtm, ok-to-test, size/XS, triage/needs-eng-input

#3340 Update Dart example for latest stable SDK
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-dart/bin/server.dart
  community/samples/serving/helloworld-dart/pubspec.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3021 inline ping-source's README.md into index.md (#2964)
  docs/eventing/samples/ping-source/README.md
  docs/eventing/samples/ping-source/index.md
Labels: approved, cla: yes, lgtm, size/L

#3348 Add a note on replication factor value
  docs/eventing/broker/kafka-broker.md
Labels: approved, cla: yes, lgtm, size/XS

#3318 Removed the Go code link
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3281 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#3324 Removed the Go path link from the ./eventing/sources/_index.md
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#3358 Update knative-offerings.md
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#2895 Added examples of kn usage for the Scala sample app
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-scala/index.md
Labels: approved, cla: yes, lgtm, size/L

#3005 Add documentation on how to use OpenTelemetry +collector
  docs/install/collecting-metrics/_index.md
  docs/install/collecting-metrics/collector.yaml
  docs/install/collecting-metrics/prometheus.yaml
  docs/install/collecting-metrics/system-diagram.svg
Labels: approved, cla: yes, lgtm, size/L, status/blocked, triage/needs-eng-input

#3321 Removed the Go path link from the ./eventing/event-delivery.md
  docs/eventing/event-delivery.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#3323 Removed the Go path link from the ./eventing/debugging/README.md
  docs/eventing/debugging/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3026 Add events to Cloud Run for Anthos description
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#3342 [Automated] Fix misspellings
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/XS

#3319 Removed the Go path link from the ./eventing/README.md
  docs/eventing/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3356 Add clarifying info about what to install
  docs/install/any-kubernetes-cluster.md
  docs/install/knative-with-operators.md
Labels: approved, cla: yes, lgtm, size/XS

#3330 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3354 Hide CONTRIBUTING.md from the website
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#3331 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/install-istio.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-ci-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-ci-no-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-kind-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-kind-no-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-minimal.yaml
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3357 Remote serving API spec and point to new location in specs repo
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, lgtm, size/XXL

#3380 Added the link to run website locally from our README to our DEVELOPMENT
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#3334 Add reference page for custom install
  docs/install/any-kubernetes-cluster.md
  docs/install/assets/eventing.md
  docs/install/assets/serving.md
  docs/install/installation-files.md
Labels: approved, cla: yes, lgtm, size/M

#3385 Use a unique name for the scale-to-zero-retention tabs
  docs/serving/autoscaling/scale-to-zero.md
Labels: approved, cherrypick-0.19, cherrypick-0.20, cherrypick-0.21, cla: yes, lgtm, size/XS

#3390 Fix broken link and tweak wording
  docs/install/any-kubernetes-cluster.md
  docs/install/installation-files.md
Labels: approved, cla: yes, lgtm, size/S

#3383 Correct link for Knative Serving documentation
  docs/serving/knative-kubernetes-services.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3381 Fix HPA allowed metrics
  docs/serving/autoscaling/autoscaling-metrics.md
Labels: approved, cla: yes, lgtm, size/XS

#3375 Update any-kubernetes-cluster.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3379 Removed README and moved content over to _index.md to resolve issue
  docs/eventing/sugar/README.md
  docs/eventing/sugar/_index.md
Labels: approved, cla: yes, lgtm, size/L

#3392 Update any-kubernetes-cluster.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3393 Update any-kubernetes-cluster.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3386 Update links and descriptions of TriggerMesh sources
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/S

#3391 fix(PingSource): correct commands and outputs
  docs/eventing/sources/pingsource.md
Labels: approved, cherrypick-0.20, cherrypick-0.21, cla: yes, lgtm, size/S

#3398 Update any-kubernetes-cluster.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3363 Separate prototyping and production concerns in any-kubernetes-cluster.md
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/S

#3382 Copied the README into _index.md instead of referencing README from
  docs/serving/README.md
  docs/serving/_index.md
Labels: approved, cla: yes, lgtm, size/L

#3142 adding katacoda tutorials
  katacoda.yaml
  tutorials/katacoda/1-serving-intro/finish.md
  tutorials/katacoda/1-serving-intro/index.json
  tutorials/katacoda/1-serving-intro/intro.md
  tutorials/katacoda/1-serving-intro/scripts/install-dependencies.sh
  tutorials/katacoda/1-serving-intro/step1.md
  tutorials/katacoda/1-serving-intro/step2.md
  tutorials/katacoda/1-serving-intro/step3.md
  tutorials/katacoda/2-serving-intro-yaml/finish.md
  tutorials/katacoda/2-serving-intro-yaml/index.json
  tutorials/katacoda/2-serving-intro-yaml/intro.md
  tutorials/katacoda/2-serving-intro-yaml/scripts/install-dependencies.sh
  tutorials/katacoda/2-serving-intro-yaml/step1.md
  tutorials/katacoda/2-serving-intro-yaml/step2.md
  tutorials/katacoda/2-serving-intro-yaml/step3.md
  tutorials/katacoda/3-eventing-intro-channels/assets/1to1.png
  tutorials/katacoda/3-eventing-intro-channels/assets/1toN.png
  tutorials/katacoda/3-eventing-intro-channels/assets/Nto1.png
  tutorials/katacoda/3-eventing-intro-channels/assets/channel.png
  tutorials/katacoda/3-eventing-intro-channels/assets/sequence.png
  tutorials/katacoda/3-eventing-intro-channels/finish.md
  tutorials/katacoda/3-eventing-intro-channels/index.json
  tutorials/katacoda/3-eventing-intro-channels/intro.md
  tutorials/katacoda/3-eventing-intro-channels/scripts/install-dependencies.sh
  tutorials/katacoda/3-eventing-intro-channels/step1.md
  tutorials/katacoda/3-eventing-intro-channels/step2.md
  tutorials/katacoda/3-eventing-intro-channels/step3.md
  tutorials/katacoda/3-eventing-intro-channels/step4.md
  tutorials/katacoda/4-eventing-intro-broker/assets/broker-eg.png
  tutorials/katacoda/4-eventing-intro-broker/assets/broker.png
  tutorials/katacoda/4-eventing-intro-broker/finish.md
  tutorials/katacoda/4-eventing-intro-broker/index.json
  tutorials/katacoda/4-eventing-intro-broker/intro.md
  tutorials/katacoda/4-eventing-intro-broker/scripts/install-dependencies.sh
  tutorials/katacoda/4-eventing-intro-broker/step1.md
  tutorials/katacoda/4-eventing-intro-broker/step2.md
  tutorials/katacoda/4-eventing-intro-broker/step3.md
Labels: approved, cla: yes, kind/enhancement, kind/sample, lgtm, ok-to-test, priority/0, size/XXL

#3365 Clean up create event source docs
  docs/eventing/samples/writing-event-source-easy-way/README.md
  docs/eventing/samples/writing-event-source-easy-way/_index.md
  docs/eventing/samples/writing-event-source/README.md
  docs/eventing/samples/writing-event-source/_index.md
  docs/eventing/sources/creating-event-sources/_index.md
  docs/eventing/sources/creating-event-sources/writing-event-source-easy-way/Dockerfile
  docs/eventing/sources/creating-event-sources/writing-event-source-easy-way/_index.md
  docs/eventing/sources/creating-event-sources/writing-event-source-easy-way/index.js
  docs/eventing/sources/creating-event-sources/writing-event-source-easy-way/package.json
  docs/eventing/sources/creating-event-sources/writing-event-source/01-theory.md
  docs/eventing/sources/creating-event-sources/writing-event-source/02-lifecycle-and-types.md
  docs/eventing/sources/creating-event-sources/writing-event-source/03-controller.md
  docs/eventing/sources/creating-event-sources/writing-event-source/04-reconciler.md
  docs/eventing/sources/creating-event-sources/writing-event-source/05-receive-adapter.md
  docs/eventing/sources/creating-event-sources/writing-event-source/06-yaml.md
  docs/eventing/sources/creating-event-sources/writing-event-source/07-knative-sandbox.md
  docs/eventing/sources/creating-event-sources/writing-event-source/_index.md
  docs/eventing/sources/creating-event-sources/writing-event-source/simplified-controller.png
Labels: approved, cla: yes, lgtm, size/XL

#3359 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#3401 Drop documentation for custom-metrics API
  docs/serving/custom-metrics-API.md
Labels: approved, cla: yes, lgtm, size/S
