Repository knative/docs, pull requests merged in 2021-08, with the labels that each got.

#4086 Avoid above and below
  docs/help/contributor/style-guide/documenting-code.md
  docs/help/contributor/style-guide/word-and-phrase-list.md
Labels: approved, cla: yes, lgtm, size/XS

#4070 3703: feature flag docs updates
  config/nav.yml
  config/redirects.yml
  docs/admin/serving/feature-flags.md
  docs/serving/feature-flags.md
Labels: Administrator guide, approved, cla: yes, kind/cleanup, lgtm, size/XL

#4100 [mkdocs] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4028 General eventing and kafka updates
  config/nav.yml
  docs/admin/install/eventing/install-eventing-with-yaml.md
  docs/developer/eventing/sources/README.md
  docs/eventing/samples/README.md
  docs/eventing/samples/kafka/README.md
  docs/eventing/samples/kafka/channel/000-ksvc.yaml
  docs/eventing/samples/kafka/channel/010-serviceaccount.yaml
  docs/eventing/samples/kafka/channel/020-k8s-events.yaml
  docs/eventing/samples/kafka/channel/030-trigger.yaml
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/kafka.yaml
  docs/eventing/samples/kafka/kafka_setup.sh
Labels: approved, cla: yes, lgtm, size/XL

#4068 Cherry-pick Update knative-offerings.md (#3994)
  docs/admin/install/knative-offerings.md
Labels: size/XS, lgtm, cla: yes, approved

#4098 Fixed a minor typo.
  docs/serving/using-auto-tls.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4099 Fixed case of cloudDNS
  docs/serving/using-auto-tls.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4094 Updates Broken Link in Event Registry Documentation
  docs/eventing/event-registry.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4091 Update knative-with-operators.md
  docs/admin/install/knative-with-operators.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4090 Fix the value of the Kafka broker class to `Kafka`
  docs/eventing/broker/example-mtbroker.md
Labels: size/XS, lgtm, cla: yes, approved

#4096 Complete instructions for installing kn binary
  docs/snippets/install-kn.md
Labels: lgtm, size/S, cla: yes, approved

#4109 [mkdocs] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, cla: yes, approved

#4107 Add references to upating nav menu
  .github/pull-request-template.md
  docs/help/contributor/structure.md
Labels: size/M, lgtm, cla: yes, approved

#4095 Ways to connect to cluster using kn
  docs/client/README.md
Labels: lgtm, size/S, cla: yes, approved

#4120 Fixes #11810
  archived/v0.23-docs/install/collecting-metrics/collector.yaml
Labels: lgtm, size/S, needs-ok-to-test, cla: yes, approved

#4104 add docs for byo certificate via domainmapping
  config/nav.yml
  docs/developer/serving/services/byo-certificate.md
Labels: size/M, lgtm, cla: yes, approved

#4083 Updating the last few commands to remove EOF
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/setting-up-custom-ingress-gateway.md
Labels: size/L, lgtm, cla: yes, approved

#4127 [mkdocs] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/XS, lgtm, cla: yes, approved

#4137 Add Knative GitHub repo rule to W&P List
  docs/help/contributor/style-guide/word-and-phrase-list.md
Labels: size/XS, lgtm, cla: yes, approved

#4125 #4124: fix link
  docs/getting-started/first-broker.md
Labels: size/XS, lgtm, cla: yes, approved

#4142 [mkdocs] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, cla: yes, approved

#4143 Fixed an example of imagePullSecrets
  docs/serving/deploying-from-private-registry.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4144 Added definition list formatting rule
  docs/help/contributor/style-guide/style-and-formatting.md
Labels: size/XS, lgtm, cla: yes, approved

#4151 add v0.25 mkdocs, remove v0.21 hugo
  hack/build.sh
  hack/docker/Dockerfile
Labels: size/M, lgtm, cla: yes, approved

#4155 Add link styling rules
  docs/help/contributor/style-guide/style-and-formatting.md
Labels: lgtm, size/S, cla: yes, approved

#4153 Update version warning banner for new release
  docs/stylesheets/extra.css
  overrides/main.html
Labels: lgtm, size/S, cla: yes, approved

#4130 Fix typo
  docs/help/contributor/mkdocs-contributor-guide.md
Labels: size/XS, lgtm, cla: yes, approved

#4121 Fix broken formatting
  docs/admin/collecting-metrics/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4123 Add .md file extension to internal links in docs/serving/
  docs/serving/README.md
  docs/serving/autoscaling/README.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/deploying-from-private-registry.md
  docs/serving/getting-started-knative-app.md
  docs/serving/installing-cert-manager.md
  docs/serving/istio-authorization.md
  docs/serving/load-balancing/README.md
  docs/serving/load-balancing/target-burst-capacity.md
  docs/serving/samples/README.md
  docs/serving/samples/cloudevents/cloudevents-dotnet/README.md
  docs/serving/samples/cloudevents/cloudevents-go/README.md
  docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
  docs/serving/samples/cloudevents/cloudevents-rust/README.md
  docs/serving/samples/cloudevents/cloudevents-spring/README.md
  docs/serving/samples/cloudevents/cloudevents-vertx/README.md
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-go/README.md
  docs/serving/samples/hello-world/helloworld-java-spark/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-php/README.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/hello-world/helloworld-ruby/README.md
  docs/serving/samples/hello-world/helloworld-scala/README.md
  docs/serving/samples/hello-world/helloworld-shell/README.md
  docs/serving/samples/knative-routing-go/README.md
  docs/serving/samples/multi-container/README.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/tag-header-based-routing/README.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-a-tls-cert.md
  docs/serving/using-auto-tls.md
Labels: size/L, lgtm, cla: yes, approved

#4139 Add .md to links in getting-started and client folders
  docs/client/README.md
  docs/client/configure-kn.md
  docs/getting-started/README.md
  docs/getting-started/first-autoscale.md
  docs/getting-started/first-broker.md
  docs/getting-started/first-traffic-split.md
  docs/getting-started/next-steps.md
Labels: lgtm, size/S, cla: yes, approved

#4148 Add tracing blog post
  blog/articles/distributed-tracing.md
  blog/articles/images/tracing-1.png
  blog/articles/images/tracing-2.png
  blog/articles/images/tracing-3.png
  blog/articles/images/tracing-4.png
  blog/articles/images/tracing-5.png
Labels: size/L, lgtm, cla: yes, approved

#4170 Fix many links in the Eventing folder
  docs/eventing/accessing-traces.md
  docs/eventing/broker/README.md
  docs/eventing/broker/create-mtbroker.md
  docs/eventing/broker/example-mtbroker.md
  docs/eventing/broker/kafka-broker/README.md
  docs/eventing/channels/README.md
  docs/eventing/channels/channel-types-defaults.md
  docs/eventing/channels/create-default-channel.md
  docs/eventing/channels/subscriptions.md
  docs/eventing/debugging/README.md
  docs/eventing/event-registry.md
  docs/eventing/experimental-features.md
  docs/eventing/flows/README.md
  docs/eventing/flows/parallel.md
  docs/eventing/flows/sequence/README.md
  docs/eventing/flows/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/flows/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/flows/sequence/sequence-terminal/README.md
  docs/eventing/flows/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/getting-started.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/gitlab-source/README.md
  docs/eventing/samples/helloworld/README.md
  docs/eventing/samples/helloworld/helloworld-go/README.md
  docs/eventing/samples/helloworld/helloworld-python/README.md
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/kafka/binding/README.md
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/parallel/README.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
Labels: size/L, lgtm, cla: yes, approved

#4169 eventing-natss: Fix name of release manifest
  docs/admin/install/eventing/install-eventing-with-yaml.md
  docs/admin/install/uninstall.md
Labels: size/XS, lgtm, cla: yes, approved

#4141 Fix broken link, some minor cleanup
  docs/developer/eventing/sources/kafka-source/README.md
Labels: lgtm, size/XL, cla: yes, approved

#4039 eventing(samples): update Node.js CloudEvents ContainerSource example
  docs/developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/Dockerfile
  docs/developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/README.md
  docs/developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/index.js
  docs/developer/eventing/sources/creating-event-sources/writing-event-source-easy-way/package.json
  docs/serving/samples/cloudevents/cloudevents-nodejs/index.js
  docs/serving/samples/cloudevents/cloudevents-nodejs/package-lock.json
  docs/serving/samples/cloudevents/cloudevents-nodejs/package.json
Labels: lgtm, size/XXL, cla: yes, ok-to-test, approved
