Repository knative/docs, pull requests merged in 2021-05, with the labels that each got.

#3516 CP of #3515
  docs/client/_index.md
  docs/eventing/README.md
  docs/eventing/_index.md
  docs/knative-offerings.md
  docs/serving/_index.md
  docs/upgrade/_index.md
  docs/upgrade/upgrade-installation-with-operator.md
  docs/upgrade/upgrade-installation.md
Labels: approved, cla: yes, lgtm, size/L

#3511 updated to hyper v0.14.7 and rust v1.51.0
  community/samples/serving/helloworld-rust/Cargo.toml
  community/samples/serving/helloworld-rust/Dockerfile
  community/samples/serving/helloworld-rust/index.md
  community/samples/serving/helloworld-rust/src/main.rs
Labels: approved, cla: yes, kind/serving, lgtm, ok-to-test, size/L

#3517 fix order
  docs/install/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3519 minor change to fix command
  docs/serving/samples/hello-world/helloworld-java-spring/index.md
Labels: approved, cherrypick-0.22, cla: yes, lgtm, size/XS

#3509 Updated pingsource docs, collated info
  docs/eventing/samples/ping-source/index.md
  docs/eventing/sources/ping-source/index.md
  docs/eventing/sources/ping-source/ping-source-binary.yaml
  docs/eventing/sources/ping-source/ping-source.yaml
  docs/eventing/sources/ping-source/service.yaml
  docs/eventing/sources/pingsource.md
Labels: approved, cla: yes, lgtm, size/XL

#3502 setting a custom resource as sink doc
  docs/eventing/sink/_index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3533 change name for menu item for preview
  help/contributor/publishing.md
Labels: approved, cla: yes, lgtm, size/XS

#3514 Added detail per issue #3425
  docs/eventing/channels/_index.md
Labels: approved, cla: yes, lgtm, size/S

#3556 background gradient animation for homepage banner
  overrides/home.html
Labels: approved, cla: yes, lgtm, size/M

#3529 Cherrypick #3495
  docs/client/configure-kn.md
  docs/client/install-kn.md
  docs/client/kn-plugins.md
Labels: approved, cla: yes, lgtm, size/M

#3553 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#3506 config-tracing configmap fix
  docs/eventing/accessing-traces.md
Labels: approved, cla: yes, kind/serving, lgtm, ok-to-test, size/XS, triage/needs-eng-input

#3563 remove unnecessary requrirements to do a release
  help/maintainer/docs-release-process.md
Labels: approved, cla: yes, lgtm, size/S

#3557 add gh-action to deploy mkdocs to gh-pages
  .github/workflows/knative-mkdocs.yaml
  hack/docker/Dockerfile
  hack/docker/README.md
  hack/docker/build.sh
  hack/docker/clean.sh
  hack/docker/mkdocs.sh
  hack/docker/run.sh
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/M

#3558 Build blog and community with hugo
  .gitignore
  docs/stylesheets/extra.css
  hack/build-with-blog.sh
  mkdocs.yml
  package-lock.json
  package.json
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XXL

#3570 remove duplicate old page
  docs/install/upgrade-installation-with-operator.md
Labels: approved, cla: yes, kind/cleanup, lgtm, size/L

#3566 Regenerate the client nav
  docs/client/README.md
  mkdocs.yml
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XS

#3572 Update Github action to build with hugo and mkdocs
  .github/workflows/knative-mkdocs.yaml
  hack/build-with-blog.sh
  mkdocs.yml
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/M

#3571 feat: added home and navigation menu changes
  docs/stylesheets/extra.css
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XL

#3567 #3543 fix link
  community/samples/_index.md
  community/samples/serving/helloworld-clojure/index.md
  community/samples/serving/helloworld-dart/index.md
  community/samples/serving/helloworld-deno/index.md
  community/samples/serving/helloworld-haskell/index.md
  community/samples/serving/helloworld-java-micronaut/index.md
  community/samples/serving/helloworld-java-quarkus/index.md
  community/samples/serving/helloworld-r/index.md
  community/samples/serving/helloworld-rserver/index.md
  community/samples/serving/helloworld-rust/index.md
  community/samples/serving/helloworld-swift/index.md
  community/samples/serving/helloworld-vertx/index.md
  community/samples/serving/machinelearning-python-bentoml/index.md
  docs/eventing/event-registry.md
  docs/eventing/getting-started.md
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/installing-istio.md
  docs/samples.md
  docs/serving/_index.md
  docs/serving/autoscaling/_index.md
  docs/serving/autoscaling/autoscale-go/index.md
  docs/serving/deploying/private-registry.md
  docs/serving/feature-flags.md
  docs/serving/getting-started-knative-app.md
  docs/serving/samples/_index.md
  docs/serving/samples/cloudevents/cloudevents-dotnet/index.md
  docs/serving/samples/cloudevents/cloudevents-go/index.md
  docs/serving/samples/cloudevents/cloudevents-nodejs/index.md
  docs/serving/samples/cloudevents/cloudevents-rust/index.md
  docs/serving/samples/cloudevents/cloudevents-spring/index.md
  docs/serving/samples/cloudevents/cloudevents-vertx/index.md
  docs/serving/samples/hello-world/helloworld-csharp/index.md
  docs/serving/samples/hello-world/helloworld-go/index.md
  docs/serving/samples/hello-world/helloworld-java-spark/index.md
  docs/serving/samples/hello-world/helloworld-java-spring/index.md
  docs/serving/samples/hello-world/helloworld-kotlin/index.md
  docs/serving/samples/hello-world/helloworld-nodejs/index.md
  docs/serving/samples/hello-world/helloworld-php/index.md
  docs/serving/samples/hello-world/helloworld-python/index.md
  docs/serving/samples/hello-world/helloworld-ruby/index.md
  docs/serving/samples/hello-world/helloworld-scala/index.md
  docs/serving/samples/hello-world/helloworld-shell/index.md
  docs/serving/using-a-custom-domain.md
  docs/serving/using-external-dns-on-gcp.md
  hack/__pycache__/macros.cpython-36.pyc
  template-docs-page.md
Labels: approved, cla: yes, lgtm, size/L

#3574 Replace xip.io with sslip.io
  blog/articles/set-up-a-local-knative-environment-with-kind.md
  community/samples/serving/helloworld-clojure/index.md
  community/samples/serving/helloworld-dart/index.md
  community/samples/serving/helloworld-deno/index.md
  community/samples/serving/helloworld-elixir/index.md
  community/samples/serving/helloworld-haskell/index.md
  community/samples/serving/helloworld-java-micronaut/index.md
  community/samples/serving/helloworld-java-quarkus/index.md
  community/samples/serving/helloworld-r/index.md
  community/samples/serving/helloworld-rserver/index.md
  community/samples/serving/helloworld-rust/index.md
  community/samples/serving/helloworld-swift/index.md
  community/samples/serving/helloworld-vertx/index.md
  docs/eventing/samples/container-source/index.md
  docs/install/install-serving-with-yaml.md
  docs/install/installation-files.md
  docs/install/installing-istio.md
  docs/install/knative-with-operators.md
  docs/serving/autoscaling/autoscale-go/index.md
  docs/serving/getting-started-knative-app.md
  docs/serving/samples/cloudevents/cloudevents-go/index.md
  docs/serving/samples/cloudevents/cloudevents-nodejs/index.md
  docs/serving/samples/cloudevents/cloudevents-rust/index.md
  docs/serving/samples/cloudevents/cloudevents-spring/index.md
  docs/serving/samples/cloudevents/cloudevents-vertx/index.md
  docs/serving/samples/grpc-ping-go/index.md
  docs/serving/samples/hello-world/helloworld-csharp/index.md
  docs/serving/samples/hello-world/helloworld-go/index.md
  docs/serving/samples/hello-world/helloworld-java-spark/index.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/index.md
  docs/serving/samples/hello-world/helloworld-kotlin/index.md
  docs/serving/samples/hello-world/helloworld-nodejs/index.md
  docs/serving/samples/hello-world/helloworld-php/index.md
  docs/serving/samples/hello-world/helloworld-python/index.md
  docs/serving/samples/hello-world/helloworld-ruby/index.md
  docs/serving/samples/hello-world/helloworld-scala/index.md
  docs/serving/samples/hello-world/helloworld-shell/index.md
  docs/serving/samples/multi-container/index.md
  docs/serving/samples/rest-api-go/index.md
  docs/serving/samples/secrets-go/index.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#3535 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#3505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3545 Remove responsive-revision-gc config
  docs/serving/feature-flags.md
Labels: approved, cla: yes, lgtm, size/XS

#3569 Fixes #3117 and broken links
  docs/serving/_index.md
  docs/serving/debugging-application-issues.md
  docs/serving/deploying/private-registry.md
  docs/serving/spec/knative-api-specification-1.0.md
Labels: approved, cla: yes, kind/serving, lgtm, size/M

#3550 Update shortcodes.md
  help/contributor/how-to/shortcodes.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3582 Enable workflows for mkdocs branch
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#3536 Slight change to ordered delivery guarantees
  docs/eventing/broker/kafka-broker/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3586 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3580 Add branch-based versioning
  docs/stylesheets/extra.css
  hack/build-with-blog.sh
  mkdocs.yml
  overrides/main.html
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/L

#3589 add correct bin PATH for postcss
  hack/build-with-blog.sh
Labels: approved, cla: yes, lgtm, size/XS

#3592 Mkdocs netlify
  netlify.toml
  requirements.txt
Labels: approved, cla: yes, lgtm, size/S

#3587 add approvers ux
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3530 Update the default progress deadline value
  docs/serving/services/deployment.md
Labels: approved, cherrypick-0.21, cherrypick-0.22, cla: yes, kind/bug, lgtm, size/XS, triage/needs-eng-input

#3596 Adding notes on KafkaSource usage
  docs/eventing/samples/kafka/source/index.md
Labels: approved, cla: yes, lgtm, size/XS

#3581 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3594 Remove pycache
  hack/__pycache__/macros.cpython-36.pyc
Labels: approved, cla: yes, lgtm, size/XS

#3578 Suggestions for getting started
  docs/getting-started/README.md
  docs/getting-started/getting-started.md
  docs/getting-started/install-serving-eventing.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/L

#3595 Use correct ClusterIssue name
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/S

#3584 Sanity Check Install Content
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/sources/apache-camel-source/README.md
  docs/eventing/sources/cloud-audit-logs-source/README.md
  docs/eventing/sources/cloud-pubsub-source/README.md
  docs/eventing/sources/cloud-scheduler-source/README.md
  docs/eventing/sources/cloud-storage-source/README.md
  docs/eventing/sources/container-source/README.md
  docs/eventing/sources/container-source/heartbeats-source.yaml
  docs/eventing/sources/container-source/service.yaml
  docs/eventing/sources/github-source/README.md
  docs/eventing/sources/github-source/github-source.yaml
  docs/eventing/sources/github-source/githubsecret.yaml
  docs/eventing/sources/github-source/personal_access_token.png
  docs/eventing/sources/github-source/service.yaml
  docs/eventing/sources/github-source/webhook_created.png
  docs/eventing/sources/gitlab-source/README.md
  docs/eventing/sources/kafka-source/README.md
  docs/eventing/sources/kafka-source/event-display.yaml
  docs/eventing/sources/kafka-source/event-source.yaml
  docs/eventing/sources/kafka-source/kafka-topic.yaml
  docs/getting-started/csantana-getting-started-eventing.md
  docs/install/README.md
  docs/install/_index.md
  docs/install/check-install-version.md
  docs/install/collecting-logs/README.md
  docs/install/collecting-logs/_index.md
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/install-serving-with-yaml.md
  docs/install/operator/configuring-serving-cr.md
  docs/serving/deploying-from-private-registry/README.md
  docs/serving/samples/hello-world/helloworld-java-spring/index.md
  mkdocs.yml
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XL

#3579 Fix broken links
  docs/eventing/accessing-traces.md
  docs/eventing/channels/channel-types-defaults.md
  docs/eventing/debugging/index.md
  docs/eventing/flows/parallel.md
  docs/eventing/samples/_index.md
  docs/eventing/samples/gitlab-source/index.md
  docs/eventing/samples/helloworld/_index.md
  docs/eventing/samples/helloworld/helloworld-go/_index.md
  docs/eventing/samples/helloworld/helloworld-python/_index.md
  docs/eventing/samples/kafka/_index.md
  docs/eventing/samples/kafka/binding/index.md
  docs/eventing/samples/kafka/channel/index.md
  docs/eventing/samples/kafka/source/index.md
  docs/eventing/samples/parallel/_index.md
  docs/eventing/samples/parallel/multiple-branches/_index.md
  docs/eventing/samples/parallel/mutual-exclusivity/_index.md
  docs/serving/samples/blue-green-deployment.md
  docs/serving/samples/gitwebhook-go/index.md
  docs/serving/samples/grpc-ping-go/index.md
  docs/serving/samples/hello-world/helloworld-java-spring/README.md
  docs/serving/samples/knative-routing-go/index.md
  docs/serving/samples/multi-container/index.md
  docs/serving/samples/rest-api-go/index.md
  docs/serving/samples/secrets-go/index.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3611 add python dependency mkdocs-awesome-pages plugin
  hack/docker/Dockerfile
  requirements.txt
Labels: approved, cla: yes, lgtm, size/XS

#3603 Updating to latest API version of Strimzi.
  docs/eventing/samples/kafka/_index.md
  docs/eventing/samples/kafka/kafka.yaml
  docs/eventing/samples/kafka/source/index.md
  docs/eventing/samples/kafka/source/kafka-topic.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3602 fix broken link in kogito example
  blog/articles/event-drive-app-knative-eventing-kogito.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3619 api specs for Release v0.23
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#3585 Update serving/_index.md with network layer option
  docs/serving/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3616 Fix typos in the sample yaml file
  docs/serving/samples/knative-routing-go/routing.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3576 EventType is not yet part of the v1 eventing API
  docs/eventing/event-registry.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS, triage/needs-eng-input

#3625 make default version development for now
  hack/build-with-blog.sh
Labels: approved, cla: yes, lgtm, size/XS

#3637 Even out the margins and paddings on the homepage
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/M

#3626 [mkdocs] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XS

#3639 correct link to point to latest appender example
  docs/eventing/flows/sequence/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3631 fix the broken link
  help/maintainer/docs-release-process.md
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XS

#3632 Fix a mismatch in 'a' vs. plural
  overrides/home.html
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XS

#3645 One plugin section to rule them all (fixes search)
  docs/check-install-version.md
  mkdocs.yml
Labels: approved, cla: yes, lgtm, size/M

#3628 handle old versions with redirects
  hack/build-with-blog.sh
  netlify.toml
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/S

#3655 fixes #3654
  docs/getting-started/README.md
  docs/getting-started/first-service.md
Labels: approved, cla: yes, lgtm, size/S

#3651 correct link to knfun sample
  docs/samples.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#3657 fixes #3656
  docs/getting-started/first-traffic-split.md
Labels: approved, cla: yes, lgtm, size/S

#3661 Fix 3654 bug fixes
  docs/getting-started/first-service.md
Labels: approved, cla: yes, lgtm, size/S

#3636 Be a bit more subtle with the gradient's colors
  overrides/assets/stylesheets/home.css
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/S

#3635 Fix syntax error that causes some CSS to not apply
  docs/stylesheets/extra.css
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XS

#3532 fix serving samples application cannot build docker image
  docs/serving/samples/gitwebhook-go/Dockerfile
  docs/serving/samples/gitwebhook-go/go.mod
  docs/serving/samples/grpc-ping-go/Dockerfile
  docs/serving/samples/grpc-ping-go/client/client.go
  docs/serving/samples/grpc-ping-go/go.mod
  docs/serving/samples/grpc-ping-go/grpc-ping.go
  docs/serving/samples/grpc-ping-go/proto/ping.pb.go
  docs/serving/samples/secrets-go/Dockerfile
  docs/serving/samples/secrets-go/go.mod
  docs/serving/samples/secrets-go/index.md
Labels: approved, cla: yes, kind/needs-migration, lgtm, ok-to-test, size/M, triage/needs-eng-input

#3659 Updating to Version 0.3.1 of the CE SDK for Rust
  docs/serving/samples/cloudevents/cloudevents-rust/Cargo.lock
  docs/serving/samples/cloudevents/cloudevents-rust/Cargo.toml
Labels: approved, cla: yes, lgtm, size/M

#3634 Add a bit of padding around the logo in the header
  overrides/assets/stylesheets/home.css
Labels: approved, cla: yes, kind/mkdocs, lgtm, size/XS

#3670 Bump cert manager API verson
  docs/admin/install/install-extensions.md
  docs/serving/using-auto-tls.md
  docs/serving/using-cert-manager-on-gcp.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#3646 Developer guide mkdocs
  docs/developer/README.md
  docs/developer/serving/services/README.md
  docs/developer/serving/services/configure-requests-limits-services.md
  docs/developer/serving/services/creating-services.md
  docs/developer/serving/services/deployment.md
  docs/developer/serving/services/private-services.md
  docs/serving/services/README.md
  docs/serving/services/creating-services.md
  docs/serving/services/private-services.md
  mkdocs.yml
Labels: approved, cla: yes, lgtm, size/L

#3662 eventing getting started hotfixes
  docs/admin/install/install-eventing-with-yaml.md
  docs/getting-started/first-broker.md
  docs/getting-started/first-source.md
Labels: approved, cla: yes, lgtm, size/S

#3683 Fix redirect to cope with query strings
  hack/build-with-blog.sh
Labels: approved, cla: yes, lgtm, size/XS

#3669 Sink binding docs (reopened PR)
  docs/eventing/sources/sinkbinding.md
  docs/eventing/sources/sinkbinding/README.md
  docs/eventing/sources/sinkbinding/getting-started.md
  docs/eventing/sources/sinkbinding/reference.md
  mkdocs.yml
Labels: approved, cla: yes, lgtm, size/XL
