Repository knative/docs, pull requests merged in 2021-10, with the labels that each got.

#4312 Update broken VMware link
  docs/admin/install/knative-offerings.md
Labels: size/XS, lgtm, cla: yes, approved

#4309 Add doc for rabbitmq broker
  config/nav.yml
  docs/eventing/broker/README.md
  docs/eventing/broker/rabbitmq-broker/README.md
Labels: size/M, lgtm, cla: yes, approved

#4313 Added rollout & time-based in words list, made the changes(roll-out to rollout) in some files (#3997)
  docs/developer/serving/rolling-out-latest-revision.md
  docs/help/contributor/style-guide/word-and-phrase-list.md
  docs/snippets/gradual-rollout-intro.md
  docs/snippets/multiple-rollouts.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4271 clean up some of the ingress.class documentation
  docs/developer/serving/services/ingress-class.md
Labels: lgtm, size/S, cla: yes, approved

#4323 release blog for 0.26
  blog/releases/announcing-knative-v0-26-release.md
Labels: size/L, lgtm, cla: yes, approved

#4299 Ignore venv directory
  .gitignore
Labels: size/XS, lgtm, cla: yes, approved

#4327 Fix operator link on Knative release notes page
  docs/reference/relnotes/README.md
Labels: size/XS, lgtm, cla: yes, kind/serving, ok-to-test, approved

#4325 Update metrics collector README.md
  docs/admin/collecting-metrics/README.md
Labels: triage/needs-eng-input, size/XS, lgtm, cla: yes, ok-to-test, approved

#4328 Adding basic sources configuration (ping source)
  config/nav.yml
  docs/admin/eventing/sources-configuration.md
Labels: size/M, lgtm, cla: yes, approved

#4297 Update the docs on configuring the knative-ingress-gateway gateway and istio-ingressgateway-service
  docs/admin/install/operator/configuring-serving-cr.md
Labels: size/M, lgtm, cla: yes, approved
