Repository knative/docs, pull requests merged in 2021-04, with the labels that each got.

#3399 Split YAML installing topic
  docs/eventing/broker/kafka-broker.md
  docs/eventing/samples/helloworld/helloworld-go/README.md
  docs/eventing/sink/kafka-sink.md
  docs/install/_index.md
  docs/install/any-kubernetes-cluster.md
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/install-serving-with-yaml.md
  docs/install/installation-files.md
  docs/install/knative-with-operators.md
  docs/install/prerequisites.md
  docs/serving/autoscaling/README.md
  docs/serving/autoscaling/autoscaling-concepts.md
  docs/serving/creating-domain-mappings.md
  docs/serving/istio-authorization.md
  docs/serving/using-auto-tls.md
Labels: approved, cla: yes, lgtm, size/XXL

#3410 Make Homebrew installation the first option for `kn`, pull command to install out of Github and into knative.dev site
  docs/client/install-kn.md
Labels: approved, cla: yes, lgtm, size/S

#3413 Create prerequisites.md
  docs/install/prerequisites.md
Labels: approved, cla: yes, lgtm

#3414 Update prerequisites.md
  docs/install/prerequisites.md
Labels: approved, cla: yes, lgtm

#3416 Fix install-kn link from install landing page
  docs/install/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3418 Update install-serving-with-yaml.md
  docs/install/install-serving-with-yaml.md
Labels: approved, cla: yes, lgtm

#3420 PRing my own PR :(
  docs/install/install-serving-with-yaml.md
Labels: approved, cla: yes, lgtm, size/XS

#3421 Update install-eventing-with-yaml.md
  docs/install/install-eventing-with-yaml.md
Labels: approved, cla: yes, lgtm, size/XS

#3422 Fixing the kn cli references
  docs/client/install-kn.md
  docs/install/_index.md
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/install-serving-with-yaml.md
  docs/install/prerequisites.md
Labels: approved, cla: yes, lgtm, size/M

#3423 Revert "Fixing the kn cli references"
  docs/client/install-kn.md
  docs/install/_index.md
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/install-serving-with-yaml.md
  docs/install/prerequisites.md
Labels: approved, cla: yes, lgtm, size/M

#3424 Removing `kn` from required
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/install-serving-with-yaml.md
  docs/install/prerequisites.md
Labels: cla: yes, size/S

#3426 Releasing v0.22.0
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
Labels: approved, cla: yes, lgtm, size/XXL

#3406 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
  blog/OWNERS
  docs/eventing/OWNERS
  docs/eventing/channels/OWNERS
  docs/eventing/sink/OWNERS
  docs/eventing/sources/OWNERS
  docs/install/OWNERS
  docs/serving/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#3429 Adding @snneji changes
  docs/install/install-eventing-with-yaml.md
  docs/install/prerequisites.md
Labels: approved, cla: yes, lgtm, size/XS

#3369 Kafka broker ordered delivery
  docs/eventing/broker/kafka-broker.md
Labels: approved, cla: yes, lgtm, size/M

#3435 Update install-serving-with-yaml.md
  docs/install/install-serving-with-yaml.md
Labels: approved, cla: yes, lgtm, size/XS

#3433 Adding a bit more of clarfication on default channel configs
  docs/install/operator/configuring-eventing-cr.md
Labels: approved, cla: yes, lgtm, size/S

#3411 Updating install flow with minor changes to reflect desired prototype in UX/11
  docs/client/install-kn.md
  docs/install/_index.md
  docs/install/install-eventing-with-yaml.md
  docs/install/install-extensions.md
  docs/install/install-serving-with-yaml.md
  docs/install/prerequisites.md
Labels: approved, cla: yes, lgtm, size/M

#3443 Make OWNERS_ALIASES valid yaml
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#3408 [#3300] Added Uninstalling topic
  docs/install/knative-with-operators.md
  docs/uninstall.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3434 Adding duck type concept page
  docs/concepts/README.md
  docs/concepts/_index.md
Labels: approved, cla: yes, lgtm, size/L

#3438 [KafkaSink] Fix auth secret reference
  docs/eventing/sink/kafka-sink.md
Labels: approved, cla: yes, lgtm, size/XS

#3432 change master to main
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, lgtm, size/S

#3456 Update link to camel.yaml
  docs/eventing/samples/apache-camel-source/index.md
  docs/eventing/sources/apache-camel-source/display_resources.yaml
  docs/eventing/sources/apache-camel-source/index.md
  docs/eventing/sources/apache-camel-source/source_http_poller.yaml
  docs/eventing/sources/apache-camel-source/source_mqtt.yaml
  docs/eventing/sources/apache-camel-source/source_telegram.yaml
  docs/eventing/sources/apache-camel-source/source_timer.yaml
Labels: approved, cla: yes, lgtm, size/S

#3455 Delete RPS Target tab
  docs/serving/autoscaling/autoscaling-targets.md
Labels: approved, cherrypick-0.22, cla: yes, lgtm, size/S

#3441 Add context to network layer install section
  docs/install/install-serving-with-yaml.md
Labels: approved, cla: yes, lgtm, size/S

#3450 Blog post announcing the TOC election kick-off for 2021.
  blog/steering/[BLOG]-toc-2021-election-announcement.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3404 Cleanup apiserversource docs
  docs/eventing/samples/kubernetes-event-source/README.md
  docs/eventing/samples/kubernetes-event-source/index.md
  docs/eventing/samples/kubernetes-event-source/k8s-events.yaml
  docs/eventing/samples/kubernetes-event-source/serviceaccount.yaml
  docs/eventing/samples/kubernetes-event-source/trigger.yaml
  docs/eventing/sources/_index.md
  docs/eventing/sources/apiserversource.md
  docs/eventing/sources/apiserversource/_index.md
  docs/eventing/sources/apiserversource/getting-started/_index.md
Labels: approved, cla: yes, lgtm, size/XL

#3454 fix homebrew statement
  docs/client/install-kn.md
Labels: approved, cla: yes, lgtm, size/XS

#3430 Update k8s version
  docs/install/any-kubernetes-cluster.md
Labels: approved, cla: yes, lgtm, size/XS

#3460 Updates to services docs
  docs/serving/cluster-local-route.md
  docs/serving/creating-domain-mappings.md
  docs/serving/knative-kubernetes-services.md
  docs/serving/services/_index.md
  docs/serving/services/creating-services.md
  docs/serving/services/deployment.md
  docs/serving/services/private-services.md
  docs/serving/services/using-a-custom-domain-per-service.md
  docs/serving/using-a-custom-domain-per-service.md
Labels: approved, cla: yes, lgtm, size/L

#3395 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#3427 Improving / reorg of broker docs
  docs/eventing/README.md
  docs/eventing/_index.md
  docs/eventing/broker/README.md
  docs/eventing/broker/_index.md
  docs/eventing/broker/alternate/README.md
  docs/eventing/broker/alternate/_index.md
  docs/eventing/broker/broker-types.md
  docs/eventing/broker/config-br-defaults.md
  docs/eventing/broker/configuring-brokers.md
  docs/eventing/broker/images/broker-workflow.svg
  docs/eventing/broker/kafka-broker/_index.md
  docs/eventing/broker/kafka-broker/kafka-configmap.md
  docs/eventing/broker/triggers/_index.md
  docs/eventing/channels/channel-types-defaults.md
  docs/eventing/images/broker-trigger-overview.svg
Labels: approved, cla: yes, lgtm, size/XL

#3469 Move serving samples to index.md
  docs/serving/samples/README.md
  docs/serving/samples/_index.md
  docs/serving/samples/cloudevents/cloudevents-dotnet/README.md
  docs/serving/samples/cloudevents/cloudevents-dotnet/index.md
  docs/serving/samples/cloudevents/cloudevents-nodejs/README.md
  docs/serving/samples/cloudevents/cloudevents-nodejs/index.md
  docs/serving/samples/cloudevents/cloudevents-spring/README.md
  docs/serving/samples/cloudevents/cloudevents-vertx/README.md
  docs/serving/samples/gitwebhook-go/README.md
  docs/serving/samples/gitwebhook-go/index.md
  docs/serving/samples/grpc-ping-go/README.md
  docs/serving/samples/grpc-ping-go/index.md
  docs/serving/samples/hello-world/helloworld-csharp/README.md
  docs/serving/samples/hello-world/helloworld-csharp/index.md
  docs/serving/samples/hello-world/helloworld-kotlin/README.md
  docs/serving/samples/hello-world/helloworld-kotlin/index.md
  docs/serving/samples/hello-world/helloworld-nodejs/README.md
  docs/serving/samples/hello-world/helloworld-nodejs/index.md
  docs/serving/samples/hello-world/helloworld-python/README.md
  docs/serving/samples/knative-routing-go/README.md
  docs/serving/samples/knative-routing-go/index.md
  docs/serving/samples/multi-container/README.md
  docs/serving/samples/multi-container/index.md
  docs/serving/samples/rest-api-go/README.md
  docs/serving/samples/rest-api-go/index.md
  docs/serving/samples/secrets-go/README.md
  docs/serving/samples/secrets-go/index.md
  docs/serving/samples/tag-header-based-routing/README.md
  docs/serving/samples/tag-header-based-routing/index.md
  docs/serving/samples/traffic-splitting/README.md
  docs/serving/samples/traffic-splitting/index.md
Labels: approved, cla: yes, lgtm, size/XXL

#3475 Move remaining docs to index.md
  docs/concepts/README.md
  docs/concepts/_index.md
  docs/install/collecting-logs/README.md
  docs/install/collecting-logs/_index.md
Labels: approved, cla: yes, lgtm, size/XL

#3473 Move eventing docs to index.md
  docs/eventing/debugging/README.md
  docs/eventing/debugging/index.md
  docs/eventing/flows/README.md
  docs/eventing/flows/_index.md
  docs/eventing/sink/README.md
  docs/eventing/sink/_index.md
Labels: approved, cla: yes, lgtm, size/XL

#3474 Move serving docs to index.md
  docs/serving/autoscaling/README.md
  docs/serving/autoscaling/_index.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/autoscaling/autoscale-go/index.md
Labels: approved, cla: yes, lgtm, size/XL

#3470 Move eventing samples to index.md
  docs/eventing/samples/README.md
  docs/eventing/samples/_index.md
  docs/eventing/samples/cloud-audit-logs-source/README.md
  docs/eventing/samples/cloud-audit-logs-source/index.md
  docs/eventing/samples/cloud-pubsub-source/README.md
  docs/eventing/samples/cloud-pubsub-source/index.md
  docs/eventing/samples/cloud-scheduler-source/README.md
  docs/eventing/samples/cloud-scheduler-source/index.md
  docs/eventing/samples/cloud-storage-source/README.md
  docs/eventing/samples/cloud-storage-source/index.md
  docs/eventing/samples/container-source/README.md
  docs/eventing/samples/container-source/index.md
  docs/eventing/samples/github-source/README.md
  docs/eventing/samples/github-source/index.md
  docs/eventing/samples/gitlab-source/README.md
  docs/eventing/samples/gitlab-source/index.md
  docs/eventing/samples/helloworld/README.md
  docs/eventing/samples/helloworld/_index.md
  docs/eventing/samples/helloworld/helloworld-go/README.md
  docs/eventing/samples/helloworld/helloworld-go/_index.md
  docs/eventing/samples/helloworld/helloworld-python/README.md
  docs/eventing/samples/helloworld/helloworld-python/_index.md
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/iot-core/index.md
  docs/eventing/samples/kafka/README.md
  docs/eventing/samples/kafka/_index.md
  docs/eventing/samples/kafka/binding/README.md
  docs/eventing/samples/kafka/binding/index.md
  docs/eventing/samples/kafka/channel/README.md
  docs/eventing/samples/kafka/channel/index.md
  docs/eventing/samples/kafka/source/README.md
  docs/eventing/samples/kafka/source/index.md
  docs/eventing/samples/parallel/README.md
  docs/eventing/samples/parallel/_index.md
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/_index.md
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/_index.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/index.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/index.md
  docs/eventing/samples/sequence/sequence-terminal/README.md
  docs/eventing/samples/sequence/sequence-terminal/index.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/index.md
Labels: approved, cla: yes, lgtm, size/XXL

#3471 Move community files to index.md
  community/annual_reports/README.md
  community/annual_reports/_index.md
  community/meetup/README.md
  community/meetup/_index.md
  community/samples/README.md
  community/samples/_index.md
  community/samples/serving/helloworld-clojure/README.md
  community/samples/serving/helloworld-clojure/index.md
  community/samples/serving/helloworld-dart/README.md
  community/samples/serving/helloworld-dart/index.md
  community/samples/serving/helloworld-deno/README.md
  community/samples/serving/helloworld-deno/index.md
  community/samples/serving/helloworld-elixir/README.md
  community/samples/serving/helloworld-elixir/index.md
  community/samples/serving/helloworld-haskell/README.md
  community/samples/serving/helloworld-haskell/index.md
  community/samples/serving/helloworld-java-micronaut/README.md
  community/samples/serving/helloworld-java-micronaut/index.md
  community/samples/serving/helloworld-java-quarkus/README.md
  community/samples/serving/helloworld-java-quarkus/index.md
  community/samples/serving/helloworld-r/README.md
  community/samples/serving/helloworld-r/index.md
  community/samples/serving/helloworld-rserver/README.md
  community/samples/serving/helloworld-rserver/index.md
  community/samples/serving/helloworld-rust/README.md
  community/samples/serving/helloworld-rust/index.md
  community/samples/serving/helloworld-swift/README.md
  community/samples/serving/helloworld-swift/index.md
  community/samples/serving/helloworld-vertx/README.md
  community/samples/serving/helloworld-vertx/index.md
  community/samples/serving/machinelearning-python-bentoml/README.md
  community/samples/serving/machinelearning-python-bentoml/index.md
Labels: approved, cla: yes, lgtm, size/XXL

#3465 Drop net-istio dependencies
  go.mod
  go.sum
  hack/tools.go
  test/e2e-tests.sh
  vendor/knative.dev/net-istio/LICENSE
  vendor/knative.dev/net-istio/third_party/download-istio.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/README.md
  vendor/knative.dev/net-istio/third_party/istio-stable/install-istio.sh
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-ci-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-ci-no-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-kind-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-kind-no-mesh.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/istio-minimal.yaml
  vendor/knative.dev/net-istio/third_party/istio-stable/placeholder.go
  vendor/knative.dev/net-istio/third_party/placeholder.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3479 Fix API doc generator to properly link to duck, networking
  docs/reference/api/eventing/eventing.md
  docs/reference/api/serving.md
  hack/reference-docs-gen-config.json
Labels: approved, cla: yes, lgtm, size/L

#3466 Simplify installation istio for Knative
  docs/install/installing-istio.md
Labels: approved, cla: yes, lgtm, size/S

#3360 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S, triage/needs-eng-input

#3482 Fix extraneous ".md" link
  docs/install/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3480 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#3472 Add frontmatter to avoid rendering infrastructure description files
  DEVELOPMENT.md
  README.md
  blog/README.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#3487 Fix invalid link for autoscaling README
  docs/serving/_index.md
Labels: approved, cla: yes, lgtm, size/XS

#3478 Add metrics api docs
  docs/_index.md
  docs/eventing/_index.md
  docs/eventing/metrics.md
  docs/serving/_index.md
  docs/serving/metrics.md
Labels: approved, cla: yes, lgtm, size/L

#3491 Update knative-offerings.md
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm

#3468 Update knative-offerings.md
  docs/knative-offerings.md
Labels: approved, cla: yes, lgtm, size/XS

#3483 Second round of broker doc updates
  docs/eventing/broker/_index.md
  docs/eventing/broker/broker-event-delivery.md
  docs/eventing/broker/broker-types.md
  docs/eventing/broker/configmaps/broker-configmaps.md
  docs/eventing/broker/create-mtbroker.md
  docs/eventing/broker/example-mtbroker.md
  docs/eventing/broker/kafka-broker/_index.md
  docs/eventing/broker/triggers/_index.md
  docs/eventing/event-delivery.md
Labels: approved, cla: yes, lgtm, size/L

#3494 Follow up comments on broker docs
  docs/eventing/broker/_index.md
  docs/eventing/broker/broker-event-delivery.md
  docs/eventing/broker/create-mtbroker.md
Labels: approved, cla: yes, lgtm, size/S

#3493 Updating the docs for tls.enabled
  docs/eventing/samples/kafka/channel/index.md
Labels: approved, cla: yes, lgtm, size/S

#3486 blog post for knative release 0.22
  blog/releases/announcing-knative-v0-22-release.md
Labels: approved, cla: yes, lgtm, size/L

#3028 Add information on sharing logs to local disk
  docs/install/collecting-logs/_index.md
Labels: approved, cla: yes, lgtm, size/M, status/blocked, triage/needs-eng-input, ¯\_(ツ)_/¯

#3437 Consolidate all "docs" help info into single location
  CONTRIBUTING.md
  DEVELOPMENT.md
  blog/README.md
  docs/reference/api/README.md
  docs/smoketest.md
  help/_index.md
  help/contributor/_index.md
  help/contributor/gettingstarted.md
  help/contributor/how-to/_index.md
  help/contributor/how-to/codesamples.md
  help/contributor/how-to/formatting.md
  help/contributor/how-to/frontmatter.md
  help/contributor/how-to/github.md
  help/contributor/how-to/shortcodes.md
  help/contributor/how-to/structure.md
  help/contributor/how-to/styleguide.md
  help/contributor/new-blog/_index.md
  help/contributor/new-blog/blog-page.md
  help/contributor/new-docs/_index.md
  help/contributor/new-docs/docs-page.md
  help/contributor/new-docs/index-page.md
  help/contributor/publishing.md
  help/faqs.md
  help/maintainer/_index.md
  help/maintainer/building-api-output.md
  help/maintainer/docs-release-process.md
  help/maintainer/docs-repo-maintanence.md
  smoketest.md
  template-_index-page.md
  template-blog-entry.md
  template-docs-page.md
Labels: approved, cla: yes, lgtm, size/XXL

#3498 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3492 Fix issue 3489 (update docs after tools move from eventing-contrib repo to eventing repo)
  docs/eventing/channels/channels.yaml
  docs/eventing/debugging/example.yaml
  docs/eventing/getting-started.md
  docs/eventing/samples/container-source/heartbeats-source.yaml
  docs/eventing/samples/container-source/index.md
  docs/eventing/samples/container-source/service.yaml
  docs/eventing/samples/github-source/index.md
  docs/eventing/samples/github-source/service.yaml
  docs/eventing/samples/gitlab-source/index.md
  docs/eventing/samples/helloworld/helloworld-go/_index.md
  docs/eventing/samples/helloworld/helloworld-python/_index.md
  docs/eventing/samples/iot-core/trigger.yaml
  docs/eventing/samples/kafka/binding/event-display.yaml
  docs/eventing/samples/kafka/binding/index.md
  docs/eventing/samples/kafka/channel/000-ksvc.yaml
  docs/eventing/samples/kafka/source/event-display.yaml
  docs/eventing/samples/kafka/source/index.md
  docs/eventing/samples/parallel/multiple-branches/_index.md
  docs/eventing/samples/parallel/multiple-branches/event-display.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/_index.md
  docs/eventing/samples/parallel/mutual-exclusivity/event-display.yaml
  docs/eventing/samples/ping-source/index.md
  docs/eventing/samples/ping-source/service.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/event-display.yaml
  docs/eventing/samples/sequence/sequence-reply-to-event-display/index.md
  docs/eventing/samples/sequence/sequence-reply-to-event-display/steps.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/event-display.yaml
  docs/eventing/samples/sequence/sequence-reply-to-sequence/index.md
  docs/eventing/samples/sequence/sequence-reply-to-sequence/steps.yaml
  docs/eventing/samples/sequence/sequence-terminal/index.md
  docs/eventing/samples/sequence/sequence-terminal/steps.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/display-trigger.yaml
  docs/eventing/samples/sequence/sequence-with-broker-trigger/index.md
  docs/eventing/samples/sequence/sequence-with-broker-trigger/steps.yaml
  docs/eventing/sources/_index.md
  docs/eventing/sources/apache-camel-source/display_resources.yaml
  docs/eventing/sources/containersource.md
  docs/eventing/sources/creating-event-sources/writing-event-source/06-yaml.md
  docs/eventing/sources/pingsource.md
  docs/eventing/sources/sinkbinding.md
  docs/install/upgrade-installation.md
  hack/gen-api-reference-docs.sh
  tutorials/katacoda/3-eventing-intro-channels/step2.md
  tutorials/katacoda/3-eventing-intro-channels/step3.md
  tutorials/katacoda/3-eventing-intro-channels/step4.md
  tutorials/katacoda/4-eventing-intro-broker/step2.md
Labels: approved, cla: yes, lgtm, size/L

#3504 Minor updates to improve docs
  docs/client/_index.md
  docs/concepts/_index.md
  docs/eventing/_index.md
  docs/eventing/flows/_index.md
  docs/eventing/flows/sequence/_index.md
  docs/eventing/flows/sequence/sequence-reply-to-event-display/event-display.yaml
  docs/eventing/flows/sequence/sequence-reply-to-event-display/index.md
  docs/eventing/flows/sequence/sequence-reply-to-event-display/ping-source.yaml
  docs/eventing/flows/sequence/sequence-reply-to-event-display/sequence-reply-to-event-display.png
  docs/eventing/flows/sequence/sequence-reply-to-event-display/sequence.yaml
  docs/eventing/flows/sequence/sequence-reply-to-event-display/steps.yaml
  docs/eventing/flows/sequence/sequence-reply-to-sequence/event-display.yaml
  docs/eventing/flows/sequence/sequence-reply-to-sequence/index.md
  docs/eventing/flows/sequence/sequence-reply-to-sequence/ping-source.yaml
  docs/eventing/flows/sequence/sequence-reply-to-sequence/sequence-reply-to-sequence.png
  docs/eventing/flows/sequence/sequence-reply-to-sequence/sequence1.yaml
  docs/eventing/flows/sequence/sequence-reply-to-sequence/sequence2.yaml
  docs/eventing/flows/sequence/sequence-reply-to-sequence/steps.yaml
  docs/eventing/flows/sequence/sequence-terminal/index.md
  docs/eventing/flows/sequence/sequence-terminal/ping-source.yaml
  docs/eventing/flows/sequence/sequence-terminal/sequence-terminal.png
  docs/eventing/flows/sequence/sequence-terminal/sequence.yaml
  docs/eventing/flows/sequence/sequence-terminal/steps.yaml
  docs/eventing/flows/sequence/sequence-with-broker-trigger/display-trigger.yaml
  docs/eventing/flows/sequence/sequence-with-broker-trigger/index.md
  docs/eventing/flows/sequence/sequence-with-broker-trigger/ping-source.yaml
  docs/eventing/flows/sequence/sequence-with-broker-trigger/sequence-with-broker-trigger.png
  docs/eventing/flows/sequence/sequence-with-broker-trigger/sequence.yaml
  docs/eventing/flows/sequence/sequence-with-broker-trigger/steps.yaml
  docs/eventing/flows/sequence/sequence-with-broker-trigger/trigger.yaml
  docs/eventing/samples/sequence/_index.md
  docs/install/_index.md
  docs/knative-offerings.md
  docs/serving/_index.md
  docs/uninstall.md
Labels: approved, cla: yes, lgtm, size/M

#3503 Add the GitHub Issue Comment source to the list of event sources
  docs/eventing/sources/_index.md
Labels: approved, cla: yes, kind/eventing, lgtm, size/XS

#3497 fixes #3462: update doc for setting up custom domain per service
  docs/serving/creating-domain-mappings.md
  docs/serving/services/using-a-custom-domain-per-service.md
Labels: approved, cla: yes, lgtm, size/M

#3515 Improve upgrade docs
  docs/client/_index.md
  docs/eventing/_index.md
  docs/install/upgrade-installation-with-operator.md
  docs/knative-offerings.md
  docs/serving/_index.md
  docs/upgrade/_index.md
  docs/upgrade/upgrade-installation-with-operator.md
  docs/upgrade/upgrade-installation.md
Labels: approved, cherrypick-0.22, cla: yes, lgtm, size/L
