Repository knative/docs, pull requests merged in 2021-09, with the labels that each got.

#4171 Added .md extension where missing
  docs/admin/collecting-logs/README.md
  docs/admin/collecting-metrics/eventing-metrics/metrics.md
  docs/admin/eventing/broker-configuration.md
  docs/admin/install/README.md
  docs/admin/install/eventing/eventing-installation-files.md
  docs/admin/install/installing-istio.md
  docs/admin/install/operator/configuring-serving-cr.md
  docs/admin/install/serving/install-serving-with-yaml.md
  docs/admin/install/serving/serving-installation-files.md
  docs/admin/serving/feature-flags.md
Labels: size/M, lgtm, cla: yes, approved

#4102 Add pointer in case the service cannot be resolved
  docs/getting-started/first-service.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4156 Style changes
  docs/developer/serving/services/custom-domains.md
Labels: size/M, lgtm, cla: yes, approved

#4173 Changed HTML links to Markdown
  docs/client/README.md
  docs/client/install-kn.md
  docs/eventing/broker/README.md
  docs/eventing/channels/README.md
  docs/getting-started/first-autoscale.md
  docs/getting-started/first-broker.md
  docs/getting-started/first-source.md
  docs/getting-started/first-traffic-split.md
  docs/getting-started/first-trigger.md
  docs/snippets/dns.md
  docs/snippets/install-kn.md
Labels: size/M, lgtm, cla: yes, approved

#4152 Add new release blog for v0.25
  blog/releases/announcing-knative-v0-25-release.md
Labels: size/L, lgtm, cla: yes, approved

#4182 Fix inaccurate description of `default-br-config`
  docs/admin/eventing/broker-configuration.md
Labels: lgtm, size/S, cla: yes, approved

#4185 Style edits to Duck Typing topic
  docs/developer/concepts/duck-typing.md
Labels: size/M, lgtm, cla: yes, approved

#4187 Add link to code of conduct
  docs/help/contributor/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4186 Fix exposed links
  docs/developer/eventing/sinks/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4175 drop extra stale issue workflow file
  .github/workflows/stale.yaml
Labels: size/M, lgtm, cla: yes, approved

#4046 Updating quickstart to use the plugin
  docs/getting-started/README.md
  docs/snippets/install-kn.md
  docs/snippets/quickstart-install.md
Labels: size/M, lgtm, cla: yes, approved

#4146 Delete duplicate deploying-from-private-registry.md file
  docs/admin/install/operator/configuring-serving-cr.md
  docs/developer/serving/deploying-from-private-registry.md
  docs/serving/deploying-from-private-registry.md
Labels: size/M, lgtm, cla: yes, approved

#4195 Typo in quickstart markdown link
  docs/snippets/install-kn.md
Labels: size/XS, lgtm, cla: yes, approved

#4194 add kn quickstart 0.25
  docs/getting-started/README.md
  docs/snippets/install-kn.md
  docs/snippets/quickstart-install.md
Labels: size/M, lgtm, cla: yes, approved

#4176 update brew command for kn
  docs/snippets/install-kn.md
Labels: size/XS, lgtm, cla: yes, approved

#4199 Update otel-collector-config configmap
  docs/admin/collecting-metrics/collector.yaml
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4189 set v1.19 as minimum k8s version
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, cla: yes, approved

#4214 Add .md extension to internal links
  docs/help/contributor/github.md
  docs/help/contributor/structure.md
  docs/help/contributor/templates/template-procedure.md
Labels: size/XS, lgtm, cla: yes, approved

#4210 Update first-trigger.md
  docs/getting-started/first-trigger.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4221 Remove iot-core sample
  config/nav.yml
  docs/eventing/samples/iot-core/README.md
  docs/eventing/samples/iot-core/gcp-pubsub-source.yaml
  docs/eventing/samples/iot-core/generator/main.go
  docs/eventing/samples/iot-core/trigger.yaml
Labels: size/L, lgtm, cla: yes, approved

#4162 avoid 'should' in documentation
  docs/help/contributor/style-guide/word-and-phrase-list.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4209 Add how to create custom domains with kn domain
  docs/developer/serving/services/custom-domains.md
Labels: lgtm, size/S, cla: yes, approved

#4223 Updates links in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4227 Add missing .md to links in Docs folder (top level)
  config/redirects.yml
  docs/_index.md
  docs/admin/install/installing-istio.md
  docs/samples.md
Labels: size/M, lgtm, cla: yes, approved

#4229 Correct kubectl expected output
  docs/getting-started/first-traffic-split.md
Labels: size/XS, lgtm, cla: yes, approved

#4236 rename mkdocs branch to main
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  .github/workflows/mkdocs-strict-verify.yaml
  docs/help/contributor/README.md
  docs/snippets/links/main-docs-branch-link.md
  golang/docs.html
  mkdocs.yml
Labels: size/M, lgtm, cla: yes, approved

#4242 [release-0.24] mkdocs -> main
  docs/help/contributor/README.md
  docs/snippets/links/main-docs-branch-link.md
  golang/docs.html
  mkdocs.yml
Labels: lgtm, size/S, cla: yes, approved

#4184 docs: add github event source install instructions
  docs/eventing/samples/github-source/README.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4244 We haven't required Istio for 2 1/2 years
  docs/serving/README.md
Labels: size/XS, lgtm, cla: yes, approved

#4071 set namespace to default before the installation verification
  docs/admin/install/knative-with-operators.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4234 Add redirect for a moved file to prevent user 404s
  config/redirects.yml
Labels: kind/bug, size/XS, lgtm, cla: yes, approved

#4232 Fix formatting for create custom domains with kn domain
  docs/developer/serving/services/custom-domains.md
Labels: size/M, lgtm, cla: yes, approved

#4228 Enhance DLQ CloudEvents with destination
  docs/developer/eventing/event-delivery.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4254 Adding container-freezer aliases
  golang/_redirects
  golang/container-freezer.html
Labels: size/XS, lgtm, cla: yes, approved

#4251 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, lgtm, cla: yes, approved

#4250 Update accessing-traces.md
  docs/serving/accessing-traces.md
Labels: lgtm, size/S, cla: yes, approved

#4258 Add code excerpt docs guidelines
  docs/help/contributor/style-guide/documenting-code.md
Labels: lgtm, size/S, cla: yes, approved

#4259 Moved metrics to dev guide
  config/nav.yml
  docs/admin/collecting-metrics/serving-metrics/metrics.md
  docs/developer/serving/services/service-metrics.md
Labels: size/M, lgtm, cla: yes, approved

#4266 document serving's revision garbage collection
  config/nav.yml
  docs/admin/serving/revision-gc.md
  docs/serving/revision-gc.md
Labels: size/L, lgtm, cla: yes, approved

#4264 Adding ingres-class annotation docs
  config/nav.yml
  docs/developer/serving/services/ingress-class.md
Labels: lgtm, size/S, cla: yes, approved

#4116 Edit PingSource docs
  config/nav.yml
  docs/developer/eventing/sources/ping-source/README.md
  docs/developer/eventing/sources/ping-source/reference.md
Labels: size/L, lgtm, cla: yes, approved

#4267 fix for issue-4233: correctly sourced collector with a fix
  docs/admin/collecting-metrics/README.md
  docs/admin/collecting-metrics/collector.yaml
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4268 fix for issue-4252: fixing content for serving metrics under activato…
  docs/admin/collecting-metrics/serving-metrics/metrics.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4273 include documentation about the httpOption annotation
  config/nav.yml
  docs/developer/serving/services/http-option.md
Labels: lgtm, size/S, cla: yes, approved

#4285 Adding COC doc
  CODE-OF-CONDUCT.md
Labels: size/M, lgtm, cla: yes, approved

#4202 Style edits to Apache Kafka Source Example topic
  docs/developer/eventing/sources/kafka-source/README.md
Labels: size/L, lgtm, cla: yes, approved

#4270 fix for issue-4269: fixing deadlink in knative operator page
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, cla: yes, ok-to-test, approved

#4110 Add sample for custom routing with Kong Gateway
  config/nav.yml
  docs/serving/samples/README.md
  docs/serving/samples/kong-routing-go/Dockerfile
  docs/serving/samples/kong-routing-go/README.md
  docs/serving/samples/kong-routing-go/images/kong-routing-sample-flow.png
  docs/serving/samples/kong-routing-go/routing.yaml
  docs/serving/samples/kong-routing-go/sample.go
  docs/serving/samples/kong-routing-go/sample.yaml
Labels: size/L, lgtm, cla: yes, ok-to-test, approved

#4300 Disable failing integration tests
  test/e2e/main.go
  test/e2e/sampleapp_test.go
  test/e2e/sampleapptestbase.go
  test/flag.go
  test/sampleapp/config.go
  test/sampleapp/config.yaml
Labels: size/L, lgtm, cla: yes, approved

#3972 fixed indentation issue with heading
  docs/serving/samples/hello-world/helloworld-python/README.md
Labels: lgtm, size/S, cla: yes, ok-to-test, approved

#4288 Update release docs
  help/maintainer/docs-release-process.md
Labels: size/L, lgtm, cla: yes, approved

#4301 improve ApiServerSource doc
  config/nav.yml
  docs/developer/eventing/sources/apiserversource/README.md
  docs/developer/eventing/sources/apiserversource/getting-started.md
  docs/developer/eventing/sources/apiserversource/reference.md
  docs/developer/eventing/sources/ping-source/README.md
Labels: size/L, lgtm, cla: yes, approved

#4294 PingSource is v1
  docs/developer/eventing/sources/ping-source/ping-source-binary.yaml
  docs/developer/eventing/sources/ping-source/ping-source.yaml
  docs/eventing/flows/sequence/sequence-reply-to-event-display/README.md
  docs/eventing/flows/sequence/sequence-reply-to-event-display/ping-source.yaml
  docs/eventing/flows/sequence/sequence-reply-to-sequence/README.md
  docs/eventing/flows/sequence/sequence-reply-to-sequence/ping-source.yaml
  docs/eventing/flows/sequence/sequence-terminal/README.md
  docs/eventing/flows/sequence/sequence-terminal/ping-source.yaml
  docs/eventing/flows/sequence/sequence-with-broker-trigger/README.md
  docs/eventing/flows/sequence/sequence-with-broker-trigger/ping-source.yaml
  docs/eventing/samples/parallel/multiple-branches/README.md
  docs/eventing/samples/parallel/multiple-branches/ping-source.yaml
  docs/eventing/samples/parallel/mutual-exclusivity/README.md
  docs/eventing/samples/parallel/mutual-exclusivity/ping-source.yaml
  tutorials/katacoda/3-eventing-intro-channels/step2.md
  tutorials/katacoda/3-eventing-intro-channels/step3.md
  tutorials/katacoda/3-eventing-intro-channels/step4.md
Labels: size/M, lgtm, cla: yes, approved

#4253 Document Defaults ConfigMap
  config/nav.yml
  docs/admin/serving/config-defaults.md
Labels: size/L, lgtm, cla: yes, approved

#4302 Disable section index feature
  mkdocs.yml
Labels: size/XS, lgtm, cla: yes, approved

#4304 Clean up sources docs
  docs/developer/eventing/sources/apiserversource/README.md
  docs/developer/eventing/sources/apiserversource/getting-started.md
  docs/developer/eventing/sources/apiserversource/reference.md
  docs/developer/eventing/sources/containersource/README.md
  docs/developer/eventing/sources/containersource/reference.md
  docs/developer/eventing/sources/ping-source/README.md
  docs/developer/eventing/sources/ping-source/reference.md
  docs/developer/eventing/sources/sinkbinding/README.md
  docs/developer/eventing/sources/sinkbinding/getting-started.md
  docs/developer/eventing/sources/sinkbinding/reference.md
Labels: size/L, lgtm, cla: yes, approved

#4272 include documentation about certificate class annotation
  config/nav.yml
  docs/developer/serving/services/certificate-class.md
Labels: lgtm, size/S, cla: yes, approved

#4231 Add doc for kreference-mapping
  docs/eventing/experimental-features.md
Labels: size/L, lgtm, cla: yes, kind/eventing, approved

#4295 fix eventing getting started doc
  docs/eventing/getting-started.md
Labels: lgtm, size/S, cla: yes, approved

#4308 [eventing] fix broken link to ref doc
  docs/eventing/channels/create-default-channel.md
  docs/eventing/channels/subscriptions.md
Labels: size/XS, lgtm, cla: yes, approved
