Repository knative/docs, pull requests merged in 2022-09, with the labels that each got.

#5211 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#5213 Add double quote for version number in KnativeServing CR
  docs/install/operator/configuring-serving-cr.md
Labels: size/XS, lgtm, approved

#5214 :broom: Quarterly release cadence
  contribute-to-docs/what-to-contribute/creating-blog-posts.md
Labels: size/XS, lgtm, approved

#5215 fix: docs indents and code highlights
  code-samples/serving/hello-world/helloworld-go/README.md
Labels: size/L, lgtm, approved

#5219 updated ping source with kn base64 example
  docs/eventing/sources/ping-source/README.md
Labels: lgtm, size/S, approved, hacktoberfest-accepted

#5223 [main] Format Go code
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/client/client_observed.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/client/observability.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/json/data_observed.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/data_observed.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/xml/data_observed.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/google/uuid/node_js.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/google/uuid/node_net.go
  code-samples/eventing/helloworld/helloworld-go/vendor/github.com/pkg/errors/go113.go
  code-samples/eventing/helloworld/helloworld-go/vendor/go.opencensus.io/tag/profile_19.go
  code-samples/eventing/helloworld/helloworld-go/vendor/go.opencensus.io/tag/profile_not19.go
  code-samples/eventing/helloworld/helloworld-go/vendor/go.opencensus.io/trace/trace_go11.go
  code-samples/eventing/helloworld/helloworld-go/vendor/go.opencensus.io/trace/trace_nongo11.go
  code-samples/eventing/helloworld/helloworld-go/vendor/go.uber.org/zap/global_go112.go
  code-samples/eventing/helloworld/helloworld-go/vendor/go.uber.org/zap/global_prego112.go
Labels: lgtm, size/S, approved

#5221 Bump minimum kubernetes version to 1.23
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, approved

#5218 Fix wording in eventing getting started guide
  docs/getting-started/first-trigger.md
Labels: size/XS, lgtm, approved

#5209 Using RPS as scaling metric always requires an annotation
  docs/serving/autoscaling/rps-target.md
Labels: size/XS, lgtm, approved

#5228 Update docs to use batch/v1
  docs/eventing/custom-event-source/sinkbinding/create-a-sinkbinding.md
  docs/eventing/custom-event-source/sinkbinding/reference.md
Labels: size/XS, lgtm, approved

#5220 Fix issues in broker docs
  docs/eventing/brokers/broker-developer-config-options.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
Labels: triage/needs-eng-input, size/M, lgtm, kind/eventing, approved, hacktoberfest-accepted

#5230 Add SASL for KafkaSource docs
  docs/eventing/sources/kafka-source/README.md
Labels: size/L, lgtm, approved

#5242 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5244 Fix markdown rendering issue with brackets
  docs/eventing/sources/kafka-source/README.md
Labels: size/XS, lgtm, approved

#5241 Update ApiServerSource apiVersion in example.yaml
  docs/eventing/troubleshooting/example.yaml
Labels: size/XS, lgtm, approved

#5229 Fix sequence with broker image to show correct filter
  docs/eventing/flows/sequence/sequence-with-broker-trigger/sequence-with-broker-trigger.png
Labels: triage/needs-eng-input, size/XS, lgtm, kind/eventing, approved

#5247 Remove mentions of Google GCP from docs
  code-samples/eventing/cloud-audit-logs-source/README.md
  code-samples/eventing/cloud-pubsub-source/README.md
  code-samples/eventing/cloud-scheduler-source/README.md
  code-samples/eventing/cloud-storage-source/README.md
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/sources/README.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/M, lgtm, approved

#5246 Cleanup channel list
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/eventing/channels/generator/ReadmeTemplate.gomd
  docs/eventing/channels/generator/main.go
Labels: size/M, lgtm, approved

#5254 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5255 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
