Repository knative/docs, pull requests merged in 2022-11, with the labels that each got.

#5313 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5320 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5317 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5314 Adding a note or two on why binary is better
  docs/eventing/brokers/broker-types/kafka-broker/README.md
Labels: size/XS, lgtm, approved

#5319 Update README.md
  docs/eventing/sources/kafka-source/README.md
Labels: size/XS, lgtm, approved

#5318 Update instructions for using temporary DNS in installation section
  docs/snippets/temporary-dns.md
Labels: size/XS, lgtm, approved

#5324 add scaling-group golang redirect
  golang/_redirects
  golang/scaling-group.html
Labels: size/XS, lgtm, approved

#5326 chore: update security report detail
  docs/reference/security/README.md
Labels: size/XS, lgtm, approved

#5330 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5323 Fix channel links
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
Labels: lgtm, size/S, approved

#5332 Remove information about strict-subscriber flag again
  config/nav.yml
  docs/eventing/experimental-features/README.md
  docs/eventing/experimental-features/strict-subscriber.md
Labels: size/M, lgtm, approved

#5333 fix broken link for on cluster build
  docs/functions/building-functions.md
Labels: size/XS, lgtm, approved

#5335 Fix stale links in functions-templates-intro snippet
  docs/snippets/functions-templates-intro.md
Labels: lgtm, size/S, approved

#5327 chore: fix typos in new trigger filter docs
  docs/eventing/experimental-features/new-trigger-filters.md
Labels: size/XS, lgtm, approved

#5336 fix(functions): include --registry flag for `run`
  docs/snippets/proc-running-function.md
Labels: size/XS, lgtm, approved

#5329 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved
