Repository knative/docs, pull requests merged in 2022-12, with the labels that each got.

#5341 Advertise first Knative Virtual Office Hour 2022/12/09
  blog/config/nav.yml
  blog/docs/events/images/virtual-office-hour-12-2022-with-text.jpg
  blog/docs/events/virtual-office-hour-12-2022.md
Labels: size/M, lgtm, approved

#5344 Fix the documentation URL for the language pack
  docs/functions/language-packs.md
Labels: size/XS, lgtm, approved

#5345 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5354 drop release 1.5 as it's no longer supported
  hack/build.sh
Labels: size/XS, lgtm, approved

#5355 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#5359 Guard1.9
  docs/serving/app-security/security-guard-about.md
  docs/serving/app-security/security-guard-example-alerts.md
  docs/serving/app-security/security-guard-install.md
Labels: size/M, lgtm, approved

#5366 Removes maven-wrapper.jar from repository
  .gitignore
  code-samples/community/serving/helloworld-java-micronaut/.mvn/wrapper/maven-wrapper.jar
  code-samples/community/serving/helloworld-java-quarkus/.mvn/wrapper/maven-wrapper.jar
  code-samples/community/serving/helloworld-java-quarkus/README.md
  code-samples/serving/cloudevents/cloudevents-spring/.mvn/wrapper/maven-wrapper.jar
  code-samples/serving/hello-world/helloworld-java-spark/.mvn/wrapper/maven-wrapper.jar
  code-samples/serving/hello-world/helloworld-java-spark/README.md
  code-samples/serving/hello-world/helloworld-java-spring/.mvn/wrapper/maven-wrapper.jar
  code-samples/serving/hello-world/helloworld-java-spring/README.md
Labels: size/XS, lgtm, approved
