Repository knative/docs, pull requests merged in 2022-01, with the labels that each got.

#4607 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#4611 Update getting started to sslip default domain
  docs/getting-started/first-service.md
Labels: lgtm, size/S, approved

#4613 Fixing broken links for examples
  docs/samples/eventing.md
Labels: size/XS, lgtm, ok-to-test, approved

#4608 Fix bugs: delete indented code block in installing istio
  docs/install/serving/installing-istio.md
Labels: size/XS, lgtm, ok-to-test, approved

#4524 Redirect to Go package docs from a real browser
  golang/_redirects
  tools/redir-gen/main.go
  tools/redir-gen/redirtemplate.gohtml
Labels: size/M, lgtm, cla: yes, approved

#4618 Clean up operator configmap docs
  config/nav.yml
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
  docs/install/operator/configuring-with-operator.md
Labels: size/L, lgtm, approved

#4614 Add documentation for freezer to knative docs
  docs/serving/configuration/deployment.md
Labels: lgtm, size/S, ok-to-test, approved

#4623 Build client docs
  config/nav.yml
  docs/reference/client/README.md
  hack/build.sh
  hack/macros.py
  netlify.toml
Labels: lgtm, size/S, approved

#4628 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/simplelru/LICENSE
  third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/simplelru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/simplelru/simplelru/lru_interface.go
  third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/simplelru/simplelru/LICENSE
  third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/simplelru/simplelru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/knative/docs/third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/simplelru/simplelru/simplelru/lru_interface.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#4629 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#4622 Updated link
  docs/install/knative-offerings.md
Labels: size/XS, lgtm, ok-to-test, approved

#4636 Iter8 load testing tutorial
  docs/samples/README.md
Labels: size/XS, lgtm, ok-to-test, approved

#4627 Mention optional attributes for CloudEvents in event sources overview
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, approved

#4634 Edit Operator docs
  config/nav.yml
  docs/install/operator/knative-with-operators.md
  docs/install/upgrade/upgrade-installation-with-operator.md
  docs/snippets/dns.md
  docs/snippets/real-dns-operator.md
  docs/snippets/real-dns-yaml.md
Labels: lgtm, size/XL, approved

#4638 Fixes link to client reference
  hack/macros.py
Labels: size/XS, lgtm, approved

#4639 [release-1.1] Fixes link to client reference
  hack/macros.py
Labels: size/XS, lgtm, approved

#4514 add stable window documentatino to "scale-bounds"
  docs/serving/autoscaling/scale-bounds.md
Labels: size/M, lgtm, cla: yes, ok-to-test, approved

#4642 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#4641 fix rss feed xml with correct url links
  blog/mkdocs.yml
Labels: size/XS, lgtm, approved

#4635 Add documentation for new trigger filters
  config/nav.yml
  docs/eventing/experimental-features.md
  docs/eventing/experimental-features/README.md
  docs/eventing/experimental-features/delivery-retryafter.md
  docs/eventing/experimental-features/delivery-timeout.md
  docs/eventing/experimental-features/kreference-group.md
  docs/eventing/experimental-features/kreference-mapping.md
  docs/eventing/experimental-features/new-trigger-filters.md
  docs/eventing/experimental-features/strict-subscriber.md
Labels: lgtm, size/XL, approved

#4645 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#4653 Fix example to immediately collect any inactive revision (#4652)
  docs/serving/configuration/revision-gc.md
Labels: size/XS, lgtm, ok-to-test, approved

#4649 TriggerMesh provides both on-premises and hosted Knative support.
  docs/install/knative-offerings.md
Labels: size/XS, lgtm, ok-to-test, approved

#4656 Change DNS to sslip in code examples
  docs/getting-started/first-autoscale.md
  docs/getting-started/first-source.md
  docs/getting-started/first-traffic-split.md
  docs/snippets/quickstart-install.md
Labels: size/M, lgtm, approved

#4657 Make kourier first network layer
  docs/install/operator/knative-with-operators.md
Labels: size/M, lgtm, approved

#4648 Updated HelloWorld C# sample to the latest 6.0 version #4643
  code-samples/serving/hello-world/helloworld-csharp/Dockerfile
  code-samples/serving/hello-world/helloworld-csharp/Program.cs
  code-samples/serving/hello-world/helloworld-csharp/Properties/launchSettings.json
  code-samples/serving/hello-world/helloworld-csharp/README.md
  code-samples/serving/hello-world/helloworld-csharp/Startup.cs
  code-samples/serving/hello-world/helloworld-csharp/helloworld-csharp.csproj
Labels: size/L, lgtm, ok-to-test, approved

#4658 Update min version requirement
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, approved

#4647 Release notes 1.1
  blog/config/nav.yml
  blog/docs/releases/_template-announcing-knative-v1-X-release.txt
  blog/docs/releases/announcing-knative-v1-1-release.md
Labels: size/L, lgtm, approved

#4659 Add pvc extension
  docs/serving/configuration/feature-flags.md
Labels: size/M, lgtm, approved

#4670 Remove unsupported Ambassador networking layer from docs
  docs/install/operator/knative-with-operators.md
  docs/install/serving/install-serving-with-yaml.md
  docs/install/uninstall.md
  docs/serving/README.md
  docs/serving/using-auto-tls.md
Labels: size/L, lgtm, approved

#4665 Update the docs regarding using `spec.deployment` to override the resources
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: size/M, lgtm, approved

#4673 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#4666 chore(eventing): fix typo in channel docs
  docs/eventing/channels/channel-types-defaults.md
Labels: size/XS, lgtm, ok-to-test, approved

#4674 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#4676 Update release to 1.2 in build script
  hack/build.sh
Labels: size/XS, lgtm, approved

#4677 Add redirect for operator install page
  config/redirects.yml
Labels: size/XS, lgtm, approved

#4675 Add release notes to blog for 1.2
  blog/config/nav.yml
  blog/docs/releases/announcing-knative-v1-2-release.md
Labels: size/L, lgtm, approved

#4679 Fix typo
  blog/docs/releases/announcing-knative-v1-2-release.md
Labels: size/XS, lgtm, approved
