Repository knative/docs, pull requests merged in 2022-05, with the labels that each got.

#4953 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#4951 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#4950 Change warning to note
  docs/getting-started/first-autoscale.md
Labels: size/XS, lgtm, approved

#4934 Instruction on how to override the labels and annotations for services
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: lgtm, size/S, approved

#4957 Configure the servers for istio gateways
  docs/install/operator/configuring-serving-cr.md
Labels: size/M, lgtm, approved

#4960 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#4959 Remove the deprecated configuration of system resources
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: size/L, lgtm, approved

#4963 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#4965 Add delivery spec Broker docs
  docs/eventing/configuration/broker-configuration.md
Labels: size/M, lgtm, approved

#4968 Fix typo in subscriptions.md
  docs/eventing/channels/subscriptions.md
Labels: size/XS, lgtm, ok-to-test, approved

#4973 kn CLI install should use tap instead of compile for brew install
  docs/snippets/install-kn.md
  docs/snippets/quickstart-install.md
Labels: lgtm, size/S, approved

#4971 Fix eventing spec links
  docs/eventing/broker/README.md
  docs/eventing/sinks/README.md
Labels: size/XS, lgtm, approved

#4974 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#4970 Fix dead link to Broker spec
  docs/eventing/broker/README.md
Labels: size/XS, lgtm, approved

#4977 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#4979 Suggested improvements for getting started
  docs/getting-started/README.md
  docs/getting-started/getting-started-eventing.md
  docs/getting-started/quickstart-install.md
  docs/snippets/quickstart-install.md
Labels: size/L, lgtm, approved

#4980 Fix values and general cleanup
  config/nav.yml
  docs/serving/using-a-custom-domain.md
  docs/serving/using-auto-tls.md
Labels: size/L, lgtm, approved
