Repository knative/docs, pull requests merged in 2022-06, with the labels that each got.

#4983 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#4984 Update upgrading docs versions
  docs/install/upgrade/upgrade-installation-with-operator.md
  docs/install/upgrade/upgrade-installation.md
Labels: size/M, lgtm, approved

#4982 Removes blog link to old knative kind setup
  blog/config/nav.yml
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
Labels: size/XS, lgtm, approved

#4995 Add the instruction on how to override/add env vars for containers
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: size/M, lgtm, approved

#4999 cut release 1.5, remove extra vars for build
  contribute-to-docs/docs-release-process.md
  hack/build.sh
Labels: lgtm, size/S, approved

#4962 Bumped the CPU requirements
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, ok-to-test, approved

#5001 Link to new KafkaChannel's docs
  docs/eventing/channels/channels-crds.md
Labels: size/XS, lgtm, approved

#5002 Fix minor tag bug
  docs/serving/traffic-management.md
Labels: size/XS, lgtm, approved

#5005 [release-1.4] Correct the instruction on system resource settings
  docs/install/operator/configuring-eventing-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: size/L, lgtm, approved

#5006 Fixes kafkasource bugs
  docs/eventing/sources/kafka-source/README.md
Labels: lgtm, size/S, approved

#5007 Include blog post for release-1.5
  blog/config/nav.yml
  blog/docs/releases/announcing-knative-v1-5-release.md
Labels: size/L, lgtm, approved

#5010 Fix docs typo regarding runtimeClassName Extension
  docs/serving/configuration/feature-flags.md
Labels: size/XS, lgtm, needs-ok-to-test, approved

#5015 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#4966 Add per-revision examples to serving config
  docs/serving/configuration/config-defaults.md
Labels: lgtm, size/XL, approved

#5025 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5026 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5018 Remove duplicate getting started, tidy up info
  config/nav.yml
  config/redirects.yml
  docs/eventing/README.md
  docs/eventing/getting-started.md
  docs/getting-started/getting-started-eventing.md
Labels: size/L, lgtm, approved

#5029 Remove unused heading from TOC
  blog/docs/releases/announcing-knative-v1-5-release.md
Labels: size/XS, lgtm, approved

#5021 Adds copyright info to some hack scripts
  hack/build.sh
  hack/macros.py
  hack/mkdocs.sh
Labels: size/M, lgtm, approved

#5032 Rename home page buttons
  overrides/home.html
Labels: size/XS, lgtm, approved

#5017 Remove katacoda docs
  tutorials/katacoda/1-serving-intro/finish.md
  tutorials/katacoda/1-serving-intro/index.json
  tutorials/katacoda/1-serving-intro/intro.md
  tutorials/katacoda/1-serving-intro/scripts/install-dependencies.sh
  tutorials/katacoda/1-serving-intro/step1.md
  tutorials/katacoda/1-serving-intro/step2.md
  tutorials/katacoda/1-serving-intro/step3.md
  tutorials/katacoda/2-serving-intro-yaml/finish.md
  tutorials/katacoda/2-serving-intro-yaml/index.json
  tutorials/katacoda/2-serving-intro-yaml/intro.md
  tutorials/katacoda/2-serving-intro-yaml/scripts/install-dependencies.sh
  tutorials/katacoda/2-serving-intro-yaml/step1.md
  tutorials/katacoda/2-serving-intro-yaml/step2.md
  tutorials/katacoda/2-serving-intro-yaml/step3.md
  tutorials/katacoda/3-eventing-intro-channels/assets/1to1.png
  tutorials/katacoda/3-eventing-intro-channels/assets/1toN.png
  tutorials/katacoda/3-eventing-intro-channels/assets/Nto1.png
  tutorials/katacoda/3-eventing-intro-channels/assets/channel.png
  tutorials/katacoda/3-eventing-intro-channels/assets/sequence.png
  tutorials/katacoda/3-eventing-intro-channels/finish.md
  tutorials/katacoda/3-eventing-intro-channels/index.json
  tutorials/katacoda/3-eventing-intro-channels/intro.md
  tutorials/katacoda/3-eventing-intro-channels/scripts/install-dependencies.sh
  tutorials/katacoda/3-eventing-intro-channels/step1.md
  tutorials/katacoda/3-eventing-intro-channels/step2.md
  tutorials/katacoda/3-eventing-intro-channels/step3.md
  tutorials/katacoda/3-eventing-intro-channels/step4.md
  tutorials/katacoda/4-eventing-intro-broker/assets/broker-eg.png
  tutorials/katacoda/4-eventing-intro-broker/assets/broker.png
  tutorials/katacoda/4-eventing-intro-broker/finish.md
  tutorials/katacoda/4-eventing-intro-broker/index.json
  tutorials/katacoda/4-eventing-intro-broker/intro.md
  tutorials/katacoda/4-eventing-intro-broker/scripts/install-dependencies.sh
  tutorials/katacoda/4-eventing-intro-broker/step1.md
  tutorials/katacoda/4-eventing-intro-broker/step2.md
  tutorials/katacoda/4-eventing-intro-broker/step3.md
Labels: lgtm, size/XXL, approved

#5028 Fix broken snippet
  docs/getting-started/README.md
  docs/getting-started/quickstart-install.md
  docs/install/client/install-kn.md
  docs/install/quickstart-install.md
  docs/snippets/install-kn.md
  docs/snippets/quickstart-install.md
  docs/snippets/quickstart-prereqs.md
Labels: size/L, lgtm, approved

#5037 [release-1.5] Add the description on the supported versions for Serving and Eventing
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#5009 Get rid of refs to old KafkaChannels
  code-samples/eventing/kafka/channel/README.md
  code-samples/eventing/kafka/resetoffset/README.md
  config/redirects.yml
  docs/eventing/channels/channels-crds.md
  docs/samples/eventing.md
Labels: size/L, lgtm, approved

#5049 Renamed Community docs section to Contributing, added func contrib docs
  config/nav.yml
  config/redirects.yml
  docs/contributing/README.md
  docs/contributing/about.md
  docs/contributing/contributing.md
  docs/contributing/images/knative-audience.png
  docs/contributing/images/knative-audience.svg
  docs/contributing/images/knative-version.png
  docs/contributing/images/logo/cmyk/knative-logo-cmyk.ai
  docs/contributing/images/logo/cmyk/knative-logo-cmyk.eps
  docs/contributing/images/logo/cmyk/knative-logo-cmyk.jpg
  docs/contributing/images/logo/cmyk/knative-logo-cmyk.pdf
  docs/contributing/images/logo/cmyk/knative-logo-cmyk.png
  docs/contributing/images/logo/rgb/knative-logo-rgb.ai
  docs/contributing/images/logo/rgb/knative-logo-rgb.eps
  docs/contributing/images/logo/rgb/knative-logo-rgb.jpg
  docs/contributing/images/logo/rgb/knative-logo-rgb.pdf
  docs/contributing/images/logo/rgb/knative-logo-rgb.png
  docs/contributing/images/logo/style-guide.pdf
Labels: do-not-merge/hold, lgtm, size/S, approved

#5053 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#5059 Update blog post frontmatter format
  blog/config/nav.yml
  blog/docs/articles/build-deploy-manage-modern-serverless-workloads-using-knative-on-kubernetes.md
  blog/docs/articles/distributed-tracing.md
  blog/docs/articles/event-drive-app-knative-eventing-kogito.md
  blog/docs/articles/event-driven-image-bigquery-processing-pipelines.md
  blog/docs/articles/get-started-knative-eventing.md
  blog/docs/articles/highlighting-value-knative-c-suite.md
  blog/docs/articles/knative-v0-3-autoscaling-a-love-story.md
  blog/docs/articles/ko-fast-kubernetes-microservice-development-in-go.md
  blog/docs/articles/orchestrating-cloud-events-with.md
  blog/docs/articles/quickstart-with-knative.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
  blog/docs/articles/workflow-as-function-flow.md
  blog/docs/events/google-summer-of-code-2022.md
  blog/docs/releases/announcing-knative-1.0.md
  blog/docs/releases/knative-1.0.md
Labels: size/L, lgtm, approved

#5060 Adding more blog authors
  blog/docs/articles/highlighting-value-knative-c-suite.md
  blog/docs/articles/knative-v0-3-autoscaling-a-love-story.md
  blog/docs/events/google-summer-of-code-2022.md
Labels: size/XS, lgtm, approved

#4939 Migrate Kafka components installation to new components
  docs/eventing/channels/channels-crds.md
  docs/eventing/channels/channels.yaml
  docs/install/uninstall.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/M, lgtm, approved
