Repository knative/docs, pull requests merged in 2023-05, with the labels that each got.

#5544 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5546 Add installation troubleshooting page
  config/nav.yml
  docs/install/troubleshooting.md
Labels: size/L, lgtm, approved

#5539 Update the operator doc on versions
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#5554 create autoscale-go image
  .github/workflows/knative-docs-image.yaml
  docs/serving/autoscaling/autoscale-go/Dockerfile
  docs/serving/autoscaling/autoscale-go/go.mod
Labels: lgtm, size/S, approved

#5556 Fix build image workflow
  .github/workflows/knative-docs-image.yaml
Labels: size/XS, lgtm, approved

#5551 point to the new ghcr.io images
  blog/docs/articles/knative-serving-in-k0s.md
  blog/docs/articles/quickstart-with-knative.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
  docs/getting-started/first-service.md
  docs/getting-started/first-traffic-split.md
  docs/serving/app-security/security-guard-quickstart.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/autoscaling/autoscaler-types.md
  docs/serving/autoscaling/concurrency.md
  docs/serving/autoscaling/kpa-specific.md
  docs/serving/autoscaling/rps-target.md
  docs/serving/autoscaling/scale-bounds.md
  docs/serving/autoscaling/scale-to-zero.md
  docs/serving/configuration/config-defaults.md
  docs/serving/configuration/feature-flags.md
  docs/serving/deploying-from-private-registry.md
  docs/serving/services/creating-services.md
  docs/serving/services/using-queue-extensions.md
Labels: size/M, lgtm, approved

#5560 [release-1.8] update image refs - gcr.io/knative-samples no longer exists
  blog/docs/articles/quickstart-with-knative.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
  docs/getting-started/first-service.md
  docs/getting-started/first-traffic-split.md
  docs/serving/app-security/security-guard-quickstart.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/autoscaling/autoscaler-types.md
  docs/serving/autoscaling/concurrency.md
  docs/serving/autoscaling/container-freezer.md
  docs/serving/autoscaling/kpa-specific.md
  docs/serving/autoscaling/rps-target.md
  docs/serving/autoscaling/scale-bounds.md
  docs/serving/autoscaling/scale-to-zero.md
  docs/serving/configuration/config-defaults.md
  docs/serving/configuration/feature-flags.md
  docs/serving/deploying-from-private-registry.md
  docs/serving/services/creating-services.md
  docs/serving/services/using-queue-extensions.md
Labels: size/M, lgtm, approved

#5558 [release-1.10] Update image references to ghcr.io/knative/*
  blog/docs/articles/knative-serving-in-k0s.md
  blog/docs/articles/quickstart-with-knative.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
  docs/getting-started/first-service.md
  docs/getting-started/first-traffic-split.md
  docs/serving/app-security/security-guard-quickstart.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/autoscaling/autoscaler-types.md
  docs/serving/autoscaling/concurrency.md
  docs/serving/autoscaling/kpa-specific.md
  docs/serving/autoscaling/rps-target.md
  docs/serving/autoscaling/scale-bounds.md
  docs/serving/autoscaling/scale-to-zero.md
  docs/serving/configuration/config-defaults.md
  docs/serving/configuration/feature-flags.md
  docs/serving/deploying-from-private-registry.md
  docs/serving/services/creating-services.md
  docs/serving/services/using-queue-extensions.md
Labels: size/M, lgtm, approved

#5559 [release-1.9] Update image references to ghcr.io
  blog/docs/articles/quickstart-with-knative.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
  docs/getting-started/first-service.md
  docs/getting-started/first-traffic-split.md
  docs/serving/app-security/security-guard-quickstart.md
  docs/serving/autoscaling/autoscale-go/README.md
  docs/serving/autoscaling/autoscaler-types.md
  docs/serving/autoscaling/concurrency.md
  docs/serving/autoscaling/container-freezer.md
  docs/serving/autoscaling/kpa-specific.md
  docs/serving/autoscaling/rps-target.md
  docs/serving/autoscaling/scale-bounds.md
  docs/serving/autoscaling/scale-to-zero.md
  docs/serving/configuration/config-defaults.md
  docs/serving/configuration/feature-flags.md
  docs/serving/deploying-from-private-registry.md
  docs/serving/services/creating-services.md
  docs/serving/services/using-queue-extensions.md
Labels: size/M, lgtm, approved

#5561 Update next-steps.md, remove knative.tips link
  docs/getting-started/next-steps.md
Labels: size/XS, lgtm, approved

#5553 Add details about revision_queue_depth metric
  docs/serving/services/service-metrics.md
Labels: size/XS, lgtm, approved

#5568 Update Knative cosign verify docs
  docs/snippets/security-prereqs-binaries.md
  docs/snippets/security-prereqs-images.md
Labels: lgtm, size/S, approved

#5574 TOC election banner on release branch
  overrides/main.html
Labels: size/XS, lgtm, approved

#5575 docs: add links to stateless and event-driven
  docs/snippets/about-functions.md
Labels: size/XS, lgtm, approved

#5576 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5578 Fix image url of autoscale-go service
  docs/serving/autoscaling/autoscale-go/service.yaml
Labels: size/XS, lgtm, approved

#5580 Update README.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
Labels: size/XS, lgtm, approved

#5581 Update autoscaling-metrics.md for modifications
  docs/serving/autoscaling/autoscaling-metrics.md
Labels: lgtm, size/S, ok-to-test, approved

#5582 Document QP reporting period
  docs/serving/services/service-metrics.md
Labels: lgtm, size/S, approved

#5584 chore: remove TOC election banner
  overrides/main.html
Labels: size/XS, lgtm, approved
