Repository knative/docs, pull requests merged in 2023-03, with the labels that each got.

#5453 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5443 Fix Code Block Formatting
  code-samples/eventing/helloworld/helloworld-go/README.md
Labels: lgtm, size/XL, approved

#5452 Proxy kafka records blog post
  blog/config/nav.yml
  blog/docs/articles/from-cloudevent-to-apach-kafka-records-part-one.md
Labels: size/L, lgtm, approved

#5457 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5456 Missing step in knative functions tutorial
  docs/snippets/proc-running-function.md
Labels: size/XS, lgtm, approved

#5454 First draft of Event Mesh definition
  config/nav.yml
  docs/eventing/event-mesh.md
  docs/eventing/images/mesh.png
Labels: lgtm, size/S, approved

#5437 Adding PNC case study
  config/nav.yml
  docs/about/case-studies/pnc.md
  docs/images/case-studies/pnc_bank.png
Labels: size/M, lgtm, approved

#5461 Update the usage of Apache Kafka term
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/kafka-broker/README.md
  docs/eventing/configuration/kafka-channel-configuration.md
  docs/eventing/event-registry.md
  docs/eventing/sinks/kafka-sink.md
  docs/eventing/sources/kafka-source/README.md
Labels: lgtm, size/S, approved

#5462 [release-1.9] Update the usage of Apache Kafka term
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/kafka-broker/README.md
  docs/eventing/configuration/kafka-channel-configuration.md
  docs/eventing/event-registry.md
  docs/eventing/sinks/kafka-sink.md
  docs/eventing/sources/kafka-source/README.md
Labels: lgtm, size/S, approved

#5464 Little more updates on Apache Kafka term usage
  config/nav.yml
Labels: size/XS, lgtm, approved

#5466 Spelling correction of Python
  docs/eventing/event-mesh.md
Labels: size/XS, lgtm, approved

#5467 Update NOT and CESQL which are not working
  docs/eventing/experimental-features/new-trigger-filters.md
Labels: size/XS, lgtm, approved

#5474 knativeproject kiosk annoucement KubeconEU23
  blog/config/nav.yml
  blog/docs/events/knative-projectmeeting-kubecon-eu-2023.md
  blog/docs/index.md
Labels: lgtm, size/S, approved

#5477 Update to golang 1.18
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/sys/unix/LICENSE
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/storage/go.mod
  vendor/cloud.google.com/go/storage/go.sum
  vendor/github.com/cloudevents/sdk-go/v2/go.mod
  vendor/github.com/cloudevents/sdk-go/v2/go.sum
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/googleapis/gax-go/v2/go.mod
  vendor/github.com/googleapis/gax-go/v2/go.sum
  vendor/github.com/jstemmer/go-junit-report/go.mod
  vendor/github.com/kelseyhightower/envconfig/go.mod
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.uber.org/atomic/go.mod
  vendor/go.uber.org/atomic/go.sum
  vendor/go.uber.org/multierr/go.mod
  vendor/go.uber.org/multierr/go.sum
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/google.golang.org/appengine/go.mod
  vendor/google.golang.org/appengine/go.sum
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/go.sum
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#5480 Fix typo in broker admin config options
  docs/eventing/brokers/broker-admin-config-options.md
Labels: size/XS, lgtm, approved

#5482 fix: correct bad link to reference page
  blog/config/nav.yml
  docs/reference/relnotes/README.md
Labels: size/XS, lgtm, approved

#5487 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#5488 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/modules.txt
Labels: size/L, lgtm, approved

#5446 fix tab formatting - issue #4922
  code-samples/serving/cloudevents/cloudevents-go/README.md
  code-samples/serving/cloudevents/cloudevents-nodejs/README.md
  code-samples/serving/cloudevents/cloudevents-rust/README.md
  code-samples/serving/cloudevents/cloudevents-spring/README.md
  code-samples/serving/cloudevents/cloudevents-vertx/README.md
  code-samples/serving/hello-world/helloworld-go/README.md
  code-samples/serving/hello-world/helloworld-java-spark/README.md
  code-samples/serving/hello-world/helloworld-java-spring/README.md
  code-samples/serving/hello-world/helloworld-php/README.md
  code-samples/serving/hello-world/helloworld-python/README.md
  code-samples/serving/hello-world/helloworld-ruby/README.md
  code-samples/serving/hello-world/helloworld-scala/README.md
  code-samples/serving/hello-world/helloworld-shell/README.md
Labels: lgtm, size/XXL, approved

#5493 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#5484 Extend event mesh topic
  docs/eventing/event-mesh.md
  docs/eventing/images/mesh.drawio
  docs/eventing/images/mesh.png
Labels: lgtm, size/S, approved

#5486 Update Cloudevents Player deployment
  docs/getting-started/first-source.md
  docs/getting-started/images/event_form.png
  docs/getting-started/images/event_received.png
  docs/getting-started/images/event_sent.png
Labels: size/M, lgtm, approved

#5510 Knative services are private by default
  docs/serving/services/private-services.md
  docs/serving/using-a-custom-domain.md
Labels: lgtm, size/S, approved

#5492 Document Request Logging Feature on the Website
  config/nav.yml
  docs/serving/observability/logging/request-logging.md
Labels: lgtm, size/S, approved

#5513 Update knative-projectmeeting-kubecon-eu-2023.md
  blog/docs/events/knative-projectmeeting-kubecon-eu-2023.md
Labels: size/XS, lgtm, approved

#5514 Add knative serving in K0s blog
  blog/config/nav.yml
  blog/docs/articles/knative-serving-in-k0s.md
Labels: size/L, lgtm, approved

#5515 Remove dead links
  docs/samples/eventing.md
Labels: size/XS, lgtm, approved

#5516 Remove documentation for container-freezer
  config/nav.yml
  docs/serving/autoscaling/README.md
  docs/serving/autoscaling/container-freezer.md
  docs/serving/configuration/deployment.md
Labels: size/M, lgtm, approved

#5517 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5520 Relabel tab to 'No DNS'
  docs/install/operator/knative-with-operators.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/snippets/dns.md
  docs/snippets/no-dns.md
Labels: size/XS, lgtm, approved
