Repository knative/docs, pull requests merged in 2023-01, with the labels that each got.

#5374 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5375 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5377 Remove outdated blog OWNERS file
  blog/OWNERS
Labels: size/XS, lgtm, approved

#5376 Adding a blog post for simpler kafka development
  blog/config/nav.yml
  blog/docs/articles/single-node-kafka-development.md
Labels: size/L, lgtm, approved

#5378 guard doc fixes
  docs/serving/app-security/security-guard-install.md
Labels: size/L, lgtm, approved

#5379 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#5367 Use `go install` to install binary
  docs/serving/autoscaling/autoscale-go/README.md
Labels: size/XS, lgtm, approved

#5360 Add Debezium as an event source
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, approved

#5382 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#5384 Fixes minikube quickstart default memory value
  docs/snippets/quickstart-install.md
Labels: size/XS, lgtm, approved

#5385 update hello world node app dependencies in readme
  code-samples/serving/hello-world/helloworld-nodejs/README.md
Labels: size/XS, lgtm, approved

#5386 Add link to springboot for function-templates
  docs/snippets/functions-templates-intro.md
Labels: size/XS, lgtm, approved

#5390 Adding a little bit more on the subject of consumer delivery guarantees
  docs/eventing/brokers/broker-types/kafka-broker/README.md
Labels: size/XS, lgtm, approved

#5348 Revise website community content to be more beginner-friendly
  .github/pull-request-template.md
  _index.html
  config/nav.yml
  config/redirects.yml
  docs/community/README.md
  docs/community/contributing.md
  docs/community/governance.md
  docs/community/images/knative-audience.png
  docs/community/images/knative-audience.svg
  docs/community/images/knative-version.png
  docs/community/images/logo/cmyk/knative-logo-cmyk.ai
  docs/community/images/logo/cmyk/knative-logo-cmyk.eps
  docs/community/images/logo/cmyk/knative-logo-cmyk.jpg
  docs/community/images/logo/cmyk/knative-logo-cmyk.pdf
  docs/community/images/logo/cmyk/knative-logo-cmyk.png
  docs/community/images/logo/rgb/knative-logo-rgb.ai
  docs/community/images/logo/rgb/knative-logo-rgb.eps
  docs/community/images/logo/rgb/knative-logo-rgb.jpg
  docs/community/images/logo/rgb/knative-logo-rgb.pdf
  docs/community/images/logo/rgb/knative-logo-rgb.png
  docs/community/images/logo/style-guide.pdf
  docs/contributing/README.md
  overrides/home.html
Labels: size/L, lgtm, approved

#5391 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#5392 Updates slack URLs to CNCF instance
  README.md
  _index.html
  blog/docs/articles/highlighting-value-knative-c-suite.md
  blog/docs/releases/_template-announcing-knative-v1-X-release.txt
  blog/mkdocs.yml
  contribute-to-docs/README.md
  contribute-to-docs/getting-started/README.md
  contribute-to-docs/getting-started/becoming-a-contributor.md
  contribute-to-docs/getting-started/github-workflow.md
  contribute-to-docs/style-guide/README.md
  contribute-to-docs/what-to-contribute/creating-blog-posts.md
  docs/community/README.md
  docs/community/contributing.md
  docs/community/governance.md
  docs/eventing/custom-event-source/custom-event-source/README.md
  docs/getting-started/next-steps.md
  docs/serving/app-security/security-guard-about.md
  mkdocs.yml
Labels: size/M, lgtm, approved

#5394 Guard script fix - for 1.9
  docs/serving/app-security/security-guard-install.md
Labels: size/M, lgtm, approved

#5395 Add missing slack channels, fix formatting
  docs/community/README.md
Labels: lgtm, size/S, approved

#5389 Docs for KafkaNamespaced broker
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/kafka-broker/README.md
Labels: size/M, lgtm, approved

#5397 Add Knative 1.9 announcement
  blog/config/nav.yml
  blog/docs/releases/announcing-knative-v1-9-release.md
Labels: size/L, lgtm, approved

#5396 Adds namespace selector reference to ApiServerSource docs [1.9 feature]
  docs/eventing/sources/apiserversource/reference.md
Labels: size/M, lgtm, approved
