Repository knative/docs, pull requests merged in 2023-11, with the labels that each got.

#5741 Fix deprecation warnings and update CSS
  blog/config/nav.yml
  blog/mkdocs.yml
  config/nav.yml
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
  requirements.txt
Labels: size/M, lgtm, approved

#5745 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5651 Finalize pvc support
  docs/serving/services/storage.md
Labels: size/M, lgtm, approved

#5749 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5755 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5754 Adding initial doc for func subscribe
  config/nav.yml
  docs/functions/subscribing-functions.md
  docs/snippets/proc-subscribe-function.md
Labels: size/M, lgtm, approved

#5752 Fix Eventing Source Example Link for Amazon Kinesis
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, approved

#5746 Fix wrong code sample in helloworld-go README.md
  code-samples/eventing/helloworld/helloworld-go/README.md
Labels: size/M, lgtm, approved

#5760 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, lgtm, approved

#5762 [release-1.12] add deprecation notices for net-http01
  docs/install/yaml-install/serving/install-serving-with-yaml.md
Labels: size/XS, lgtm, approved

#5761 drop net-http01 from v1.13 release
  blog/docs/releases/announcing-knative-v1-12-release.md
  docs/install/uninstall.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
Labels: size/M, lgtm, approved

#5766 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#5774 Add clotributor link to readme
  README.md
Labels: size/XS, lgtm, approved

#5773 Documentation - progress deadline annotation on per revision basis
  docs/serving/configuration/deployment.md
Labels: size/M, lgtm, approved

#5776 Bump min-k8s version to 1.27
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, approved

#5779 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5770 Trigger image build when requirements change
  .github/workflows/knative-docs-image.yaml
Labels: size/XS, lgtm, approved
