Repository knative/docs, pull requests merged in 2023-08, with the labels that each got.

#5639 Added mention of channels to event type autocreate docs
  docs/eventing/experimental-features/eventtype-auto-creation.md
Labels: lgtm, size/S, approved

#5591 update configure-kn.md to include channel-type-mappings and add comments to sample yaml
  docs/client/configure-kn.md
Labels: lgtm, size/S, approved

#5649 Fixing typo
  blog/docs/articles/new_event_discovery_features.md
Labels: size/XS, lgtm, approved

#5648 Update the release table for Knative Operator 1.11
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#5647 Add Knative v1.11.0 release blog
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-11-release.md
Labels: size/L, lgtm, approved

#5654 Adding note on channel api support for this as well
  blog/docs/articles/new_event_discovery_features.md
Labels: size/XS, lgtm, approved

#5656 Redirect goimports properly
  golang/_redirects
  golang/func-go.html
  tools/redir-gen/main.go
Labels: lgtm, size/S, approved

#5657 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5658 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5638 Adding blog on Knative Vision
  blog/config/nav.yml
  blog/docs/articles/knative-eventing-vision.md
Labels: size/L, lgtm, approved

#5659 Fixing the actual date of publication
  blog/docs/articles/knative-eventing-vision.md
Labels: size/XS, lgtm, approved

#5660 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5664 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5661 rename sandbox to extensions - manual
  config/redirects.yml
  contribute-to-docs/style-guide/word-and-phrase-list.md
  docs/client/kn-plugins.md
  docs/community/governance.md
  docs/eventing/custom-event-source/custom-event-source/README.md
  docs/eventing/experimental-features/delivery-retryafter.md
  docs/functions/language-packs.md
Labels: lgtm, size/S, approved

#5670 Update set-up-a-local-knative-environment-with-kind.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
Labels: size/XS, lgtm, approved
