Repository knative/docs, pull requests merged in 2023-10, with the labels that each got.

#5702 update expected revision name for quickstart service
  docs/getting-started/first-service.md
Labels: size/XS, lgtm, approved

#5694 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#5692 Rename and reword `auto-tls` feature to `external-domain-tls`
  config/nav.yml
  config/redirects.yml
  docs/install/installing-cert-manager.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/serving/README.md
  docs/serving/encryption/enabling-automatic-tls-certificate-provisioning.md
  docs/serving/encryption/using-certificates-in-networking-layer.md
  docs/serving/services/certificate-class.md
  docs/serving/services/custom-tls-certificate-domain-mapping.md
  docs/serving/services/http-protocol.md
  docs/serving/services/service-metrics.md
Labels: size/L, lgtm, approved

#5622 Added kafka features config map to kafka broker docs
  config/nav.yml
  docs/eventing/brokers/broker-types/kafka-broker/README.md
  docs/eventing/brokers/broker-types/kafka-broker/configuring-kafka-features.md
Labels: size/M, lgtm, approved

#5706 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5711 control-protocol is still used in Knative 1.10
  golang/_redirects
  tools/redir-gen/main.go
Labels: size/XS, lgtm, approved

#5716 Update README.md
  README.md
Labels: lgtm, size/S, approved

#5715 Source cloudevents revision
  docs/getting-started/first-source.md
Labels: size/XS, lgtm, approved

#5676 Explain what `sample application` is, in `no-dns.md`
  docs/snippets/no-dns.md
Labels: size/XS, lgtm, approved

#5721 [UPDATED] the home page svg file
  blog/docs/images/home-images/knative_flowchart_graphic.svg
  docs/images/home-images/knative_flowchart_graphic.svg
Labels: lgtm, size/XXL, approved

#5726 Helloworld rust/bump dependencies
  code-samples/community/serving/helloworld-rust/Cargo.lock
  code-samples/community/serving/helloworld-rust/Cargo.toml
  code-samples/community/serving/helloworld-rust/Dockerfile
  code-samples/community/serving/helloworld-rust/README.md
Labels: size/L, lgtm, approved

#5727 Fix deprecation warning in Knative Verify
  blog/mkdocs.yml
  mkdocs.yml
  requirements.txt
Labels: lgtm, size/S, approved

#5730 Revert "Fix deprecation warning (#5727)"
  blog/mkdocs.yml
  mkdocs.yml
  requirements.txt
Labels: lgtm, size/S, approved

#5731 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#5733 Blog post about knative presence in KubeCon NA 2023
  blog/docs/events/knative-at-kubecon-na-2024.md
Labels: lgtm, size/S, approved

#5734 Rename knative-at-kubecon-na-2024.md to knative-at-kubecon-na-2023.md
  blog/docs/events/knative-at-kubecon-na-2023.md
Labels: size/XS, lgtm, approved

#5735 Update nav.yml for navigating blog post about kubecon na 23
  blog/config/nav.yml
Labels: size/XS, lgtm, approved

#5737 PingSource schedule seconds support documented
  docs/eventing/sources/ping-source/README.md
Labels: lgtm, size/S, ok-to-test, approved

#5738 Bump to new release version
  hack/build.sh
Labels: size/XS, lgtm, approved

#5739 Add Knative v1.12.0 release blog
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-12-release.md
Labels: size/L, lgtm, approved

#5743 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved
