Repository knative/docs, pull requests merged in 2023-02, with the labels that each got.

#5393 GSoC23@Knative blogpost
  blog/config/nav.yml
  blog/docs/events/google-summer-of-code-2023.md
Labels: lgtm, size/S, approved

#5398 Update the documents on Knative Operator 1.9
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#5400 added note for knative installation on kind
  docs/snippets/quickstart-install.md
Labels: size/XS, lgtm, approved

#5402 Update the advanced istio installation docs
  docs/install/installing-istio.md
  docs/install/operator/knative-with-operators.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/snippets/dns.md
Labels: size/L, lgtm, approved

#5404 Release docs version 1.9
  hack/build.sh
Labels: size/XS, lgtm, approved

#5405 Updated the Broken links
  docs/samples/README.md
Labels: size/XS, lgtm, approved

#5381 Fixes a typo in docs
  docs/serving/observability/metrics/serving-metrics.md
Labels: size/XS, lgtm, approved

#5411 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#5406 Blog post about Knative Kafka Broker with isolated data plane
  blog/config/nav.yml
  blog/docs/articles/kafka-broker-with-isolated-data-plane.md
Labels: size/L, lgtm, approved

#5272 Add image/binary signing verification docs
  blog/docs/releases/announcing-knative-v1-9-release.md
  docs/client/install-kn.md
  docs/install/operator/knative-with-operator-cli.md
  docs/install/operator/knative-with-operators.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/reference/security/README.md
  docs/snippets/security-prereqs-binaries.md
  docs/snippets/security-prereqs-images.md
Labels: size/L, lgtm, approved, hacktoberfest-accepted

#5415 We do not have an activator in Eventing
  docs/install/operator/configuring-eventing-cr.md
Labels: size/XS, lgtm, approved

#5409 Cleanup: remove ioutil for new go version
  code-samples/serving/multi-container/README.md
  code-samples/serving/multi-container/servingcontainer/servingcontainer.go
  docs/eventing/channels/generator/main.go
  test/sampleapp/config.go
Labels: lgtm, size/S, approved

#5420 Update min required kubernetes version
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, approved

#5419 Add CLI func if Git URL already specified
  docs/functions/building-functions.md
Labels: size/XS, lgtm, approved

#5424 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#5413 Fixed error in incomplete sentence.
  docs/community/README.md
Labels: size/XS, lgtm, approved

#5426 Adding a little description to the Kafka Sink doc
  docs/eventing/sinks/kafka-sink.md
Labels: size/XS, lgtm, approved

#5425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#5428 fix language-packs link
  docs/functions/README.md
Labels: size/XS, lgtm, approved

#5430 Document scaling KafkaSource
  docs/eventing/sources/kafka-source/README.md
Labels: size/M, lgtm, ok-to-test, approved

#5435 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5433 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5439 Documenting guard support for functions
  docs/serving/app-security/security-guard-quickstart.md
Labels: lgtm, size/S, approved

#5436 Migrate from k8s.gcr.io to registry.k8s.io
  docs/eventing/observability/logging/fluent-bit-collector.yaml
  docs/serving/observability/logging/fluent-bit-collector.yaml
  docs/serving/stackdriver/Dockerfile
Labels: size/XS, lgtm, approved

#5441 Update version label in query command
  docs/install/upgrade/check-install-version.md
Labels: size/XS, lgtm, ok-to-test, approved

#5445 [release-1.9] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#5451 update triggermesh event sources documentation
  docs/eventing/sources/README.md
Labels: size/M, lgtm, approved
