Repository knative/docs, pull requests merged in 2023-09, with the labels that each got.

#5673 Update DomainMapping to v1beta1 from v1alpha1
  docs/serving/services/byo-certificate.md
  docs/serving/services/custom-domains.md
Labels: size/XS, lgtm, ok-to-test, approved

#5273 chore: multi-arch support with buildx in all Dockerfiles
  code-samples/community/serving/helloworld-clojure/README.md
  code-samples/community/serving/helloworld-clojure/index.md
  code-samples/community/serving/helloworld-dart/README.md
  code-samples/community/serving/helloworld-dart/index.md
  code-samples/community/serving/helloworld-deno/README.md
  code-samples/community/serving/helloworld-deno/index.md
  code-samples/community/serving/helloworld-elixir/README.md
  code-samples/community/serving/helloworld-elixir/index.md
  code-samples/community/serving/helloworld-haskell/README.md
  code-samples/community/serving/helloworld-haskell/index.md
  code-samples/community/serving/helloworld-java-micronaut/README.md
  code-samples/community/serving/helloworld-java-micronaut/index.md
  code-samples/community/serving/helloworld-java-quarkus/README.md
  code-samples/community/serving/helloworld-java-quarkus/index.md
  code-samples/community/serving/helloworld-r/Dockerfile
  code-samples/community/serving/helloworld-r/README.md
  code-samples/community/serving/helloworld-r/index.md
  code-samples/community/serving/helloworld-rserver/README.md
  code-samples/community/serving/helloworld-rserver/index.md
  code-samples/community/serving/helloworld-rust/README.md
  code-samples/community/serving/helloworld-rust/index.md
  code-samples/community/serving/helloworld-swift/README.md
  code-samples/community/serving/helloworld-swift/index.md
  code-samples/community/serving/helloworld-vertx/README.md
  code-samples/community/serving/helloworld-vertx/index.md
  code-samples/community/serving/machinelearning-python-bentoml/README.md
  code-samples/community/serving/machinelearning-python-bentoml/index.md
  code-samples/eventing/helloworld/helloworld-go/Dockerfile
  code-samples/eventing/helloworld/helloworld-go/README.md
  code-samples/eventing/helloworld/helloworld-python/README.md
  code-samples/eventing/writing-event-source-easy-way/README.md
  code-samples/serving/cloudevents/cloudevents-dotnet/README.md
  code-samples/serving/cloudevents/cloudevents-go/Dockerfile
  code-samples/serving/cloudevents/cloudevents-go/README.md
  code-samples/serving/cloudevents/cloudevents-nodejs/README.md
  code-samples/serving/cloudevents/cloudevents-rust/README.md
  code-samples/serving/gitwebhook-go/Dockerfile
  code-samples/serving/gitwebhook-go/README.md
  code-samples/serving/grpc-ping-go/Dockerfile
  code-samples/serving/grpc-ping-go/README.md
  code-samples/serving/hello-world/helloworld-csharp/README.md
  code-samples/serving/hello-world/helloworld-go/README.md
  code-samples/serving/hello-world/helloworld-java-spark/README.md
  code-samples/serving/hello-world/helloworld-java-spring/README.md
  code-samples/serving/hello-world/helloworld-kotlin/README.md
  code-samples/serving/hello-world/helloworld-nodejs/README.md
  code-samples/serving/hello-world/helloworld-php/README.md
  code-samples/serving/hello-world/helloworld-python/README.md
  code-samples/serving/hello-world/helloworld-shell/README.md
  code-samples/serving/knative-routing-go/Dockerfile
  code-samples/serving/knative-routing-go/README.md
  code-samples/serving/kong-routing-go/Dockerfile
  code-samples/serving/kong-routing-go/README.md
  code-samples/serving/multi-container/README.md
  code-samples/serving/multi-container/servingcontainer/Dockerfile
  code-samples/serving/multi-container/sidecarcontainer/Dockerfile
  code-samples/serving/secrets-go/Dockerfile
  code-samples/serving/secrets-go/README.md
  hack/docker/build-image.sh
Labels: size/L, lgtm, approved, hacktoberfest-accepted

#5675 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5677 Updates to func build/run documentation
  docs/snippets/proc-building-function.md
  docs/snippets/proc-running-function.md
Labels: size/XS, lgtm, approved

#5678 Update min required kubernetes version
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, ok-to-test, approved

#5681 DeliverySpec.Timeout field mark beta
  docs/eventing/experimental-features/README.md
Labels: size/XS, lgtm, approved

#5683 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5684 Removed Kafka Binding doc and its references
  code-samples/eventing/kafka/binding/README.md
  docs/samples/eventing.md
Labels: size/L, lgtm, approved

#5636 Getting started blog p2
  blog/config/nav.yml
  blog/docs/articles/getting-started-blog-p0.md
  blog/docs/articles/getting-started-blog-p1.md
  blog/docs/articles/getting-started-blog-p2.md
  blog/docs/images/getting-started-blog-series/post2/doodle001.png
  blog/docs/images/getting-started-blog-series/post2/doodle002.png
  blog/docs/images/getting-started-blog-series/post2/doodle003.png
  blog/docs/images/getting-started-blog-series/post2/jb001.png
  blog/docs/images/getting-started-blog-series/post2/jb002.png
  blog/docs/images/getting-started-blog-series/post2/vscode001.png
  blog/docs/images/getting-started-blog-series/post2/vscode002.png
  blog/docs/images/getting-started-blog-series/post2/vscode003.png
  blog/docs/images/getting-started-blog-series/post2/vscode004.png
  blog/docs/images/getting-started-blog-series/post2/vscode005.png
Labels: size/L, lgtm, approved

#5688 Update configuring-serving-cr.md
  docs/install/operator/configuring-serving-cr.md
Labels: size/XS, lgtm, approved

#5667 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#5691 Added the golang redirect for serving-progressive-rollout
  golang/_redirects
  golang/serving-progressive-rollout.html
Labels: size/XS, lgtm, approved

#5695 Bump min-k8s version to 1.26
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, approved

#5693 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#5697 Document how to trust specific CA certs for event senders
  docs/eventing/experimental-features/transport-encryption.md
Labels: size/M, lgtm, approved

#5686 correct Event Type AutoCreate flag name
  docs/eventing/experimental-features/eventtype-auto-creation.md
Labels: size/XS, lgtm, approved

#5700 update kn + quickstart installs for consistency
  docs/snippets/install-kn.md
  docs/snippets/quickstart-install.md
Labels: size/M, lgtm, approved
