Repository knative/docs, pull requests merged in 2023-07, with the labels that each got.

#5620 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5619 Document current behaviour of scaling down with activation scale
  docs/serving/autoscaling/scale-bounds.md
Labels: size/XS, lgtm, approved

#5621 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5618 Intro to open source with knative blog series p0 and p1
  blog/config/nav.yml
  blog/docs/articles/getting-started-blog-p0.md
  blog/docs/articles/getting-started-blog-p1.md
  blog/docs/images/getting-started-blog-series/post0/person-chasing-logo.png
  blog/docs/images/getting-started-blog-series/post0/person-falling-logo.png
  blog/docs/images/getting-started-blog-series/post0/reading-side-doodle.png
  blog/docs/images/getting-started-blog-series/post1/getting-feedback.png
  blog/docs/images/getting-started-blog-series/post1/hello-open-source.png
  blog/docs/images/getting-started-blog-series/post1/open-source-workflow.png
  blog/docs/images/getting-started-blog-series/post1/propose-ideas.png
  blog/docs/images/getting-started-blog-series/post1/ready-for-review.png
  blog/docs/images/getting-started-blog-series/post1/start-coding.png
  blog/docs/images/getting-started-blog-series/post1/thanks.png
  blog/docs/images/getting-started-blog-series/post1/why-contribute.png
Labels: size/L, lgtm, approved

#5624 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#5625 Fixing minor typo in getting-started-blog-p1.md
  blog/docs/articles/getting-started-blog-p1.md
Labels: size/XS, lgtm, approved

#5626 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5617 Describe how to set qp resources
  docs/serving/services/configure-requests-limits-services.md
Labels: size/M, lgtm, approved

#5605 Add details for storage and knative services
  config/nav.yml
  docs/serving/services/storage.md
Labels: size/M, lgtm, approved

#5627 Add blogpost and report for fuzzing audit
  blog/config/nav.yml
  blog/docs/events/fuzzing-audit-2023.md
  reports/ADA-knative-fuzzing-audit-22-23.pdf
Labels: size/M, lgtm, approved

#5628 Fix nits in fuzzing audit blogpost
  blog/docs/events/fuzzing-audit-2023.md
  reports/ADA-knative-fuzzing-audit-22-23.pdf
Labels: size/XS, lgtm, approved

#5633 Remove subtitle in homepage
  overrides/home.html
Labels: size/XS, lgtm, approved

#5635 Aligning the Eventing message w/ the README from its repo
  docs/concepts/README.md
  docs/eventing/README.md
  docs/snippets/about-eventing.md
Labels: size/XS, lgtm, approved

#5592 Add doc about cutomize kourier-bootstrap for Kourier gateways
  docs/install/operator/configuring-serving-cr.md
Labels: lgtm, size/S, approved

#5641 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5640 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#5610 docs: update instructions on client code-sign verification
  docs/reference/security/README.md
Labels: lgtm, size/S, approved

#5629 Fixing #5537: Adding mandatory target annotation and their units.
  docs/serving/autoscaling/autoscaling-metrics.md
Labels: lgtm, size/S, approved

#5643 Add version 1.11 to generate docs
  hack/build.sh
Labels: size/XS, lgtm, approved
