Repository knative/docs, pull requests merged in 2024-10, with the labels that each got.

#6134 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6140 fix: sources table rendering
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, approved

#6143 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#6142 fix: remove next/previous text from blog footer
  overrides/partials/footer.html
Labels: lgtm, size/S, approved

#6146 Release v1.16
  hack/build.sh
Labels: size/XS, lgtm, approved

#6148 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#6147 Add release blog Knative 1.16
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-16-release.md
Labels: size/L, lgtm, approved

#6150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#6152 Add the image banners for the release 1.16
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-16-release.md
  blog/docs/releases/images/release1.16-1.png
  blog/docs/releases/images/release1.16-eventing.png
  blog/docs/releases/images/release1.16-function.png
  blog/docs/releases/images/release1.16-serving.png
Labels: size/XS, lgtm, approved
