Repository knative/docs, pull requests merged in 2024-09, with the labels that each got.

#6105 [Blog post] Building Stateful applications with Knative and Restate
  blog/config/nav.yml
  blog/docs/articles/Building-Stateful-applications-with-Knative-and-Restate.md
  blog/docs/index.md
Labels: size/L, lgtm, approved

#6106 Add image blog post
  blog/docs/articles/Building-Stateful-applications-with-Knative-and-Restate.md
  blog/docs/articles/images/Building-stateful-serverless-apps-with-knative-and-restate.png
  blog/docs/index.md
Labels: size/XS, lgtm, approved

#6104 Add documentation for Eventing Authorization
  config/nav.yml
  config/redirects.yml
  docs/eventing/features/README.md
  docs/eventing/features/authorization.md
  docs/eventing/features/images/authz-example.png
Labels: size/L, lgtm, approved

#6108 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6114 Minor tweaks for WebSockets sample
  code-samples/serving/websockets-go/README.md
  code-samples/serving/websockets-go/config/service.yaml
Labels: size/XS, lgtm, approved

#6113 Adding Websocket blog post
  blog/config/nav.yml
  blog/docs/articles/Knative-Serving-WebSockets.md
Labels: size/L, lgtm, approved

#6115 fix: update express to the latest(4.20.0).
  code-samples/eventing/bookstore-sample-app/solution/node-server/package-lock.json
  code-samples/eventing/bookstore-sample-app/solution/node-server/package.json
  code-samples/eventing/bookstore-sample-app/start/node-server/package-lock.json
  code-samples/eventing/bookstore-sample-app/start/node-server/package.json
  code-samples/serving/cloudevents/cloudevents-nodejs/package-lock.json
  code-samples/serving/cloudevents/cloudevents-nodejs/package.json
  code-samples/serving/hello-world/helloworld-nodejs/package-lock.json
  code-samples/serving/hello-world/helloworld-nodejs/package.json
Labels: lgtm, size/XXL, approved

#6095 Remove cocurrenty-state-endpoint from docs
  docs/serving/configuration/deployment.md
Labels: size/XS, lgtm, approved

#6107 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved, skip-review

#6118 Fix sampleconsistency test
  code-samples/serving/hello-world/helloworld-nodejs/README.md
Labels: size/XS, lgtm, approved

#6004 Fix footer styling issue
  overrides/partials/footer.html
Labels: lgtm, size/S, approved

#6101 made mobile view of knative components container
  docs/images/home-images/knative_flowchart_graphic_mobile.svg
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: size/L, lgtm, approved

#6068 made top three sections of home page responsive
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: size/L, lgtm, approved

#6123 Document host* and shareProcessNamespace flags
  docs/serving/configuration/feature-flags.md
Labels: size/M, lgtm, approved

#6126 Knative Backstage security blogpost
  blog/config/nav.yml
  blog/docs/articles/images/knative-backstage-security-01.png
  blog/docs/articles/knative-backstage-plugins.md
  blog/docs/articles/knative-backstage-security.md
Labels: size/M, lgtm, approved

#6127 Backstage plugin docs
  config/nav.yml
  docs/eventing/event-registry/README.md
  docs/eventing/event-registry/eventmesh-backstage-plugin.md
  docs/eventing/event-registry/images/event-mesh-plugin-apis-view.png
  docs/eventing/event-registry/images/event-mesh-plugin-components-view.png
  docs/eventing/event-registry/images/event-mesh-plugin-graph.png
  docs/eventing/event-registry/images/knative-backstage-security.png
  docs/install/installing-backstage-plugins.md
Labels: size/L, lgtm, approved

#6129 Fix broken links
  docs/eventing/event-registry/README.md
Labels: size/XS, lgtm, approved
