Repository knative/docs, pull requests merged in 2024-11, with the labels that each got.

#6155 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6162 Update SQS Source blog
  blog/docs/articles/consuming_sqs_data_with_integrationsource.md
Labels: size/XS, lgtm, approved

#6156 Adding first draft of IntegrationSource doc
  config/nav.yml
  docs/eventing/sources/integration-source/README.md
  docs/eventing/sources/integration-source/aws_ddbstreams.md
  docs/eventing/sources/integration-source/aws_s3.md
  docs/eventing/sources/integration-source/aws_sqs.md
  docs/eventing/sources/integration-source/timer.md
Labels: size/L, lgtm, approved

#6163 Adding initial doc for IntegrationSink
  config/nav.yml
  docs/eventing/sinks/README.md
  docs/eventing/sinks/integration-sink/README.md
  docs/eventing/sinks/integration-sink/aws_s3.md
  docs/eventing/sinks/integration-sink/aws_sqs.md
  docs/eventing/sinks/integration-sink/logger.md
Labels: size/L, lgtm, approved

#6164 Update source index
  docs/eventing/sources/README.md
Labels: size/M, lgtm, approved

#6165 Update Sink Index page
  docs/eventing/sinks/README.md
Labels: lgtm, size/S, approved

#6168 fixed border radius on home page button
  overrides/assets/stylesheets/home.css
Labels: size/XS, lgtm, approved

#6167 Create How_Conxai_uses_Knative_Eventing_to_provide_AI_APIs_in_the_con…
  blog/config/nav.yml
  blog/docs/articles/How_Conxai_uses_Knative_Eventing_to_provide_AI_APIs_in_the_construction_industry.md
Labels: size/M, lgtm, approved

#6169 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#6166 [release-1.16] Remove Triggermesh, since they are gone, since a while
  docs/eventing/sources/README.md
Labels: size/M, lgtm, approved
