Repository knative/docs, pull requests merged in 2024-03, with the labels that each got.

#5883 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5884 Modify the description about Max revision timeout seconds
  docs/serving/configuration/config-defaults.md
Labels: size/XS, lgtm, approved

#5886 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5878 Implemented sliding animation for the adopter logos
  docs/images/corporate-logos/Google.svg
  docs/images/corporate-logos/IBM.svg
  docs/images/corporate-logos/Redhat.svg
  docs/images/corporate-logos/alibaba_cloud.svg
  docs/images/corporate-logos/bloomberg.svg
  docs/images/corporate-logos/blue_origin.svg
  docs/images/corporate-logos/box.svg
  docs/images/corporate-logos/chainguard.svg
  docs/images/corporate-logos/control_plane.svg
  docs/images/corporate-logos/deepc.svg
  docs/images/corporate-logos/fulcrum.svg
  docs/images/corporate-logos/gojek.svg
  docs/images/corporate-logos/google.svg
  docs/images/corporate-logos/ibm.svg
  docs/images/corporate-logos/ka-nabell_japan.svg
  docs/images/corporate-logos/kubesphere.svg
  docs/images/corporate-logos/liquidx.svg
  docs/images/corporate-logos/manomano.svg
  docs/images/corporate-logos/optum.svg
  docs/images/corporate-logos/property_xyz.svg
  docs/images/corporate-logos/redhat.svg
  docs/images/corporate-logos/scaleway.svg
  docs/images/corporate-logos/sonavi_labs.svg
  docs/images/corporate-logos/spider.svg
  docs/images/corporate-logos/tata_comm.svg
  docs/images/corporate-logos/triggermesh_logo.svg
  docs/images/corporate-logos/vmware.svg
  docs/images/corporate-logos/y_meadows.svg
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: lgtm, size/XXL, approved

#5898 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/json-iterator/go/LICENSE
  third_party/VENDOR-LICENSE/github.com/modern-go/concurrent/LICENSE
  third_party/VENDOR-LICENSE/github.com/modern-go/reflect2/LICENSE
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
Labels: lgtm, size/XL, approved

#5896 Sample Bookstore App: DB setup for Book Review Comments
  code-samples/eventing/bookstore-sample-app/db/README.md
  code-samples/eventing/bookstore-sample-app/db/sample.sql
Labels: size/M, lgtm, approved

#5869 Case studies index page and link from homepage
  config/nav.yml
  config/redirects.yml
  docs/about/case-studies/README.md
  hack/docker/run.sh
  overrides/home.html
Labels: size/M, lgtm, approved

#5902 Fix hard-coded version
  docs/install/operator/knative-with-operators.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/snippets/security-prereqs-images.md
Labels: lgtm, size/S, approved

#5906 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5910 Revert "drop eventing-rabbitmq"
  config/nav.yml
  config/redirects.yml
  docs/eventing/brokers/broker-developer-config-options.md
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/channel-based-broker/README.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
  docs/eventing/sources/README.md
  docs/eventing/sources/rabbitmq-source/README.md
  docs/install/operator/knative-with-operator-cli.md
  docs/install/operator/knative-with-operators.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/L, lgtm, approved

#5911 Revert "[release-1.13] add deprecation notices for rabbitmq integration"
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
  docs/eventing/sources/rabbitmq-source/README.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/XS, lgtm, approved

#5912 Revert "[release-1.12] add deprecation notices for rabbitmq integration"
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
  docs/eventing/sources/rabbitmq-source/README.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/XS, lgtm, approved

#5888 Sample App: Notification Service: camel slack sink
  code-samples/eventing/bookstore-sample-app/slack-sink/README.md
  code-samples/eventing/bookstore-sample-app/slack-sink/slack-sink-camel-pipe.yaml
Labels: size/L, lgtm, approved

#5908 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5914 Restructure eventing docs navigation
  config/nav.yml
  docs/eventing/faq/README.md
Labels: size/M, lgtm, approved

#5709 Blog article on "Demystifying activator on the data path"
  blog/config/nav.yml
  blog/docs/articles/demystifying-activator-on-path.md
  blog/docs/articles/images/ebc.png
  blog/docs/articles/images/panic.png
  blog/docs/articles/images/readypods.png
  blog/docs/articles/images/timeline.png
Labels: size/L, lgtm, approved

#5922 Polish the article "Demysifying the activator on data path"
  blog/docs/articles/demystifying-activator-on-path.md
Labels: size/M, lgtm, approved

#5923 Bump min-k8s version to 1.28
  docs/snippets/prerequisites.md
Labels: size/XS, lgtm, approved

#5924 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
