Repository knative/docs, pull requests merged in 2024-01, with the labels that each got.

#5806 Enable copy for code blocks
  mkdocs.yml
Labels: size/XS, lgtm, approved

#5807 Updated Copywrite Information
  blog/mkdocs.yml
  mkdocs.yml
Labels: size/XS, lgtm, approved

#5795 improve grafana configuration steps
  docs/snippets/collecting-metrics.md
Labels: size/M, lgtm, approved

#5812 Resolved the bug in the default styling of note
  docs/eventing/configuration/broker-configuration.md
Labels: size/XS, lgtm, approved

#5814 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5816 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#5817 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5801 Add dynamic date on blog pages
  .gitignore
  blog/docs/articles/build-deploy-manage-modern-serverless-workloads-using-knative-on-kubernetes.md
  blog/docs/articles/distributed-tracing.md
  blog/docs/articles/event-drive-app-knative-eventing-kogito.md
  blog/docs/articles/event-driven-image-bigquery-processing-pipelines.md
  blog/docs/articles/eventing-rabbitmq-announcement.md
  blog/docs/articles/from-cloudevent-to-apach-kafka-records-part-one.md
  blog/docs/articles/from-cloudevent-to-apache-kafka-records-part-two.md
  blog/docs/articles/get-started-knative-eventing.md
  blog/docs/articles/getting-started-blog-p0.md
  blog/docs/articles/getting-started-blog-p1.md
  blog/docs/articles/getting-started-blog-p2.md
  blog/docs/articles/highlighting-value-knative-c-suite.md
  blog/docs/articles/improved-ha-configuration.md
  blog/docs/articles/kafka-broker-with-isolated-data-plane.md
  blog/docs/articles/knative-eventing-vision.md
  blog/docs/articles/knative-serving-in-k0s.md
  blog/docs/articles/knative-v0-3-autoscaling-a-love-story.md
  blog/docs/articles/ko-fast-kubernetes-microservice-development-in-go.md
  blog/docs/articles/new_event_discovery_features.md
  blog/docs/articles/orchestrating-cloud-events-with.md
  blog/docs/articles/performance-test-with-slos.md
  blog/docs/articles/quickstart-with-knative.md
  blog/docs/articles/set-up-a-local-knative-environment-with-kind.md
  blog/docs/articles/single-node-kafka-development.md
  blog/docs/articles/workflow-as-function-flow.md
  blog/docs/events/fuzzing-audit-2023.md
  blog/docs/events/google-summer-of-code-2022.md
  blog/docs/events/google-summer-of-code-2023.md
  blog/docs/events/knative-at-kubecon-na-2022.md
  blog/docs/events/knative-at-kubecon-na-2023.md
  blog/docs/events/knative-projectmeeting-kubecon-eu-2023.md
  blog/docs/events/security-audit-2023.md
  blog/docs/events/virtual-office-hour-12-2022.md
  blog/docs/releases/announcing-knative-1.0.md
  blog/docs/releases/knative-1.0.md
  blog/mkdocs.yml
  blog/overrides/assets/stylesheets/content.css
  blog/overrides/partials/content.html
  blog/overrides/partials/source-file.html
  hack/build.sh
  mkdocs.yml
  requirements.txt
Labels: size/L, lgtm, approved

#5819 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5821 Add edit Button to Documentation Pages
  mkdocs.yml
Labels: size/XS, lgtm, approved

#5822 Add basic doc for eventing OIDC feature
  config/nav.yml
  docs/eventing/experimental-features/README.md
  docs/eventing/experimental-features/sender-identity.md
Labels: size/L, lgtm, approved

#5824 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5818 Document the use of HTTP/1 full duplex support
  config/nav.yml
  docs/serving/services/http-protocol.md
Labels: size/M, lgtm, approved

#5827 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5828 Event types discovery - fix link to eventtype-auto-creation doc
  blog/docs/articles/new_event_discovery_features.md
Labels: size/XS, lgtm, approved

#5831 Add Knative v1.13.0 release blog
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-13-release.md
Labels: size/L, lgtm, approved

#5825 Update transport-encryption.md
  docs/eventing/experimental-features/transport-encryption.md
Labels: size/XS, lgtm, approved

#5836 Use links to artifact on uninstall page
  docs/install/uninstall.md
Labels: size/XS, lgtm, approved

#5837 Update Knative docs to 1.13
  hack/build.sh
Labels: size/XS, lgtm, approved

#5834 Remove sugar controller installation and uninstallation steps
  docs/install/uninstall.md
  docs/install/yaml-install/eventing/eventing-installation-files.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/M, lgtm, approved

#5841 Reflect that the feature is not just for brokers, it is more...
  docs/eventing/experimental-features/eventtype-auto-creation.md
Labels: size/XS, lgtm, approved

#5844 Mention auto-create on event registry doc
  docs/eventing/event-registry.md
Labels: size/XS, lgtm, approved

#5846 Update the docs to reflect the changes for 1.13 operator
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved
