Repository knative/docs, pull requests merged in 2024-05, with the labels that each got.

#5957 Update Knative docs to 1.14
  hack/build.sh
Labels: size/XS, lgtm, approved

#5958 Add release blog Knative 1.14
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-14-release.md
Labels: size/L, lgtm, approved

#5959 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#5955 Improve Serving encryption docs
  docs/serving/encryption/configure-certmanager-integration.md
Labels: lgtm, size/S, approved

#5916 Add SubscriptionsAPI filters to APIServerSource
  config/nav.yml
  docs/eventing/experimental-features/new-apiserversource-filters.md
Labels: size/L, lgtm, approved

#5970 Added the golang redirect for autoscaler-keda and func-python
  golang/_redirects
  golang/autoscaler-keda.html
  golang/func-python.html
Labels: lgtm, size/S, approved

#5967 Update docs for Eventing TLS Beta
  config/nav.yml
  config/redirects.yml
  docs/eventing/event-registry.md
  docs/eventing/features/README.md
  docs/eventing/features/delivery-retryafter.md
  docs/eventing/features/delivery-timeout.md
  docs/eventing/features/eventtype-auto-creation.md
  docs/eventing/features/kreference-group.md
  docs/eventing/features/kreference-mapping.md
  docs/eventing/features/new-apiserversource-filters.md
  docs/eventing/features/new-trigger-filters.md
  docs/eventing/features/sender-identity.md
  docs/eventing/features/transport-encryption.md
  docs/eventing/sources/kafka-source/README.md
  docs/eventing/triggers/README.md
Labels: size/L, lgtm, approved

#5879 Document Eventing istio integration
  config/nav.yml
  docs/eventing/features/README.md
  docs/eventing/features/istio-integration.md
Labels: size/M, lgtm, approved

#5971 Bring back the removed redirects
  golang/_redirects
Labels: size/XS, lgtm, approved

#5991 Add UX leads as docs reviewers
  OWNERS
Labels: size/XS, lgtm, approved

#5992 Adding apache camel k blog post
  blog/config/nav.yml
  blog/docs/articles/knative-meets-apache-camel.md
  blog/docs/index.md
Labels: size/L, lgtm, approved

#5980 fix: Website colour adjustments
  docs/stylesheets/extra.css
  overrides/assets/stylesheets/home.css
Labels: size/M, lgtm, approved

#5949 Intro to open source with knative blog series p3
  blog/config/nav.yml
  blog/docs/articles/getting-started-blog-p0.md
  blog/docs/articles/getting-started-blog-p3.md
  blog/docs/images/getting-started-blog-series/post3/001.png
  blog/docs/images/getting-started-blog-series/post3/002.png
  blog/docs/images/getting-started-blog-series/post3/003.png
  blog/docs/images/getting-started-blog-series/post3/004.png
  blog/docs/images/getting-started-blog-series/post3/005.png
  blog/docs/images/getting-started-blog-series/post3/006.png
  blog/docs/images/getting-started-blog-series/post3/007.png
  blog/docs/images/getting-started-blog-series/post3/008.png
  blog/docs/images/getting-started-blog-series/post3/009.png
Labels: size/L, lgtm, approved

#6001 Added a Blog Post Detailing My LFX Mentorship Project
  blog/config/nav.yml
  blog/docs/articles/enhancing-the-knative-experience.md
  blog/docs/index.md
Labels: size/M, lgtm, approved

#5987 Add new CNCF case study to Knative website
  config/nav.yml
  docs/about/case-studies/README.md
  docs/about/case-studies/ibm.md
  docs/images/case-studies/ibm.png
  overrides/assets/stylesheets/home.css
  overrides/home.html
Labels: size/L, lgtm, approved

#5966 Updated Design of the "Trusted By" Section
  docs/images/corporate-logos/alibaba_cloud.svg
  docs/images/corporate-logos/bloomberg.svg
  docs/images/corporate-logos/blue_origin.svg
  docs/images/corporate-logos/box.svg
  docs/images/corporate-logos/chainguard.svg
  docs/images/corporate-logos/control_plane.svg
  docs/images/corporate-logos/deepc.svg
  docs/images/corporate-logos/fulcrum.svg
  docs/images/corporate-logos/gojek.svg
  docs/images/corporate-logos/google.svg
  docs/images/corporate-logos/grerook.svg
  docs/images/corporate-logos/high_cohesion.svg
  docs/images/corporate-logos/ibm.svg
  docs/images/corporate-logos/ka-nabell_japan.svg
  docs/images/corporate-logos/kubesphere.svg
  docs/images/corporate-logos/liquidx.svg
  docs/images/corporate-logos/manomano.svg
  docs/images/corporate-logos/optum.svg
  docs/images/corporate-logos/property_xyz.svg
  docs/images/corporate-logos/redhat.svg
  docs/images/corporate-logos/scaleway.svg
  docs/images/corporate-logos/sonavi_labs.svg
  docs/images/corporate-logos/spider.svg
  docs/images/corporate-logos/sva.svg
  docs/images/corporate-logos/tata_comm.svg
  docs/images/corporate-logos/vhive.svg
  docs/images/corporate-logos/vmware.svg
  docs/images/corporate-logos/vorteil-direktiv.svg
  docs/images/corporate-logos/y_meadows.svg
  overrides/home.html
Labels: lgtm, size/XXL, approved
