Repository knative/docs, pull requests merged in 2024-04, with the labels that each got.

#5929 [main] Upgrade to latest dependencies
  code-samples/serving/hello-world/helloworld-nodejs/README.md
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5897 Knative Backstage plugin article
  blog/config/nav.yml
  blog/docs/articles/images/knative-backstage-plugins-01.png
  blog/docs/articles/images/knative-backstage-plugins-02.png
  blog/docs/articles/knative-backstage-plugins.md
Labels: size/M, lgtm, approved

#5934 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5933 Docs: Change namespace-wildcard-cert-selector value type from object to string
  docs/serving/encryption/enabling-automatic-tls-certificate-provisioning.md
Labels: size/XS, lgtm, approved

#5855 Add documentation for Serving probes
  config/nav.yml
  docs/serving/configuration/feature-flags.md
  docs/serving/services/configure-probing.md
  docs/serving/services/probes-overview.drawio.svg
Labels: size/L, lgtm, approved

#5931 Sample app frontend
  code-samples/eventing/bookstore-sample-app/frontend/.eslintrc.json
  code-samples/eventing/bookstore-sample-app/frontend/.gitignore
  code-samples/eventing/bookstore-sample-app/frontend/Dockerfile
  code-samples/eventing/bookstore-sample-app/frontend/README.md
  code-samples/eventing/bookstore-sample-app/frontend/app/globals.css
  code-samples/eventing/bookstore-sample-app/frontend/app/layout.tsx
  code-samples/eventing/bookstore-sample-app/frontend/app/page.tsx
  code-samples/eventing/bookstore-sample-app/frontend/client/components/BookDetail.js
  code-samples/eventing/bookstore-sample-app/frontend/client/components/CommentDisplay.js
  code-samples/eventing/bookstore-sample-app/frontend/client/components/CommentForm.js
  code-samples/eventing/bookstore-sample-app/frontend/client/components/CommentList.js
  code-samples/eventing/bookstore-sample-app/frontend/client/components/Emoji.js
  code-samples/eventing/bookstore-sample-app/frontend/client/components/Header.js
  code-samples/eventing/bookstore-sample-app/frontend/client/components/Toggle.js
  code-samples/eventing/bookstore-sample-app/frontend/client/pages/Main.js
  code-samples/eventing/bookstore-sample-app/frontend/next.config.mjs
  code-samples/eventing/bookstore-sample-app/frontend/package-lock.json
  code-samples/eventing/bookstore-sample-app/frontend/package.json
  code-samples/eventing/bookstore-sample-app/frontend/postcss.config.js
  code-samples/eventing/bookstore-sample-app/frontend/public/images/Bookcover.jpg
  code-samples/eventing/bookstore-sample-app/frontend/public/images/avatar.jpg
  code-samples/eventing/bookstore-sample-app/frontend/public/images/knative-logo.png
  code-samples/eventing/bookstore-sample-app/frontend/tailwind.config.ts
  code-samples/eventing/bookstore-sample-app/frontend/tsconfig.json
Labels: lgtm, size/XXL, approved

#5937 fix correct display
  docs/eventing/sources/kafka-source/README.md
Labels: lgtm, size/S, approved

#5935 Implement inappropriate language filter Python script
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/.funcignore
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/.gitignore
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/Procfile
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/app.sh
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/func.py
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/func.yaml
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/requirements.txt
Labels: size/M, lgtm, approved

#5909 Sample App: Adding the db service
  code-samples/eventing/bookstore-sample-app/db-service/100-create-configmap.yaml
  code-samples/eventing/bookstore-sample-app/db-service/100-create-secret.yaml
  code-samples/eventing/bookstore-sample-app/db-service/100-create-volume.yaml
  code-samples/eventing/bookstore-sample-app/db-service/200-create-postgre.yaml
  code-samples/eventing/bookstore-sample-app/db-service/300-expose-service.yaml
  code-samples/eventing/bookstore-sample-app/db-service/400-create-job.yaml
  code-samples/eventing/bookstore-sample-app/db-service/sample.sql
  code-samples/eventing/bookstore-sample-app/db/README.md
Labels: size/L, lgtm, approved

#5895 Add Ceph Source to Event Sources
  docs/eventing/sources/README.md
Labels: size/XS, lgtm, approved

#5940 Add limitations for having OIDC and Istio enabled
  docs/eventing/experimental-features/sender-identity.md
Labels: lgtm, size/S, approved

#5944 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5942 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#5941 Add list with OIDC authn supporting eventing components
  docs/eventing/experimental-features/sender-identity.md
Labels: lgtm, size/S, approved

#5946 [main] Upgrade to latest dependencies
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
Labels: size/L, lgtm, approved

#5928 Sample App: Event Driven Architecture I
  .gitignore
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/Dockerfile
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/broker.yaml
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/deployment.yaml
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/event-display.yaml
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/index.js
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/package-lock.json
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/package.json
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/service.yaml
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/sinkbinding.yaml
  code-samples/eventing/bookstore-sample-app/db/bookstore-eda/trigger.yaml
Labels: lgtm, size/XXL, approved

#5904 Sample App: Adding the knative function build for the sentiment analysis service
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/.funcignore
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/.gitignore
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/Procfile
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/README.md
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/app.sh
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/func.py
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/func.yaml
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/requirements.txt
  code-samples/eventing/bookstore-sample-app/ML-sentiment-analysis/setup.py
Labels: size/L, lgtm, approved

#5947 Sample App: Fix the content in the bad word filter knative function code
  code-samples/eventing/bookstore-sample-app/ML-inappropriate-language-filter/func.py
Labels: lgtm, size/S, approved

#5951 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5939 Notification service docs: Add the tutorial on how to create the slack workspace
  code-samples/eventing/bookstore-sample-app/create-workspace.md
  code-samples/eventing/bookstore-sample-app/screenshots/Postman.png
  code-samples/eventing/bookstore-sample-app/screenshots/result.png
  code-samples/eventing/bookstore-sample-app/screenshots/select-channel.png
  code-samples/eventing/bookstore-sample-app/screenshots/webhooklink.png
Labels: size/M, lgtm, approved

#5952 Adding Kafka Source details on delivery spec
  docs/eventing/sources/kafka-source/README.md
Labels: size/M, lgtm, approved

#5954 Document the remaining timeout settings
  docs/serving/configuration/config-defaults.md
Labels: size/M, lgtm, approved

#5804 Add documentation for Serving Encryption
  config/nav.yml
  config/redirects.yml
  docs/install/installing-cert-manager.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/serving/README.md
  docs/serving/encryption/cluster-local-domain-tls.md
  docs/serving/encryption/configure-certmanager-integration.md
  docs/serving/encryption/enabling-automatic-tls-certificate-provisioning.md
  docs/serving/encryption/encryption-cluster-local-domain.drawio.svg
  docs/serving/encryption/encryption-external-domain.drawio.svg
  docs/serving/encryption/encryption-overview.drawio.svg
  docs/serving/encryption/encryption-overview.md
  docs/serving/encryption/encryption-system-internal.drawio.svg
  docs/serving/encryption/external-domain-tls.md
  docs/serving/encryption/system-internal-tls.md
  docs/serving/encryption/using-certificates-in-networking-layer.md
  docs/serving/services/custom-tls-certificate-domain-mapping.md
  docs/serving/services/http-protocol.md
  docs/snippets/encryption-notice.md
Labels: lgtm, size/XXL, approved
