Repository knative/docs, pull requests merged in 2024-06, with the labels that each got.

#6002 blog link: How IBM watsonx Assistant uses Knative Eventing to train machine learning models
  blog/config/nav.yml
  blog/docs/articles/How-IBM-watsonx-Assistant-uses-Knative-Eventing-to-train-machine-learning-models.md
  blog/docs/articles/images/How-IBM-watsonx-Assistant-uses-Knative-Eventing-to-train-machine-learning-models.png
  blog/docs/index.md
Labels: lgtm, size/S, approved

#6008 chore: update operator supported table for v1.14
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#6005 Add JobSink documentation
  config/nav.yml
  docs/eventing/brokers/broker-developer-config-options.md
  docs/eventing/sinks/README.md
  docs/eventing/sinks/job-sink.md
Labels: size/L, lgtm, approved

#6010 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5993 Add more information about Broker Developer Configuration Options
  docs/eventing/brokers/broker-developer-config-options.md
  docs/eventing/brokers/create-broker.md
Labels: size/M, lgtm, approved

#5976 added Linkedln page link
  overrides/assets/stylesheets/home.css
  overrides/home.html
  overrides/partials/footer.html
Labels: size/M, lgtm, approved

#6014 Adding a new post on S3 events to Knative Functions
  blog/config/nav.yml
  blog/docs/articles/consuming_s3_data_with_knative.md
Labels: size/L, lgtm, approved

#6017 Little fix on typo
  blog/docs/articles/consuming_s3_data_with_knative.md
Labels: size/XS, lgtm, approved

#6015 Remove old warning about istio and external-domain-tls
  docs/serving/encryption/external-domain-tls.md
Labels: size/XS, lgtm, approved

#6019 Correct link to first article
  blog/docs/articles/consuming_s3_data_with_knative.md
Labels: size/XS, lgtm, approved

#6023 Add link to community roles to contributor page
  docs/community/contributing.md
Labels: size/XS, lgtm, approved

#6020 Blog on migrating to Knative Functions
  blog/config/nav.yml
  blog/docs/articles/aws_to_func_migration.md
Labels: size/L, lgtm, approved

#6027 Remove as_updated field in rss plugin
  blog/mkdocs.yml
Labels: size/XS, lgtm, approved

#5965 implemented the new design navbar
  docs/stylesheets/extra.css
  overrides/assets/stylesheets/home.css
Labels: size/M, lgtm, approved

#6022 feat: add docs for runtime-class-name feature
  docs/serving/configuration/deployment.md
Labels: size/M, lgtm, approved
