Repository knative/docs, pull requests merged in 2024-02, with the labels that each got.

#5848 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5850 added docs for kafka scaling to kafka source docs
  docs/eventing/sources/kafka-source/README.md
Labels: lgtm, size/S, approved

#5830 Add linux foundation trademark
  netlify.toml
  overrides/partials/footer.html
Labels: lgtm, size/S, approved

#5854 Document how to set Kafka Topic config options
  docs/eventing/brokers/broker-types/kafka-broker/README.md
Labels: lgtm, size/S, approved

#5858 Update net-istio configuration format
  docs/install/installing-istio.md
  docs/install/operator/configuring-serving-cr.md
  docs/install/operator/knative-with-operators.md
  docs/serving/setting-up-custom-ingress-gateway.md
Labels: size/M, lgtm, approved

#5862 [release-1.13] add deprecation notices for rabbitmq integration
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
  docs/eventing/sources/rabbitmq-source/README.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/XS, lgtm, approved

#5864 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5861 drop eventing-rabbitmq
  config/nav.yml
  config/redirects.yml
  docs/eventing/brokers/broker-developer-config-options.md
  docs/eventing/brokers/broker-types/README.md
  docs/eventing/brokers/broker-types/channel-based-broker/README.md
  docs/eventing/brokers/broker-types/rabbitmq-broker/README.md
  docs/eventing/sources/README.md
  docs/eventing/sources/rabbitmq-source/README.md
  docs/install/operator/knative-with-operator-cli.md
  docs/install/operator/knative-with-operators.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/L, lgtm, approved

#5865 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5852 Blog post about TM committee dissolving
  blog/config/nav.yml
  blog/docs/steering/2024-02-14-trademark-committee-dissolved.md
  docs/community/governance.md
Labels: size/M, lgtm, approved

#5866 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#5867 queue-sidecar annotations should be defined under spec.template.metad…
  docs/serving/services/configure-requests-limits-services.md
Labels: lgtm, size/S, approved

#5868 Add SVA case study
  config/nav.yml
  docs/about/case-studies/sva.md
  docs/images/case-studies/sva.png
Labels: size/M, lgtm, approved

#5753 Add support s390x and ppc64le archs
  .github/workflows/knative-docs-image.yaml
Labels: size/XS, lgtm, approved

#5872 Update knative-offerings.md
  docs/install/knative-offerings.md
Labels: size/XS, lgtm, approved

#5875 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#5877 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved
