Repository knative/docs, pull requests merged in 2025-05, with the labels that each got.

#6269 Update install-eventing-with-yaml.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
Labels: size/XS, lgtm, ok-to-test, approved

#6272 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#6273 Update web community info to remove TOC and duplication of audience info
  docs/community/governance.md
Labels: size/M, lgtm, approved
