Repository knative/docs, pull requests merged in 2025-09, with the labels that each got.

#6358 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review

#6352 [serving] OTel Metrics Documentation
  config/nav.yml
  docs/eventing/observability/metrics/collecting-metrics.md
  docs/eventing/observability/metrics/collector.yaml
  docs/eventing/observability/metrics/eventing-metrics.md
  docs/eventing/observability/metrics/system-diagram.svg
  docs/serving/observability/metrics/collecting-metrics.md
  docs/serving/observability/metrics/collector.yaml
  docs/serving/observability/metrics/serving-metrics.md
  docs/serving/observability/metrics/system-diagram.svg
  docs/snippets/collecting-metrics.md
  docs/snippets/observability-shared-metrics.md
Labels: lgtm, size/XL, approved

#6360 OTel docs follow up
  docs/serving/observability/metrics/serving-metrics.md
  docs/snippets/observability-shared-metrics.md
Labels: size/M, lgtm, approved

#6367 Knative quickstart - content tab fixes, added success output for kn func
  docs/snippets/proc-running-function.md
Labels: lgtm, size/S, ok-to-test, approved

#6373 drop old serving metrics documentation
  config/redirects.yml
  docs/.nav.yml
  docs/serving/services/service-metrics.md
Labels: size/M, lgtm, approved

#6377 [release-1.19] drop old serving metrics documentation
  config/nav.yml
  config/redirects.yml
  docs/serving/services/service-metrics.md
Labels: size/M, lgtm, approved

#6379 [release-1.18] Updated the docs for operator 1.18
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#6384 Fix site base URL, which should fix some asset links
  mkdocs.yml
Labels: size/XS, lgtm, approved

#6387 add dependabot to update actions
  .github/dependabot.yaml
Labels: size/XS, lgtm, approved

#6396 fix: change OIDC disabled to enabled
  docs/eventing/features/authorization.md
Labels: size/XS, lgtm, approved

#6392 Fix site search
  hack/build.sh
  mkdocs.yml
  netlify.toml
  overrides/assets/javascripts/bundle.0af37618.min.js
  overrides/main.html
Labels: size/M, lgtm, approved

#6395 Installation Doc Updates
  docs/.nav.yml
  docs/client/install-kn.md
  docs/install/README.md
  docs/install/operator/knative-with-operator-cli.md
  docs/install/operator/knative-with-operators.md
  docs/install/quickstart-install.md
  docs/install/yaml-install/eventing/install-eventing-with-yaml.md
  docs/install/yaml-install/serving/install-serving-with-yaml.md
  docs/snippets/install-kn.md
Labels: size/L, lgtm, approved

#6400 Undo different example output for kn func invoke
  docs/snippets/proc-running-function.md
Labels: size/M, lgtm, approved

#6369 feat: Add pod identity note for ECR access
  contribute-to-docs/getting-started/formatting.md
  docs/versioned/install/operator/configuring-serving-cr.md
Labels: size/L, lgtm, approved

#6410 Added link to AWS Pod identity docs
  docs/versioned/install/operator/configuring-serving-cr.md
Labels: size/XS, lgtm, approved
