Repository knative/docs, pull requests merged in 2025-04, with the labels that each got.

#6247 fix: fix typo in configuring serving cr
  docs/install/operator/configuring-serving-cr.md
Labels: size/XS, lgtm, approved

#6256 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/modules.txt
Labels: size/L, lgtm, approved

#6257 Update mkdocs.md for 2025 year
  mkdocs.yml
Labels: size/XS, lgtm, approved

#6258 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6239 Helm: create and use 'knative-operator' namespace
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#6259 Updated the docs about Knative Operator 1.18
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#6260 new release 1.18
  hack/build.sh
Labels: size/XS, lgtm, approved

#6261 Blog: new blog for 1.18 release
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-18-release.md
Labels: size/L, lgtm, approved
