Repository knative/docs, pull requests merged in 2025-07, with the labels that each got.

#6289 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6290 Kubevirt/Eventing blog
  blog/config/nav.yml
  blog/docs/articles/images/kubevirt-meets-eventing-flow.png
  blog/docs/articles/kubevirt_meets_eventing.md
Labels: size/L, lgtm, approved

#6288 Add skip permissions option to ApiServerSource
  docs/eventing/sources/apiserversource/reference.md
Labels: size/M, lgtm, approved

#6294 Fix: wrong filters attribute in trigger document
  docs/eventing/triggers/README.md
Labels: size/XS, lgtm, approved

#6299 Update for release 1.19 in build.sh
  hack/build.sh
Labels: size/XS, lgtm, approved

#6300 New blog post for 1.19 release
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-19-release.md
Labels: size/L, lgtm, approved
