Repository knative/docs, pull requests merged in 2025-01, with the labels that each got.

#6189 chore: fix typo in sample parallel README
  code-samples/eventing/parallel/multiple-branches/README.md
Labels: size/XS, lgtm, approved

#6193 Add documentation on fetching Knative supply-chain security attestations
  config/nav.yml
  docs/reference/security/verifying-images.md
Labels: size/M, lgtm, approved

#6194 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#6171 add alauda logo to trusted by secion
  docs/images/corporate-logos/alauda.svg
  overrides/home.html
Labels: lgtm, size/S, approved

#6197 Add interconnected as an attribute of the Event Mesh definition
  docs/eventing/event-mesh.md
Labels: size/XS, lgtm, approved

#6196 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#6199 Link to supply-chain details rather than including inline.
  docs/reference/security/verifying-images.md
  docs/snippets/security-prereqs-images.md
Labels: size/M, lgtm, approved

#6175 docs: update README to reflect CronJobSource renamed to PingSource
  docs/eventing/event-registry/README.md
Labels: size/XS, lgtm, approved

#6201 Document KafkaSource v1 API
  code-samples/eventing/kafka/binding/event-source.yaml
  docs/eventing/event-registry/README.md
  docs/eventing/sinks/job-sink.md
  docs/eventing/sources/kafka-source/README.md
  docs/eventing/sources/kafka-source/event-source.yaml
Labels: lgtm, size/S, approved

#6202 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6206 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#6208 Add release blog for Knative v1.17
  blog/config/nav.yml
  blog/docs/index.md
  blog/docs/releases/announcing-knative-v1-17-release.md
  blog/docs/releases/images/release1.17-1.png
Labels: size/L, lgtm, approved

#6207 Update operator supported version to v1.17
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#6209 Update version switch with latest 1.17
  hack/build.sh
Labels: size/XS, lgtm, approved

#6211 Updated the default namespace for operator
  docs/install/operator/knative-with-operators.md
Labels: size/XS, lgtm, approved

#6210 fix serving typos
  blog/docs/releases/announcing-knative-v1-17-release.md
Labels: size/XS, lgtm, approved
